(function(g){var window=this;'use strict';var RA=function(G){G.publish("cardstatechange",G.fX()&&G.Wb()?1:0)},pF=function(G,m){var w=g.Uq(m),W=w?m:arguments;
for(w=w?0:1;w<W.length;w++){if(G==null)return;G=G[W[w]]}return G},RNm=function(G){var m=g.Xa(G);
G=g.mF(G);return new g.JN(m.x,m.y,G.width,G.height)},pU9=function(G,m,w){var W=W===void 0?{}:W;
var U;return U=g.i4(G,m,function(){g.K6(U);w.apply(G,arguments)},W)},Pq=function(G){G=g.Q9(G);
delete j2[G];g.$u(j2)&&S2&&S2.stop()},S1H=function(){S2||(S2=new g.ey(function(){jeR()},20));
var G=S2;G.isActive()||G.start()},jeR=function(){var G=g.Tm();
g.y9(j2,function(m){Puq(m,G)});
g.$u(j2)||S1H()},oA=function(G,m,w,W){g.sN.call(this);
if(!Array.isArray(G)||!Array.isArray(m))throw Error("Start and end parameters must be arrays");if(G.length!=m.length)throw Error("Start and end points must be the same length");this.Y=G;this.L=m;this.duration=w;this.j=W;this.coords=[];this.progress=this.K=0;this.D=null},Puq=function(G,m){m<G.startTime&&(G.endTime=m+G.endTime-G.startTime,G.startTime=m);
G.progress=(m-G.startTime)/(G.endTime-G.startTime);G.progress>1&&(G.progress=1);G.K=1E3/(m-G.D);G.D=m;oT9(G,G.progress);G.progress==1?(G.V=0,Pq(G),G.onFinish(),G.s5()):G.isPlaying()&&G.mO()},oT9=function(G,m){typeof G.j==="function"&&(m=G.j(m));
G.coords=Array(G.Y.length);for(var w=0;w<G.Y.length;w++)G.coords[w]=(G.L[w]-G.Y[w])*m+G.Y[w]},hNd=function(G,m){g.eQ.call(this,G);
this.coords=m.coords;this.x=m.coords[0];this.y=m.coords[1];this.z=m.coords[2];this.duration=m.duration;this.progress=m.progress;this.fps=m.K;this.state=m.V},hH=function(G,m,w,W,U){oA.call(this,m,w,W,U);
this.element=G},l8d=function(G,m,w,W,U){if(m.length!=2||w.length!=2)throw Error("Start and end points must be 2D");
hH.call(this,G,m,w,W,U)},Cuq=function(G){return Math.pow(G,3)},ET9=function(G){return 3*G*G-2*G*G*G},JbR=function(G){g.J.call(this);
this.Y=G||window;this.V=[]},lt=function(G){return G.baseUrl||null},CF=function(G,m){return g.g$(g.iI(G,m),function(w){return!!w})},rbn=function(G,m,w){function W(Oo){var QZ=Oo.hovercardButton;
if(!QZ)return null;QZ=QZ.subscribeButtonRenderer;if(!QZ)return null;var D$=c(QZ.unsubscribedButtonText),me=c(QZ.subscribedButtonText);if(QZ.subscribed){var dd=c(QZ.subscriberCountWithUnsubscribeText);var Y6=c(QZ.subscriberCountText)}else dd=c(QZ.subscriberCountText),Y6=c(QZ.subscriberCountWithSubscribeText);var Gm=null;if(Oo.signinEndpoint){Gm=pF(Oo,"signinEndpoint","webNavigationEndpointData","url");if(!Gm){var iR,vg;Gm=(vg=g.n((iR=QZ.signInEndpoint)==null?void 0:iR.commandMetadata,g.VD))==null?
void 0:vg.url}if(!Gm)return null}return D$&&(me||Gm)?{subscribed:QZ.subscribed,subscribeText:D$,subscribeCount:dd,unsubscribeText:me,unsubscribeCount:Y6,enabled:QZ.enabled,signinUrl:Gm,classic:Oo.useClassicSubscribeButton}:null}
function U(Oo){if(Oo){var QZ=[],D$=Oo.videoId;D$&&QZ.push("v="+D$);(D$=Oo.playlistId)&&QZ.push("list="+D$);(Oo=Oo.startTimeSeconds)&&QZ.push("t="+Oo);return"/watch?"+QZ.join("&")}}
function c(Oo){if(!Oo)return null;var QZ=Oo.simpleText;return QZ?QZ:Oo.runs?g.iI(Oo.runs,function(D$){return D$.text}).join(""):null}
m=m.endscreenElementRenderer;if(!m)return null;var Q=m.style,D=m.endpoint||{},O=null,q=null,T=!1,a=null,Z=null,k=null,K=null,M=!1,t=null,R=null,f=null,P=null,E=null,e=null;if(Q==="VIDEO")g.n(D,g.S3)?O=g.n(D,g.S3).url:(e=g.n(D,g.L_),O=U(e)),q=!1,a=G,m.thumbnailOverlays?(T=m.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,Z=c(T.text),T=T.style==="LIVE"):Z=c(m.videoDuration);else if(Q==="PLAYLIST")g.n(D,g.S3)?O=g.n(D,g.S3).url:(e=g.n(D,g.L_),O=U(e)),q=!1,a=G,k=c(m.playlistLength);else if(Q===
"CHANNEL"){if(M=pF(D,"browseEndpoint","browseId"))K=M,O="/channel/"+K;q=!1;a="new";(M=!!m.isSubscribe)?t=W(m):R=c(m.subscribersText)}else Q==="WEBSITE"?((f=pF(D,"urlEndpoint","url"))&&(O=f),q=!0,a="new",f=m.icon.thumbnails[0].url):Q==="CREATOR_MERCHANDISE"&&(m.productPrice&&(P=c(m.productPrice)),m.additionalFeesText&&(E=c(m.additionalFeesText)),(q=pF(D,"urlEndpoint","url"))&&(O=q),q=!0,a="new");G=pF(m,"title","accessibility","accessibilityData","label");var A=m.endpoint?m.endpoint.clickTrackingParams:
null,Y="";if(m.metadata){var vW=c(m.metadata);vW&&(Y=vW)}return{id:"element-"+w,type:Q,title:c(m.title),metadata:Y,callToAction:c(m.callToAction),je:m.image,iconUrl:f,left:Number(m.left),width:Number(m.width),top:Number(m.top),aspectRatio:Number(m.aspectRatio),startMs:Math.floor(Number(m.startMs)),endMs:Math.floor(Number(m.endMs)),videoDuration:Z,Nz:T,playlistLength:k,channelId:K,subscribeButton:t,subscribersText:R,isSubscribe:M,targetUrl:O||null,ov:q,sessionData:A?{itct:A}:null,qYp:a,oK:G?G:null,
isPlaceholder:m.isPlaceholder,impressionUrls:CF(m.impressionUrls||[],lt),rb:CF(m.hovercardShowUrls||[],lt),clickUrls:CF(D.loggingUrls||[],lt),visualElement:g.iD(m.trackingParams),productPrice:P,additionalFeesText:E,watchEndpoint:e||null}},FQm=function(G,m){var w={startMs:Math.floor(Number(G.startMs)),
impressionUrls:CF(G.impressionUrls||[],lt),elements:CF(G.elements||[],function(W,U){return rbn(m,W,U)})};
G.trackingParams&&(w.visualElement=g.iD(G.trackingParams));return w},eNd=function(G){g.bK.call(this,G);
this.D=this.endscreen=null;this.Y={};this.K={};this.j=this.X=null;this.C=[];this.V=null;this.YB=!0;this.L=0;G=G.S();this.U=g.va(G)||g.OV(G);this.events=new g.Mh(this);g.r(this,this.events);this.events.T(this.player,g.uA("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.H_("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.GP);this.events.T(window,"focus",this.qQj);this.load();var m=g.aI("STYLE");(g.sx("HEAD")[0]||document.body).appendChild(m);this.addOnDisposeCallback(function(){g.Nb(m)});
m.sheet&&(m.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),m.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},nTq=function(G){return G.player.getVideoData().UL?"current":G.U?"new":"current"},EO=function(G){return G.player.S().playerStyle==="creator-endscreen-editor"},xsH=function(G){var m=G.player.getVideoData(),w=m.videoId;
G.D&&G.D.abort();w={method:"POST",onFinish:function(U){var c=G.D=null;U.status===200&&(U=U.responseText,U.substring(0,3)===")]}"&&(U=U.substring(3),c=JSON.parse(U),c=FQm(c,nTq(G))));JH(G,c)},
urlParams:{v:w},withCredentials:!0};G.U&&(w.urlParams.ptype="embedded");var W=m.SJ;W&&(w.postParams={ad_tracking:W});if(m=g.JiW(m))if(m=g.Qa(m),m=g.Ua(m))G.D=g.N4(m,w)},JH=function(G,m,w){w=w===void 0?!0:w;
G.player.eZ("creatorendscreen");G.X&&(G.X.dispose(),G.X=null,G.j.dispose(),G.j=null);for(var W=g.V(Object.values(G.Y)),U=W.next();!U.done;U=W.next())U.value.dispose();G.Y={};G.K={};G.C.length>0&&(G.C.forEach(function(D){D.dispose()}),G.C.length=0);
G.V&&(g.wV(G.V,"ytp-ce-element-show"),G.V.setAttribute("aria-hidden","true"));G.L=0;if((G.endscreen=m)&&m.elements){w&&u5d(G);w=[];W=new g.nk(m.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});w.push(W);G.player.S().Y||(G.X=new g.x({B:"div",Z:"ytp-ce-shadow"}),g.ye(G.player,G.X.element,4),G.j=new g.XT(G.X,200));for(W=0;W<m.elements.length;++W){U=m.elements[W];var c=HsH(G,U);if(c){G.Y[U.id]=c;G.K[U.id]=U;g.ye(G.player,c.element,4);var Q=new g.nk(U.startMs,U.endMs,{id:"ytp-ce-element-"+
U.id,namespace:"creatorendscreen"});w.push(Q);Y1b(G,c,U)}else g.f4(new g.J0("buildEndscreenElement null",U))}G.player.Zr(w);G.GP()}},u5d=function(G){var m=g.N7(),w=g.IC();
w&&m&&G.endscreen.visualElement&&g.x4(g.rR)(void 0,w,m,G.endscreen.visualElement)},HsH=function(G,m){var w=null;
switch(m.type){case "VIDEO":G={B:"div",fM:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":m.oK||"","aria-hidden":"true"},G:[{B:"div",Z:"ytp-ce-element-shadow"},{B:"div",Z:"ytp-ce-covering-image",W:rv(m)},{B:"div",Z:"ytp-ce-covering-shadow-top"},{B:"a",Z:"ytp-ce-covering-overlay",W:{href:Fc(G,m.targetUrl),tabindex:"-1"},G:[{B:"div",fM:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.ON(m.title||"")},l6:m.title},{B:"div",Z:m.Nz?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
l6:m.videoDuration||void 0}]}]};w=new g.x(G);break;case "PLAYLIST":G={B:"div",fM:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":m.oK||"","aria-hidden":"true"},G:[{B:"div",Z:"ytp-ce-element-shadow"},{B:"div",Z:"ytp-ce-covering-image",W:rv(m)},{B:"div",Z:"ytp-ce-covering-shadow-top"},{B:"a",Z:"ytp-ce-covering-overlay",W:{href:Fc(G,m.targetUrl),tabindex:"-1"},G:[{B:"div",fM:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.ON(m.title||"")},l6:m.title},{B:"div",Z:"ytp-ce-playlist-count",
G:[{B:"div",Z:"ytp-ce-playlist-icon"},{B:"div",Z:"ytp-ce-playlist-count-text",l6:m.playlistLength||void 0}]}]}]};w=new g.x(G);break;case "CHANNEL":w={B:"div",fM:["ytp-ce-element","ytp-ce-channel",m.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":m.oK||"","aria-hidden":"true"},G:[{B:"div",Z:"ytp-ce-element-shadow"},{B:"div",Z:"ytp-ce-expanding-overlay",G:[{B:"div",Z:"ytp-ce-expanding-overlay-hider"},{B:"div",Z:"ytp-ce-expanding-overlay-background"},{B:"div",Z:"ytp-ce-expanding-overlay-content",
G:[{B:"div",Z:"ytp-ce-expanding-overlay-body",G:[{B:"div",Z:"ytp-ce-expanding-overlay-body-padding",G:[{B:"a",fM:["ytp-ce-channel-title","ytp-ce-link"],W:{href:Fc(G,m.targetUrl),target:"_blank",tabindex:"-1",dir:g.ON(m.title||"")},l6:m.title},m.subscribeButton?{B:"div",Z:"ytp-ce-subscribe-container",G:[{B:"div",Z:"ytp-ce-channel-subscribe"}]}:"",m.subscribersText?{B:"div",Z:"ytp-ce-channel-subscribers-text",l6:m.subscribersText}:"",m.metadata?{B:"div",fM:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],l6:m.metadata}:""]}]}]}]},{B:"div",Z:"ytp-ce-expanding-image",W:rv(m)}]};w=new g.x(w);var W=g.Q7(document,"div","ytp-ce-channel-subscribe",w.element)[0];if(m.subscribeButton&&m.channelId){g.Gb(W,"ytp-ce-subscribe-button");if(G.player.S().Y){var U=null;var c=m.sessionData.itct}else U="endscreen",c=null;U=new g.UW(m.subscribeButton.subscribeText,m.subscribeButton.subscribeCount,m.subscribeButton.unsubscribeText,m.subscribeButton.unsubscribeCount,!!m.subscribeButton.enabled,!!m.subscribeButton.classic,
m.channelId,!!m.subscribeButton.subscribed,U,c,G.player,!1);W.appendChild(U.element);G.C.push(U)}break;case "WEBSITE":G={B:"div",fM:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":m.oK||"","aria-hidden":"true"},G:[{B:"div",Z:"ytp-ce-element-shadow"},{B:"div",Z:"ytp-ce-expanding-overlay",G:[{B:"div",Z:"ytp-ce-expanding-overlay-hider"},{B:"div",Z:"ytp-ce-expanding-overlay-background"},{B:"div",Z:"ytp-ce-expanding-overlay-content",G:[{B:"div",Z:"ytp-ce-expanding-overlay-body",G:[{B:"div",
Z:"ytp-ce-expanding-overlay-body-padding",G:[{B:"div",Z:"ytp-ce-website-title",W:{dir:g.ON(m.title||"")},l6:m.title},{B:"div",Z:"ytp-ce-website-metadata",l6:m.metadata},{B:"a",fM:["ytp-ce-website-goto","ytp-ce-link"],W:{href:Fc(G,m.targetUrl),target:"_blank",tabindex:"-1"},l6:m.callToAction}]}]}]}]},{B:"div",Z:"ytp-ce-expanding-image",W:rv(m)},{B:"div",Z:"ytp-ce-expanding-icon",W:BXd(m.iconUrl)}]};w=new g.x(G);break;case "CREATOR_MERCHANDISE":w="",m.productPrice&&(w={B:"div",Z:"ytp-ce-merchandise-price-container",
G:[{B:"div",Z:"ytp-ce-merchandise-price",l6:m.productPrice}]},m.additionalFeesText&&w.G.push({B:"div",Z:"ytp-ce-merchandise-additional-fees",l6:m.additionalFeesText})),G={B:"div",fM:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":m.oK||"","aria-hidden":"true"},G:[{B:"div",Z:"ytp-ce-element-shadow"},{B:"div",Z:"ytp-ce-expanding-overlay",G:[{B:"div",Z:"ytp-ce-expanding-overlay-hider"},{B:"div",Z:"ytp-ce-expanding-overlay-background"},{B:"div",Z:"ytp-ce-expanding-overlay-content",
G:[{B:"div",Z:"ytp-ce-expanding-overlay-body",G:[{B:"div",Z:"ytp-ce-expanding-overlay-body-padding",G:[{B:"div",Z:"ytp-ce-merchandise-title",W:{dir:g.ON(m.title||"")},l6:m.title},w,{B:"div",Z:"ytp-ce-merchandise-metadata",l6:m.metadata},{B:"a",fM:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:Fc(G,m.targetUrl),target:"_blank",tabindex:"-1"},l6:m.callToAction}]}]}]}]},{B:"div",Z:"ytp-ce-expanding-image",W:rv(m)},{B:"div",Z:"ytp-ce-merchandise-invideo-cta-container",G:[{B:"div",Z:"ytp-ce-merchandise-invideo-cta",
l6:m.callToAction||void 0}]}]},w=new g.x(G)}m.isPlaceholder&&g.Gb(w.element,"ytp-ce-placeholder");return w},rv=function(G){if(G.je)var m=G.je.thumbnails;
return BXd(m?m[m.length-1].url:null)},BXd=function(G){return G?{style:"background-image: url("+G+")"}:{}},Y1b=function(G,m,w){function W(O){O&&(m.listen("blur",function(){O.style.display!="none"&&G.YB&&O.focus()}),m.T(O,"focus",c),m.T(O,"blur",Q))}
function U(O){G.L+=O;G.L>0?(g.Gb(m.element,"ytp-ce-force-expand"),e2(G,w.id,!0)):(g.wV(m.element,"ytp-ce-force-expand"),g.wV(m.element,"ytp-ce-element-hover"),e2(G,w.id,!1))}
function c(){U(1)}
function Q(){U(-1)}
m.listen("mouseenter",function(){Ab4(G,m,w)});
m.listen("mouseleave",function(){XU4(G,m,w)});
G.player.S().Y||m.listen("click",function(){g.Gb(m.element,"ytp-ce-element-hover")});
m.listen("click",function(O){ybq(G,w,O)});
m.listen("keypress",function(O){ybq(G,w,O)});
m.listen("focus",function(){Ab4(G,m,w)});
m.listen("blur",function(){XU4(G,m,w)});
m.listen("touchstart",function(){Ab4(G,m,w)});
var D=g.vC("ytp-ce-expanding-overlay-hider",m.element);D&&m.T(D,"touchstart",function(O){O.stopPropagation();g.wV(m.element,"ytp-ce-element-hover");g.wV(m.element,"ytp-ce-force-expand")});
m.listen("keydown",function(O){G.YB=O.keyCode===9&&!O.shiftKey});
W(g.vC("ytp-sb-subscribe",m.element));W(g.vC("ytp-sb-unsubscribe",m.element));m.listen("focus",c);m.listen("blur",Q)},ybq=function(G,m,w){if(m.targetUrl&&(!w||w.type!=="keypress"||w.keyCode===13)){for(var W=w.target;W&&!g.yR(W,"ytp-ce-element");){g.yR(W,"subscribe-label")&&GXb(G,m);
if(g.yR(W,"ytp-ce-channel-subscribe"))return;W=W.parentElement||null}if(!W||g.yR(W,"ytp-ce-element-hover")){w.preventDefault();w.stopPropagation();if(W=G.Y[m.id])XU4(G,W,m),W.element.blur();if(w.ctrlKey||w.metaKey||m.qYp==="new")GXb(G,m),G.player.sendVideoStatsEngageEvent(17,void 0),G.player.pauseVideo(),w=g.Qa(Fc(G,m.targetUrl)),w=g.Ua(w),g.JI(w,void 0,m.sessionData);else{var U=g.Mu(G.player.S())||G.player.getVideoData().UL,c=function(){var Q=Fc(G,m.targetUrl),D=m.sessionData,O=m.watchEndpoint,q=
g.X7(Q);U&&q&&(q.v||q.list)?G.player.NH(q.v,D,q.list,!1,void 0,O||void 0):g.EX(Q,D)};
GXb(G,m,function(){G.player.sendVideoStatsEngageEvent(17,c)})}}}},Fc=function(G,m){G=G.player.S();
if(m){if(m.startsWith("//"))return G.protocol+":"+m;if(m.startsWith("/"))return g.pe(G)+m}else return"";return m},Ab4=function(G,m,w){g.yR(m.element,"ytp-ce-element-hover")||(w.type==="VIDEO"||w.type==="PLAYLIST"?g.Gb(m.element,"ytp-ce-element-hover"):G.player.S().Y?(new g.ey(function(){g.Gb(m.element,"ytp-ce-element-hover")},200)).start():g.Gb(m.element,"ytp-ce-element-hover"),nF(G,w.rb),e2(G,w.id,!0))},XU4=function(G,m,w){g.wV(m.element,"ytp-ce-element-hover");
g.wV(m.element,"ytp-ce-force-expand");e2(G,w.id,!1)},e2=function(G,m,w){G.X&&(w?G.j.show():G.j.hide());
for(var W=g.V(Object.keys(G.Y)),U=W.next();!U.done;U=W.next())U=U.value,U!==m&&g.UN(G.Y[U].element,"ytp-ce-element-shadow-show",w)},nF=function(G,m,w){function W(){c||(U++,U===m.length&&(Q.stop(),w&&w()))}
if(!m||m.length===0||EO(G))w&&w();else{m=mie(G,m);var U=0,c=!1,Q=new g.ey(function(){c=!0;w&&w()},1E3,G);
Q.start();for(G=0;G<m.length;G++)g.Pn(m[G],W)}},GXb=function(G,m,w){nF(G,m.clickUrls,w);
(G=g.IC())&&m.ov&&g.yX(G,m.visualElement)},mie=function(G,m){var w=G.player.getVideoData().clientPlaybackNonce;
G=G.player.getCurrentTime().toFixed(2);w={CPN:w,AD_CPN:w,MT:G};G=[];for(var W=0;W<m.length;W++)G.push(wxg(m[W],w));return G},wxg=function(G,m){return G.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(w){var W=unescape(w);
W=W.substring(1,W.length-1);return m[W]?escape(m[W]):w})},Wld=function(G){return typeof G==="string"?G:""},xP=function(G,m,w){for(var W in m)if(m[W]===G)return G;
return w},Uiq=function(G,m,w,W){this.value=G;
this.target=m;this.showLinkIcon=w;this.V=W},ut=function(G){return G.value?G.value:null},Hq=function(G){if(!G)return null;
var m=g.Qa(Wld(G.value));m=g.Ua(m);if(!m)return null;var w=xP(G.target,sbc,"current");if(w==null)G=null;else{var W=G.show_link_icon;G=new Uiq(m,w,W==="true"||W==="false"?W==="true":!0,G.pause_on_navigation!=null?G.pause_on_navigation:!0)}return G},c6g=function(G,m,w){this.type=G;
this.trigger=m;this.url=w},DiR=function(G){if(!G)return null;
var m=xP(G.type,Qbq),w=xP(G.trigger,v14);G=G.url;G=Array.isArray(G)&&G.length?G[0]:G;G=Hq(G?G:null);return m?new c6g(m,w,G):null},O0z=function(G,m,w,W,U){this.id=G;
this.type=m;this.style=w;this.data=U;this.action=W||[]},qzH=function(G,m){return g.Nn(G.action,m)},T3H=function(G,m){this.context=G;
this.V=m},$iR=function(G){return G.customMessage?YP("div","iv-card-message",G.customMessage):""},Bq=function(G,m){G="background-image: url("+G+");";
var w=[];m&&w.push(m);return{B:"div",Z:"iv-card-image",W:{style:G},G:w}},aIg=function(G){if(!G.metaInfo||G.metaInfo.length===0)return"";
var m=[];G=g.V(G.metaInfo);for(var w=G.next();!w.done;w=G.next())m.push(YP("li","",w.value));return{B:"ul",Z:"iv-card-meta-info",G:m}},YP=function(G,m,w){m?typeof m==="string"?m={"class":m}:Array.isArray(m)&&(m={"class":m.join(" ")}):m={};
m.dir=g.ON(w);return{B:G,W:m,l6:w}},Z0q=function(G){if(!G.customMessage)return"";
var m=["iv-card-action","iv-card-primary-link"],w={};G.uT&&(m.push("iv-card-action-icon"),w.style="background-image: url("+G.uT+");");w.dir=g.ON(G.customMessage);var W=[{B:"span",l6:G.customMessage}];G.showLinkIcon&&(W.push("\u00a0"),W.push({B:"span",Z:"iv-card-link-icon"}));return{B:"div",fM:m,W:w,G:W}},AH=function(G,m,w,W){if(W){m=g.V(m);
for(var U=m.next();!U.done;U=m.next())G.V(U.value,W,w.id,w.sessionData,w.ET.click,5)}},kXg=function(G,m){this.merchant=G;
this.price=m},i0m=function(G){var m;
(m=G)&&!(m=G.length>1?G.charAt(0)==="/"&&G.charAt(1)!=="/":G==="/")&&(m=G.replace(/^(https?:)?\/\//,"").split("/",1),m=!m||m.length<1||!m[0]?[]:m[0].toLowerCase().split(".").reverse(),m=m[0]==="com"&&m[1]==="youtube"||m[0]==="be"&&m[1]==="youtu");return m?G.indexOf("/redirect?")===-1:!1},Klz=function(G,m){return m?m:i0m(G)?"current":"new"},Xc=function(G,m){g.J.call(this);
var w=this;this.element=G;this.context=m;this.Qj=!1;this.OM=new Map;this.kB=new Map;this.context.N.addEventListener(g.uA("annotations_module"),function(W){(W=w.OM.get(W))&&W.apply(w)});
this.context.N.addEventListener(g.H_("annotations_module"),function(W){(W=w.kB.get(W))&&W.apply(w)})},yw=function(G,m,w,W,U,c,Q){G.context.V.listen(m,"click",function(D){G.z5(w,W,U,c||[],Q||0,D)});
G.context.V.listen(m,"touchstart",function(){G.Qj=!1});
G.context.V.listen(m,"touchmove",function(){G.Qj=!0})},N3q=function(G){var m;
return((m=g.n(G,g.S3))==null?0:m.url)?g.n(G,g.S3).url:(G=g.n(G,g.L_))&&G.videoId?(m="/watch?v="+G.videoId,G.playlistId&&(m+="&list="+G.playlistId),G.index&&(m+="&index="+G.index),G.startTimeSeconds&&(m+="&t="+G.startTimeSeconds),m):null},GP=function(G,m,w){return{Gp:(G.impressionLoggingUrlsV2s||[]).map(function(W){return W.baseUrl||""}),
click:(w.loggingUrls||[]).map(function(W){return W.baseUrl||""}),
close:(m.dismissLoggingUrlsV2s||[]).map(function(W){return W.baseUrl||""}),
OI:(m.impressionLoggingUrlsV2s||[]).map(function(W){return W.baseUrl||""}),
Dl:(m.clickLoggingUrlsV2s||[]).map(function(W){return W.baseUrl||""})}},IIm=function(G,m,w){Xc.call(this,m,w);
var W=this;this.N=G;this.eventId=null;this.aM=this.Pk=this.Bl=this.X=this.isInitialized=!1;this.cards=[];this.hY=this.j=this.pM=this.K=this.Z6=this.V=null;this.YB=[];this.D6=this.C=this.Yj=this.rd=null;this.L=0;this.J4=new g.ey(function(){},w.h4.NJ?4E3:3E3);
g.r(this,this.J4);this.u6=new g.ey(function(){});
g.r(this,this.u6);this.M9=new T3H(w,function(U,c,Q,D,O,q){yw(W,U,c,Q,D,O,q)});
this.U=new g.x({B:"div",Z:"iv-drawer",W:{id:"iv-drawer"},G:[{B:"div",Z:"iv-drawer-header",W:{"aria-role":"heading"},G:[{B:"span",Z:"iv-drawer-header-text"},{B:"button",fM:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Masquer les fiches",tabindex:"0"}}]},{B:"div",Z:"iv-drawer-content"}]});g.r(this,this.U);this.D=this.U.element;this.yj=new g.XT(this.U,330);g.r(this,this.yj);this.x5=g.vC("iv-drawer-header-text",this.D);this.Y=g.vC("iv-drawer-content",this.D);this.addCueRange(0,w.videoData.lengthSeconds*
1E3,"",function(){W.Bl&&mf(W,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(W.Bl=W.X)&&wC(W)});
this.EM=new g.Mh(this);g.r(this,this.EM);this.N.addEventListener("videodatachange",this.zC.bind(this))},z4q=function(G,m){m=m.data;
m.autoOpenMs&&G.addCueRange(m.autoOpenMs,0x8000000000000,"",function(){mf(G,"YOUTUBE_DRAWER_AUTO_OPEN")});
m.autoCloseMs&&G.addCueRange(m.autoCloseMs,0x8000000000000,"",function(){wC(G)});
var w=m.headerText;g.zj(G.x5,w);G.j&&(G.N.J("player_tooltip_data_title_killswitch")?G.j.setAttribute("title",w):G.j.setAttribute("data-tooltip-title",w));m.eventId&&(G.eventId=m.eventId);G.rd=g.iD(m.trackingParams);G.C=g.iD(m.closeTrackingParams);G.Yj=g.iD(m.iconTrackingParams)},Vhb=function(G,m){var w=m.cardId?m.cardId:"cr:"+G.L,W=G.N.S().experiments.vk("enable_error_corrections_infocard_web_client");
if(!m.content&&m.teaser.simpleCardTeaserRenderer&&W){var U=m.teaser.simpleCardTeaserRenderer,c=m.icon?m.icon.infoCardIconRenderer:null;if(U.channelAvatar&&U.channelAvatar.thumbnails&&U.channelAvatar.thumbnails.length>0)var Q=Wi(U.channelAvatar.thumbnails,22,22).url;m={id:w,timestamp:G.L,type:"simple",teaserText:g.qm(U.message),teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),autoOpen:!!m.autoOpen,sessionData:{},sponsored:!1,ET:{},gf:null,lP:U.trackingParams?
g.iD(U.trackingParams):null,Yj:c&&c.trackingParams?g.iD(c.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,uT:null,title:"",customMessage:"",url:null,onClickCommand:U.onTapCommand||null,TL:Q};Uy(G,m)}else{var D;if((D=m.content)==null?0:D.simpleCardContentRenderer){if(!m.cueRanges.length)return;Q=(U=m.content)==null?void 0:U.simpleCardContentRenderer;U=m.teaser.simpleCardTeaserRenderer;c=m.icon?m.icon.infoCardIconRenderer:null;m={id:w,timestamp:G.L,type:"simple",teaserText:g.qm(U.message),
teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),autoOpen:!!m.autoOpen,sessionData:sy(G,w,m,Q),sponsored:!1,ET:GP(Q,U,Q.command),gf:Q.trackingParams?g.iD(Q.trackingParams):null,lP:U.trackingParams?g.iD(U.trackingParams):null,Yj:c&&c.trackingParams?g.iD(c.trackingParams):null,imageUrl:Wi(Q.image.thumbnails,290,290).url,displayDomain:Q.displayDomain?g.qm(Q.displayDomain):null,showLinkIcon:!!Q.showLinkIcon,uT:null,title:Q.title?g.qm(Q.title):"",
customMessage:Q.callToAction?g.qm(Q.callToAction):"",url:g.n(Q.command,g.S3).url?Hq({pause_on_navigation:!G.context.videoData.isLivePlayback,target:"new",value:g.n(Q.command,g.S3).url}):null,onClickCommand:null};Uy(G,m)}else{var O;if((O=m.content)==null?0:O.collaboratorInfoCardContentRenderer){if(!m.cueRanges.length)return;Q=(c=m.content)==null?void 0:c.collaboratorInfoCardContentRenderer;U=m.teaser.simpleCardTeaserRenderer;c=m.icon?m.icon.infoCardIconRenderer:null;m={id:w,timestamp:G.L,type:"collaborator",
teaserText:g.qm(U.message),teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),autoOpen:!!m.autoOpen,sessionData:sy(G,w,m,Q),sponsored:!1,ET:GP(Q,U,Q.endpoint),gf:Q.trackingParams?g.iD(Q.trackingParams):null,lP:U.trackingParams?g.iD(U.trackingParams):null,Yj:c&&c.trackingParams?g.iD(c.trackingParams):null,channelId:g.n(Q.endpoint,g.AO).browseId,customMessage:Q.customText?g.qm(Q.customText):null,profileImageUrl:Wi(Q.channelAvatar.thumbnails,290,
290).url,title:Q.channelName?g.qm(Q.channelName):"",metaInfo:[Q.subscriberCountText?g.qm(Q.subscriberCountText):""],url:Hq({pause_on_navigation:!G.context.videoData.isLivePlayback,target:"new",value:g.n(Q.endpoint,g.AO).canonicalBaseUrl?g.n(Q.endpoint,g.AO).canonicalBaseUrl:"/channel/"+g.n(Q.endpoint,g.AO).browseId}),onClickCommand:null};Uy(G,m)}else{var q;if((q=m.content)==null?0:q.playlistInfoCardContentRenderer){if(!m.cueRanges.length)return;var T;Q=(T=m.content)==null?void 0:T.playlistInfoCardContentRenderer;
U=m.teaser.simpleCardTeaserRenderer;c=m.icon?m.icon.infoCardIconRenderer:null;m={id:w,timestamp:G.L,type:"playlist",teaserText:g.qm(U.message),teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),autoOpen:!!m.autoOpen,sessionData:sy(G,w,m,Q),sponsored:!1,ET:GP(Q,U,Q.action),gf:Q.trackingParams?g.iD(Q.trackingParams):null,lP:U.trackingParams?g.iD(U.trackingParams):null,Yj:c&&c.trackingParams?g.iD(c.trackingParams):null,zL:Wi(Q.playlistThumbnail.thumbnails,
258,290).url,customMessage:Q.customMessage?g.qm(Q.customMessage):null,playlistVideoCount:g.qm(Q.playlistVideoCount),title:Q.playlistTitle?g.qm(Q.playlistTitle):"",metaInfo:[Q.channelName?g.qm(Q.channelName):"",Q.videoCountText?g.qm(Q.videoCountText):""],url:Hq({pause_on_navigation:!G.context.videoData.isLivePlayback,target:"new",value:N3q(Q.action)}),onClickCommand:null};Uy(G,m)}else{var a;if((a=m.content)==null?0:a.videoInfoCardContentRenderer){if(!m.cueRanges.length)return;var Z;Q=(Z=m.content)==
null?void 0:Z.videoInfoCardContentRenderer;U=m.teaser.simpleCardTeaserRenderer;c=m.icon?m.icon.infoCardIconRenderer:null;m={id:w,timestamp:G.L,type:"video",teaserText:g.qm(U.message),teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),autoOpen:!!m.autoOpen,sessionData:sy(G,w,m,Q),sponsored:!1,ET:GP(Q,U,Q.action),gf:Q.trackingParams?g.iD(Q.trackingParams):null,lP:U.trackingParams?g.iD(U.trackingParams):null,Yj:c&&c.trackingParams?g.iD(c.trackingParams):
null,zL:Wi(Q.videoThumbnail.thumbnails,258,290).url,videoDuration:Q.lengthString?g.qm(Q.lengthString):null,customMessage:Q.customMessage?g.qm(Q.customMessage):null,title:Q.videoTitle?g.qm(Q.videoTitle):"",metaInfo:[Q.channelName?g.qm(Q.channelName):"",Q.viewCountText?g.qm(Q.viewCountText):""],isLiveNow:!!Q.badge,url:Hq({pause_on_navigation:!G.context.videoData.isLivePlayback,target:"new",value:N3q(Q.action)}),onClickCommand:null};Uy(G,m)}}}}}G.L++},Wi=function(G,m,w){for(var W=-1,U=-1,c=0;c<G.length;c++){if(G[c].height===
m||G[c].width===w)return G[c];
((G[c].height||0)<m||(G[c].width||0)<w)&&(W<0||(G[W].height||0)<(G[c].height||0)||(G[W].width||0)<(G[c].width||0))?W=c:((G[c].height||0)>=m||(G[c].width||0)>=w)&&(U<0||(G[U].height||0)>(G[c].height||0)||(G[U].width||0)>(G[c].width||0))&&(U=c)}return G[U>=0?U:W]},sy=function(G,m,w,W){return{feature:w.feature?w.feature:"cards",
src_vid:G.context.videoData.videoId,annotation_id:m,ei:G.context.videoData.eventId||"",itct:W.trackingParams||""}},Llf=function(G,m){if(m=Mhq(G,m))m===G.V&&(G.V=null),G.N.removeCueRange(m.uI.id),g.Nb(m.Qs),g.Mn(G.cards,m),G.rk(),ci(G)},mf=function(G,m,w){if(!G.X){G.yj.show();
G.Z6=new g.ey(function(){g.Gb(G.context.N.getRootNode(),g.bm.IV_DRAWER_OPEN)},0);
G.Z6.start();G.EM.T(G.Y,"mousewheel",function(Q){G.J4.start();Q.preventDefault();Q=Q||window.event;var D=0;Q.type=="MozMousePixelScroll"?D=0==(Q.axis==Q.HORIZONTAL_AXIS)?Q.detail:0:window.opera?D=Q.detail:D=Q.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?Q.wheelDeltaY/-30:Q.wheelDeltaY/-1.2:Q.wheelDelta/-1.6:Q.wheelDeltaY/-3;if(Q=D)G.Y.scrollTop+=Q});
G.X=!0;var W=g.IC();W&&G.rd&&G.C&&g.An(W,[G.rd,G.C]);m={TRIGGER_TYPE:m};for(var U=g.V(G.cards),c=U.next();!c.done;c=U.next())c=c.value,c.Wx||(c.Wx=!0,b0R(G.context.logger,c.uI.ET.Gp,m)),W&&g.An(W,[c.uI.gf]);RA(G.N);w&&(G.K=new g.ey(function(){G.pM=G.j;G.hY.focus()},330),G.K.start())}},wC=function(G){G.X&&(G.yj.hide(),g.L6(G.EM),g.wV(G.context.N.getRootNode(),g.bm.IV_DRAWER_OPEN),G.X=!1,RA(G.N),G.K&&G.K.stop(),G.K=new g.ey(function(){G.pM&&(G.pM.focus(),G.pM=null)},330),G.K.start())},thH=function(G){g.mB(G.n5(),
[g.bm.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.ye(G.N,G.D,5);G.Q2();G.j=g.vC("ytp-cards-button",G.N.getRootNode());G.hY=g.vC("iv-drawer-close-button",G.D);G.isInitialized=!0},g1e=function(G){G.YB.push(g.yJ("iv-teaser-shown",G.qo,G));
G.YB.push(g.yJ("iv-teaser-hidden",G.Xk2,G));G.YB.push(g.yJ("iv-teaser-clicked",G.I_,G));G.aM=!0},dib=function(G,m){var w;
return m.onClickCommand&&((w=g.n(m.onClickCommand,g.Wm4))==null?void 0:w.targetId)==="engagement-panel-error-corrections"?(G.D6=m,!0):!1},fId=function(G,m){G.D6=m;
var w=G.N.getVideoData();if(!w)return!1;w=g.mU(w);if(w==null?0:w.markersMap)for(var W,U=0;((W=w)==null?void 0:W.markersMap.length)>U;U++){var c=void 0,Q=(c=w)==null?void 0:c.markersMap[U];if(Q.key==="ERROR_CORRECTION_MARKERS"&&(c=void 0,(Q=(c=Q.value)==null?void 0:c.markers)&&Q.length>0))return W=void 0,m.startMs=((W=g.n(Q[0],g.Lfq))==null?void 0:W.timeRangeStartMillis)||0,G.D6=null,!0}return!1},Uy=function(G,m){if(!dib(G,m)||fId(G,m)){var w=R4n(G,m);
if(w){var W={uI:m,Qs:w.element,Wx:!1};if(m.onClickCommand)G.N.J("web_infocards_teaser_show_logging_fix")&&(G.aM||g1e(G),Llf(G,m.id),w=G.findLastIndex(W),g.Eq(G.cards,w,0,W));else{G.isInitialized||thH(G);Llf(G,m.id);var U=G.findLastIndex(W);g.Eq(G.cards,U,0,W);w.KM(G.Y,U);G.rk()}m.autoOpen?G.addCueRange(m.startMs,0x8000000000000,m.id,function(){G.X||(G.V=W,ci(G),pxn(G,W),mf(G,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(w=G.context.N.getCurrentTime()*1E3,w<5E3&&w>m.startMs&&jbf(G,W),G.addCueRange(m.startMs,
m.startMs+1,m.id,function(){jbf(G,W)}),ci(G))}}},R4n=function(G,m){switch(m.type){case "simple":G=G.M9;
var w=m.displayDomain?{B:"div",Z:"iv-card-image-text",l6:m.displayDomain}:void 0;var W=Z0q(m);w={B:"div",fM:["iv-card"],G:[{B:"a",Z:"iv-click-target",W:{href:m.url?ut(m.url)||"":""},G:[Bq(m.imageUrl,w),{B:"div",Z:"iv-card-content",G:[YP("h2",void 0,m.title),W]}]}]};w=new g.x(w);AH(G,g.cC("iv-click-target",w.element),m,m.url);m=w;break;case "collaborator":G=G.M9;w={B:"div",fM:["iv-card","iv-card-channel"],G:[{B:"a",fM:["iv-click-target"],W:{href:ut(m.url)||"","data-ytid":m.channelId},G:[Bq(m.profileImageUrl),
{B:"div",Z:"iv-card-content",G:[$iR(m),{B:"h2",Z:"iv-card-primary-link",l6:m.title},aIg(m)]}]}]};w=new g.x(w);AH(G,g.cC("iv-click-target",w.element),m,m.url);m=w;break;case "playlist":G=G.M9;w={B:"div",fM:["iv-card","iv-card-playlist"],G:[{B:"a",Z:"iv-click-target",W:{href:ut(m.url)||""},G:[Bq(m.zL,{B:"div",Z:"iv-card-image-overlay",G:[{B:"span",Z:"iv-card-playlist-video-count",l6:m.playlistVideoCount}]}),{B:"div",Z:"iv-card-content",G:[$iR(m),YP("h2","iv-card-primary-link",m.title),aIg(m)]}]}]};
w=new g.x(w);AH(G,g.cC("iv-click-target",w.element),m,m.url);m=w;break;case "productListing":G=G.M9;var U=m.offers.length!=0;w=["iv-card"];W="";var c=Z0q(m);U&&(w.push("iv-card-product-listing"),W="iv-card-primary-link",c=m.offers[0],U=[],c.price&&U.push({B:"div",Z:"iv-card-offer-price",l6:c.price}),c.merchant&&U.push({B:"div",Z:"iv-card-offer-merchant",l6:c.merchant}),c={B:"div",G:U});U=m.url?ut(m.url)||"":"";w={B:"div",fM:w,W:{tabindex:"0"},G:[{B:"a",fM:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
m.imageUrl+");",href:U,"aria-hidden":"true",tabindex:"-1"}},{B:"div",Z:"iv-card-content",G:[m.sponsored?{B:"div",Z:"iv-card-sponsored",G:["Lien commercial",{B:"div",Z:"iv-ad-info-container",G:[{B:"div",Z:"iv-ad-info",l6:"{{adInfo}}"},{B:"div",Z:"iv-ad-info-icon-container",G:[{B:"div",Z:"iv-ad-info-icon"},{B:"div",Z:"iv-ad-info-callout"}]}]}]}:"",{B:"a",Z:"iv-click-target",W:{href:U},G:[YP("h2",W,m.title),c]}]}]};w=new g.x(w);W=g.aI("span");g.zj(W,"Vous voyez ce produit, car nous pensons qu'il est pertinent pour la vid\u00e9o. Il se peut que le marchand r\u00e9mun\u00e8re Google.");
w.kz(W,"adInfo");AH(G,g.cC("iv-click-target",w.element),m,m.url);m=w;break;case "video":G=G.M9;W=m.videoDuration?{B:"span",Z:"iv-card-video-duration",l6:m.videoDuration}:void 0;c=m.isLiveNow?{B:"span",fM:["yt-badge","yt-badge-live"],l6:"EN DIRECT MAINTENANT"}:null;U={B:"div",fM:["iv-card","iv-card-video"],G:[{B:"a",Z:"iv-click-target",W:{href:((w=m.url)==null?void 0:ut(w))||""},G:[Bq(m.zL,W),{B:"div",Z:"iv-card-content",G:[$iR(m),YP("h2","iv-card-primary-link",m.title),aIg(m),c]}]}]};w=new g.x(U);
AH(G,g.cC("iv-click-target",w.element),m,m.url);m=w;break;default:return null}return m},SzH=function(G){if(G.V)return G.V.uI.type==="productListing";
if(G.N.J("enable_wn_infocards")){var m;return!((m=G.cards)==null||!m.length)&&g.Ki(G.cards,function(w){return w.uI.type==="productListing"})}return g.Ki(G.cards,function(w){return w.uI.type==="productListing"})},ci=function(G){g.UN(G.N.getRootNode(),"ytp-cards-shopping-active",SzH(G))},jbf=function(G,m){if(!g.yR(G.N.getRootNode(),"ytp-cards-teaser-shown")){if(G.V!==m){var w=g.IC(),W=G.V?G.V.uI.Yj:G.Yj;
w&&W&&g.X8(w,[W]);G.V=m;ci(G)}(w=G.isInitialized&&G.n5().style.display=="none")||(w=G.context.N.getPlayerState(),W=w===0&&G.context.N.getCurrentTime()===0,w=!(w===1||w===3||W));if(!w&&m.uI.teaserDurationMs){var U;w={teaserText:m.uI.teaserText,durationMs:m.uI.teaserDurationMs,onClickCommand:m.uI.onClickCommand,TL:(U=m.uI.TL)!=null?U:null};G.N.Wq(!0,w)}G.u6.isActive()||((!G.X||!G.J4.isActive()&&G.Pk)&&pxn(G,m),G.u6.start(910+m.uI.teaserDurationMs))}},pxn=function(G,m){G.U.Y5?(m=new oA([0,
G.Y.scrollTop],[0,m.Qs.offsetTop],600,ET9),G.context.X.listen(m,"animate",function(w){G.Y.scrollTop=w.y}),G.context.X.listen(m,"finish",function(w){G.Y.scrollTop=w.y}),m.play()):(G.U.tY(!0),G.Y.scrollTop=m.Qs.offsetTop,G.U.tY(!1))},QT=function(G){return G.V&&G.V.uI?G.V.uI:G.cards[0]&&G.cards[0].uI?G.cards[0].uI:null},Mhq=function(G,m){return g.Nn(G.cards,function(w){return w.uI.id===m})},vi=function(G,m,w){Xc.call(this,G,m);
this.annotation=w;this.isActive=!1},Pz4=function(G){var m=G.annotation.data;
"start_ms"in m&&"end_ms"in m&&G.addCueRange(Number(m.start_ms),Number(m.end_ms),G.annotation.id,function(){G.show()},function(){G.hide()})},D9=function(G,m,w){vi.call(this,G,m,w);
this.Y=null;this.L=!1;this.X=null;this.D=!1;this.V=this.K=this.j=null},o19=function(G,m){var w=w===void 0?0:w;
var W=RNm(m).width;g.BC(m,W);w=new l8d(m,[W,m.offsetTop],[W-W-w,m.offsetTop],200,Cuq);g.r(G,w);G.context.X.listen(w,"begin",function(){g.wp(m,!0)});
w.play()},Czg=function(G,m){if(m.channel_name){var w=G.createElement({B:"div",
fM:["iv-branding-context-name"],l6:m.channel_name}),W=G.createElement({B:"div",fM:["iv-branding-context-subscribe"]}),U=m.standalone_subscribe_button_data;U&&(G.V=new g.UW(U.subscribeText,U.subscribeCount,U.unsubscribeText,U.unsubscribeCount,!!U.enabled,!!U.classic,m.channel_id,!!U.subscribed,U.feature,m.session_data.itct,G.context.N,!1),G.V.KM(W));var c=G.createElement({B:"div",fM:["iv-branding-context-subscribe-caret"]}),Q=G.createElement({B:"div",fM:["branding-context-container-inner"]});Q.appendChild(c);
Q.appendChild(w);Q.appendChild(W);g.wp(Q,!1);var D=G.createElement({B:"div",fM:["branding-context-container-outer"]});D.appendChild(Q);g.eT(D,"right",m.image_width+"px");g.kS(G.n5(),D);G.X=new g.ey(function(){h49(G,Q,D)},500);
g.r(G,G.X);G.context.V.listen(G.n5(),"mouseover",function(){lIm(G,Q,D,c,m.image_height)});
G.context.V.listen(G.n5(),"mouseout",function(){G.X.start()})}},lIm=function(G,m,w,W,U){G.X.stop();
if(!G.D){var c=g.mF(m);G.V||(m.style.width=g.YS(c.width,!0),w.style.width=g.YS(c.width,!0));g.eT(W,"top",c.height-Math.max(Math.min(c.height,U)/2+10,20)+"px");g.eT(W,"right","1px");G.D=!0;g.wp(m,!0);G.j=new g.ey(function(){g.Gb(this.n5(),"iv-branding-active")},0,G);
G.j.start()}},h49=function(G,m,w){g.wV(G.n5(),"iv-branding-active");
G.K=new g.ey(function(){g.wp(m,!1);G.V||(w.style.width=g.YS(0,!0))},250);
G.K.start();G.D=!1},E19=function(G,m,w,W,U,c,Q){this.V=G;
this.X=m;this.h4=w;this.videoData=W;this.logger=U;this.N=c;this.Y=Q},J6c=function(G,m,w){vi.call(this,G,m,w);
var W=this;this.C=this.isCollapsed=this.U=!1;this.K=5E3;this.Y=this.X=this.V=this.D=null;this.L=this.createElement({B:"div",fM:["iv-promo-contents"]});this.j=new g.ey(function(){W.V.setAttribute("aria-hidden","true");g.wp(W.X,!1);g.wp(W.Y,!0)},700,this);
g.r(this,this.j)},FlR=function(G){var m=G.annotation.data;
if(G.annotation.style==="cta")var w=6;else if(G.annotation.style==="video"||G.annotation.style==="playlist")w=7;G.K=m.collapsedelay_ms||G.K;var W=["iv-promo","iv-promo-inactive"];G.n5().setAttribute("aria-hidden","true");G.n5().setAttribute("aria-label","Promotion");G.n5().tabIndex=0;var U=G.annotation.Po(),c=m.image_url;if(c){var Q=G.createElement({B:"div",fM:["iv-promo-img","iv-click-target"]});c=G.createElement({B:"img",W:{src:c,"aria-hidden":"true"}});Q.appendChild(c);m.video_duration&&!m.is_live?
(c=G.createElement({B:"span",Z:"iv-promo-video-duration",l6:m.video_duration}),Q.appendChild(c)):m.playlist_length&&(c=G.createElement({B:"span",Z:"iv-promo-playlist-length",l6:m.playlist_length.toString()}),Q.appendChild(c));U&&yw(G,Q,U,G.annotation.id,m.session_data,void 0,w)}U?(c=G.createElement({B:"a",Z:"iv-promo-txt"}),g.Oa(c,ut(U)),G.V=c):G.V=G.createElement({B:"div",Z:"iv-promo-txt"});switch(G.annotation.style){case "cta":case "website":var D=G.createElement({B:"p",G:[{B:"strong",l6:m.text_line_1}]});
var O=G.createElement({B:"p",G:[{B:"span",Z:"iv-promo-link",l6:m.text_line_2}]});if(c=m.text_line_3){W.push("iv-promo-website-card-cta-redesign");var q=G.createElement({B:"button",fM:["iv-promo-round-expand-icon","ytp-button"]});c=G.createElement({B:"button",fM:["iv-button","iv-promo-button"],G:[{B:"span",Z:"iv-button-content",l6:c}]});var T=G.createElement({B:"div",Z:"iv-promo-button-container"});T.appendChild(c);U&&yw(G,G.n5(),U,G.annotation.id,m.session_data,void 0,w)}g.Gb(G.V,"iv-click-target");
U&&yw(G,G.V,U,G.annotation.id,m.session_data,void 0,w);break;case "playlist":case "video":D=G.createElement({B:"p",G:[{B:"span",l6:m.text_line_1}]}),O=G.createElement({B:"p",G:[{B:"strong",l6:m.text_line_2}]}),m.is_live&&(D=O,O=G.createElement({B:"span",fM:["yt-badge","iv-promo-badge-live"],l6:"EN DIRECT MAINTENANT"})),g.Gb(G.V,"iv-click-target"),U&&yw(G,G.V,U,G.annotation.id,m.session_data,void 0,w),W.push("iv-promo-video")}D&&G.V.appendChild(D);O&&G.V.appendChild(O);G.L.appendChild(G.V);T&&G.L.appendChild(T);
w=G.createElement({B:"div",Z:"iv-promo-actions"});G.Y=G.createElement({B:"button",fM:["iv-promo-expand","ytp-button"]});G.Y.title="Agrandir";G.context.V.listen(G.Y,"click",function(a){r6q(G,5E3,a)});
w.appendChild(G.Y);g.wp(G.Y,!1);G.context.V.listen(G.n5(),"mouseover",G.OH,G);G.context.V.listen(G.n5(),"mouseout",G.gI,G);G.context.V.listen(G.n5(),"touchend",function(a){r6q(G,5E3,a)});
G.X=G.createElement({B:"button",fM:["iv-promo-close","ytp-button"]});G.X.title="Fermer";G.context.V.listen(G.X,"click",G.annotation.style==="cta"&&m.text_line_3?G.yr:G.CH,G);w.appendChild(G.X);g.mB(G.n5(),W);Q&&(g.kS(G.n5(),Q),q&&Q.appendChild(q));g.kS(G.n5(),G.L);g.kS(G.n5(),w)},r6q=function(G,m,w){w.stopPropagation();
e4q(G);n1g(G,m);G.V.focus()},xiH=function(G){G.isCollapsed||G.C||G.D||(g.Gb(G.n5(),"iv-promo-collapsed"),G.isCollapsed=!0,G.j.start())},e4q=function(G){G.j.stop();
G.isCollapsed&&(g.Wj(G.n5(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),G.isCollapsed=!1,G.V&&G.V.removeAttribute("aria-hidden"),g.wp(G.Y,!1),g.wp(G.X,!0))},n1g=function(G,m){G.D||(G.D=g.P5(function(){uum(this);
xiH(this)},m,G))},uum=function(G){G.D&&(g.X6.clearTimeout(G.D),G.D=null)},H0z=function(G){this.N=G},b0R=function(G,m,w){m&&(w?Oy(G,m.map(function(W){return g.b3(W,w)})):Oy(G,m))},Oy=function(G,m,w,W){var U=1,c=void 0,Q=-1;
if(w){var D=!1;c=function(){U--;U||D||(clearTimeout(Q),D=!0,w())};
Q=setTimeout(function(){D=!0;w()},1E3)}m=g.V(m||[]);
for(var O=m.next();!O.done;O=m.next())O=O.value,U++,g.Pn(O,c);W&&(U++,W!==0&&G.N.sendVideoStatsEngageEvent(W,c))},Yzn=function(G){g.bK.call(this,G);
var m=this;this.YB=this.C=!1;this.loadNumber=0;this.K={};this.logger=new H0z(this.player);this.D=new g.Mh(this);this.j=this.L=null;this.events=new g.Mh(this);this.Ya=this.U=this.V=null;this.D6=[];g.r(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){m.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){m.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){m.publish("onShowControls")});
this.D.T(this.player,"resize",function(W){m.publish("resize",W)});
this.D.T(this.player,"presentingplayerstatechange",function(W){m.publish("presentingplayerstatechange",W)});
this.subscribe("presentingplayerstatechange",this.ZK,this);this.subscribe("resize",this.E9,this);this.player.S().Pk.subscribe("vast_info_card_add",this.XM,this);g.r(this,this.events);this.M9=this.createElement({B:"div",Z:"video-custom-annotations"});this.Y=new g.x({B:"div",fM:["ytp-player-content","ytp-iv-player-content"]});g.r(this,this.Y);g.ye(this.player,this.Y.element,4);this.Y.hide();this.X=new g.x({B:"div",fM:["ytp-iv-video-content"]});g.r(this,this.X);G=this.createElement({B:"div",Z:"video-annotations"});
G.appendChild(this.M9);this.X.element.appendChild(G);this.Dn()&&this.load();var w=this.createElement({B:"style"});(g.sx("HEAD")[0]||document.body).appendChild(w);this.addOnDisposeCallback(function(){g.Nb(w)});
if(G=w.sheet)G.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),G.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),G.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),G.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),G.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),G.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),G.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),G.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),G.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),G.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},B3R=function(G){G=G.createElement({B:"div",
fM:["annotation","annotation-type-custom"]});g.wp(G,!1);return G},A69=function(G,m){m=!m.isCued()&&!g.H(m,1024);
G.Y.tY(m);G.X.tY(m)},Xxd=function(G,m,w){G.C=!0;
G.j=g.N4(m,w)},y6g=function(G,m){for(var w={},W=g.V(m.attributes),U=W.next();!U.done;U=W.next())U=U.value,w[U.name]=U.nodeValue;
for(W=0;W<m.childNodes.length;W++)if(U=m.childNodes[W],g.sq(U)&&U.nodeType==1){if(w[U.tagName])var c=w[U.tagName];else if(U.tagName==="data"){U.childNodes.length>0&&(c=U.childNodes[0].nodeValue,w[U.tagName]=typeof c==="string"?c.trim():c);continue}else c=[],w[U.tagName]=c;U&&U.tagName==="TEXT"?U.childNodes.length===1&&U.childNodes[0].nodeType===3?c.push(U.childNodes[0].nodeValue):c.push(""):U&&c.push(y6g(G,U))}return w},Wug=function(G){var m=G.player.getVideoData();
if(m.EM){var w=G.player.S().Pk.get(m.videoId);if(w){var W={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(U,c,Q){U=G.loadNumber;c=m.videoId;G.loaded&&G.loadNumber===U&&G.player.getVideoData().videoId===c&&(Q=g.vA(Q)&&Q.responseXML?Q.responseXML:null)&&Gnq(G,Q)}};
g.YN()&&(W.onFinish=mtR(G,W.onFinish));W.postParams={ic_only:"1"};wzc(W,w);G.C=!0;g.N4(m.EM,W)}}},wzc=function(G,m){G.method="POST";
G.postParams=G.postParams||{};m.Rd&&(G.postParams.ic_coll=m.Rd);m.cU&&(G.postParams.ic_xml=m.cU);m.Yv&&(G.postParams.ic_track=m.Yv)},UtH=function(G){var m=new g.x({B:"div"});
g.wp(m.element,!1);var w=new IIm(G.player,m.element,qI(G));g.r(w,m);m.KM(G.Y.element);w.KC();return w},cjR=function(G,m){var w,W;
if(m=(w=m.getWatchNextResponse())==null?void 0:(W=w.cards)==null?void 0:W.cardCollectionRenderer)G.YB=!0,s4d(G,m),m.headerText&&G.Ya&&(w=g.qm(m.headerText),G.player.J("player_tooltip_data_title_killswitch")?G.Ya.setAttribute("title",w):G.Ya.setAttribute("data-tooltip-title",w))},qI=function(G){if(!G.U){var m=new JbR(G);
g.r(G,m);var w=new g.$E(G);g.r(G,w);G.U=new E19(m,w,G.player.S(),G.player.getVideoData(),G.logger,G.player,G.eH)}return G.U},Gnq=function(G,m){var w=!1,W=m.getElementsByTagName("annotations");
if(W&&!(W.length<1)&&(W=W[0].getAttribute("itct"))){var U=g.IC();if(U){var c=g.N7();c&&g.x4(g.Jn)(void 0,U,c,[g.iD(W)])}}m=m.getElementsByTagName("annotation");for(W=0;W<m.length;W++){c=y6g(G,m[W]);U=null;try{if(c){var Q=c.id,D=/.+/;var O=typeof Q==="string"&&D!=null&&Q!=null&&Q.match(D)?Q:"";var q=xP(c.type,Q4c),T=xP(c.style,vaf),a=Wld(c.data),Z=a.length!==0?JSON.parse(a):{};var k=c.action;c=DiR;if(k==null)var K=null;else if(g.Uq(k)){D=[];for(var M=g.V(k),t=M.next();!t.done;t=M.next()){var R=c(t.value);
R&&D.push(R)}K=D}else{var f=c(k);K=f?[f]:[]}U=O&&q?new O0z(O,q,T,K,Z):null}else U=null}catch(vW){}if(U)if(U.type==="branding"||U.type==="promotion"){c=G;D=U;var P=B3R(c),E=null;switch(D.type){case "branding":if(c.player.S().SX)break;c.player.J("web_player_overlay_positioned_layout")?(P.setAttribute("data-overlay-order","11"),c.player.Uc(P,4,!0)):c.Y.element.appendChild(P);E=new D9(P,qI(c),D);break;case "promotion":g.ye(c.player,P,4),E=new J6c(P,qI(c),D)}E&&E.KC();if(c=E)g.r(G,c),G.K[U.id]=c}else if(U.type===
"card"||U.type==="drawer"){G.V||(G.V=UtH(G),g.r(G,G.V));if(U.type==="card"){P=G.V;var e=(w=U)&&w.data&&w.data.card_type;U=w.data;if(e)switch(c=U.tracking||{},c={Gp:c.impression,click:c.click,close:c.close,OI:c.teaser_impression,Dl:c.teaser_click},D=U.tracking_params||{},E=null,e){case "collaborator":w={id:w.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,startMs:U.start_ms,autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||
!1,ET:c,gf:D.card?g.iD(D.card):null,lP:D.teaser?g.iD(D.teaser):null,Yj:D.icon?g.iD(D.icon):null,channelId:U.channel_id,customMessage:U.custom_message?U.custom_message:null,profileImageUrl:U.image_url,title:U.title,metaInfo:U.meta_info,url:Hq({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url}),onClickCommand:null};Uy(P,w);break;case "playlist":w={id:w.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,startMs:U.start_ms,
autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||!1,ET:c,gf:D.card?g.iD(D.card):null,lP:D.teaser?g.iD(D.teaser):null,Yj:D.icon?g.iD(D.icon):null,zL:U.image_url,playlistVideoCount:U.playlist_video_count,customMessage:U.custom_message?U.custom_message:null,title:U.title,metaInfo:U.meta_info,url:Hq({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url}),onClickCommand:null};Uy(P,w);break;case "productListing":U.signin_url&&(E=Hq({target:"current",
value:U.signin_url}));e=[];for(var A=U.offers||[],Y=0;Y<A.length;Y++)e.push(new kXg(g.pn(A[Y].merchant),g.pn(A[Y].price)));w={id:w.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,startMs:U.start_ms,autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||!1,ET:c,gf:D.card?g.iD(D.card):null,lP:D.teaser?g.iD(D.teaser):null,Yj:D.icon?g.iD(D.icon):null,imageUrl:U.image_url,displayDomain:U.display_domain?U.display_domain:
null,showLinkIcon:!!U.show_link_icon,uT:U.button_icon_url?U.button_icon_url:null,title:U.title,customMessage:U.custom_message?U.custom_message:null,url:Hq({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url}),s8d:E,Nqy:U.signin_title?U.signin_title:void 0,nXy:U.signin_message?U.signin_message:void 0,offers:e,onClickCommand:null};Uy(P,w);break;case "simple":w={id:w.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,
startMs:U.start_ms,autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||!1,ET:c,gf:D.card?g.iD(D.card):null,lP:D.teaser?g.iD(D.teaser):null,Yj:D.icon?g.iD(D.icon):null,imageUrl:U.image_url,displayDomain:U.display_domain?U.display_domain:null,showLinkIcon:!!U.show_link_icon,uT:U.button_icon_url?U.button_icon_url:null,title:U.title,customMessage:U.custom_message?U.custom_message:null,url:Hq({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url}),onClickCommand:null};
Uy(P,w);break;case "video":w={id:w.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,startMs:U.start_ms,autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||!1,ET:c,gf:D.card?g.iD(D.card):null,lP:D.teaser?g.iD(D.teaser):null,Yj:D.icon?g.iD(D.icon):null,zL:U.image_url,videoDuration:U.video_duration||null,customMessage:U.custom_message?U.custom_message:null,title:U.title,metaInfo:U.meta_info,isLiveNow:!!U.is_live_now,
url:Hq({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url}),onClickCommand:null},Uy(P,w)}}else z4q(G.V,U);w=!0}}w&&(RA(G.player),G.E9())},s4d=function(G,m){var w=!1;
G.V||(G.V=UtH(G),g.r(G,G.V));for(var W=g.V(m.cards||[]),U=W.next();!U.done;U=W.next())U=U.value,U.cardRenderer&&(Vhb(G.V,U.cardRenderer),w=!0);if(w){var c;(c=G.player.getVideoData())!=null&&g.UZ(c)||(w=G.V,W=m.headerText?g.qm(m.headerText):"",g.zj(w.x5,W),w.j&&(w.N.J("player_tooltip_data_title_killswitch")?w.j.setAttribute("title",W):w.j.setAttribute("data-tooltip-title",W)),w.context.videoData.eventId&&(w.eventId=w.context.videoData.eventId),w.rd=m.trackingParams?g.iD(m.trackingParams):null,w.C=
m.closeButton.infoCardIconRenderer.trackingParams?g.iD(m.closeButton.infoCardIconRenderer.trackingParams):null,w.Yj=m.icon.infoCardIconRenderer.trackingParams?g.iD(m.icon.infoCardIconRenderer.trackingParams):null,G.E9());RA(G.player)}},Dtq=function(G,m,w,W,U){if(!G.player.S().SX){var c=[];
m.navigationEndpoint&&g.n(m.navigationEndpoint,g.AO)&&g.n(m.navigationEndpoint,g.AO).browseId&&c.push(new c6g("openUrl","click",new Uiq("/channel/"+g.n(m.navigationEndpoint,g.AO).browseId,"new",!0,!0)));var Q=m.watermark.thumbnails[0];W={channel_name:m.channelName,end_ms:m.endTimeMs,image_height:Q.height,image_type:1,image_url:Q.url,image_width:Q.width,is_mobile:!1,session_data:{annotation_id:w,ei:U,feature:"iv",itct:m.trackingParams,src_vid:W},start_ms:m.startTimeMs};if(m.subscribeButton&&g.n(m.subscribeButton,
g.XZ)){W.channel_id=g.n(m.subscribeButton,g.XZ).channelId;var D;m=g.n(m.subscribeButton,g.XZ);Q=U=null;m.subscribed?(m.subscriberCountWithUnsubscribeText&&(U=g.qm(m.subscriberCountWithUnsubscribeText)),m.subscriberCountText&&(Q=g.qm(m.subscriberCountText))):(m.subscriberCountText&&(U=g.qm(m.subscriberCountText)),m.subscriberCountWithSubscribeText&&(Q=g.qm(m.subscriberCountWithSubscribeText)));var O,q=((O=g.n((D=m.signInEndpoint)==null?void 0:D.commandMetadata,g.VD))==null?void 0:O.url)||"";D={subscribeText:g.qm(m.unsubscribedButtonText),
subscribeCount:U||"",unsubscribeText:g.qm(m.subscribedButtonText),unsubscribeCount:Q||"",enabled:m.enabled||!1,classic:!1,subscribed:m.subscribed||!1,feature:"iv",signInUrl:q};W.standalone_subscribe_button_data=D}c=new O0z(w,"branding","branding",c,W);D=B3R(G);G.player.J("web_player_overlay_positioned_layout")?(D.setAttribute("data-overlay-order","11"),G.player.Uc(D,4,!0)):G.Y.element.appendChild(D);c=new D9(D,qI(G),c);c.KC();g.r(c,c);G.K[w]=c}},mtR=function(G,m){return function(){var w=g.Eo.apply(0,
arguments);
G.i6()||G.D6.push(g.Pv.cI(function(){m.apply(null,g.Z$(w))}))}},OM9=function(G){return G==="annotation-editor"||G==="live-dashboard"};
g.nB.prototype.Wq=g.Uo(39,function(G,m){var w=g.lK(this.jn());w&&w.Wq(G,m)});
var j2={},S2=null;g.aq(oA,g.sN);g.N=oA.prototype;g.N.getDuration=function(){return this.duration};
g.N.play=function(G){if(G||this.V==0)this.progress=0,this.coords=this.Y;else if(this.isPlaying())return!1;Pq(this);this.startTime=G=g.Tm();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.Hn();this.y5("play");this.isPaused()&&this.y5("resume");this.V=1;var m=g.Q9(this);m in j2||(j2[m]=this);S1H();Puq(this,G);return!0};
g.N.stop=function(G){Pq(this);this.V=0;G&&(this.progress=1);oT9(this,this.progress);this.onStop();this.s5()};
g.N.pause=function(){this.isPlaying()&&(Pq(this),this.V=-1,this.y5("pause"))};
g.N.Hk=function(){this.V==0||this.stop(!1);this.y5("destroy");oA.Hj.Hk.call(this)};
g.N.destroy=function(){this.dispose()};
g.N.mO=function(){this.y5("animate")};
g.N.y5=function(G){this.dispatchEvent(new hNd(G,this))};
g.aq(hNd,g.eQ);g.aq(hH,oA);hH.prototype.X=function(){};
hH.prototype.mO=function(){this.X();hH.Hj.mO.call(this)};
hH.prototype.s5=function(){this.X();hH.Hj.s5.call(this)};
hH.prototype.Hn=function(){this.X();hH.Hj.Hn.call(this)};
g.aq(l8d,hH);l8d.prototype.X=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.I(JbR,g.J);g.N=JbR.prototype;g.N.listen=function(G,m,w,W){w=(0,g.De)(w,W||this.Y);G=g.i4(G,m,w);this.V.push(G);return G};
g.N.Tn=function(G,m,w,W){w=(0,g.De)(w,W||this.Y);G=pU9(G,m,w);this.V.push(G);return G};
g.N.JA=function(G){g.K6(G);g.Mn(this.V,G)};
g.N.removeAll=function(){g.K6(this.V);this.V.length=0};
g.N.Hk=function(){this.removeAll();g.J.prototype.Hk.call(this)};g.I(eNd,g.bK);g.N=eNd.prototype;g.N.load=function(){g.bK.prototype.load.call(this);if(!EO(this)){var G=g.riB(this.player.getVideoData());G?(G=FQm(G,nTq(this)),JH(this,G,!1)):xsH(this)}};
g.N.unload=function(){JH(this,null);this.D&&(this.D.abort(),this.D=null);g.bK.prototype.unload.call(this)};
g.N.MI=function(G,m){return EO(this)?G==="loadCustomEndscreenRenderer"?(G=FQm(m,"new"),JH(this,G),!0):null:null};
g.N.getOptions=function(){return EO(this)?["loadCustomEndscreenRenderer"]:[]};
g.N.GP=function(){if(this.endscreen&&this.endscreen.elements){var G=this.player.getVideoContentRect();if(G&&G.width!==0&&G.height!==0){var m=this.player.getPlayerSize();if(m&&m.width!==0&&m.height!==0){var w=G.width/G.height;var W=0;for(var U=-1,c=0;c<qFn.length;c++){var Q=Math.abs(m.width-qFn[c]);if(U===-1||W>=Q)U=c,W=Q}W=TKq[U];this.X&&g.eT(this.X.element,"outline-width",Math.max(m.width,m.height)+"px");for(m=0;m<this.endscreen.elements.length;++m)if(c=this.endscreen.elements[m].id,U=this.Y[c],
Q=this.K[c],U&&Q){var D=Q.width*w/Q.aspectRatio,O=Math.round(Q.width*G.width);c=Math.round(D*G.height);var q=G.left+Math.round(Q.left*G.width),T=G.top+Math.round(Q.top*G.height);g.Gr(U.element,O,c);g.BC(U.element,q,T);g.Wj(U.element,$tH);O>256||c>256?g.Gb(U.element,"ytp-ce-large-round"):O>96||c>96?g.Gb(U.element,"ytp-ce-medium-round"):g.Gb(U.element,"ytp-ce-small-round");g.Wj(U.element,aB4);O=Q.left+Q.width/2;Q=Q.top+D/2;g.Gb(U.element,O<=.5&&Q<=.5?"ytp-ce-top-left-quad":O>.5&&Q<=.5?"ytp-ce-top-right-quad":
O<=.5&&Q>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Wj(U.element,TKq);g.Gb(U.element,W);(U=g.Q7(document,"div","ytp-ce-expanding-overlay-body",U.element)[0])&&g.eT(U,"height",c+"px")}}}}};
g.N.onCueRangeEnter=function(G){if(this.endscreen)if(G.getId()==="ytp-ce-in-endscreen")nF(this,this.endscreen.impressionUrls),(G=g.IC())&&this.endscreen.visualElement&&g.B7(G,this.endscreen.visualElement),this.V&&(g.Gb(this.V,"ytp-ce-element-show"),this.V.removeAttribute("aria-hidden"),this.player.fX()?g.Gb(this.V,"ytp-ce-hide-button-lower"):g.wV(this.V,"ytp-ce-hide-button-lower"));else{G=G.getId().substring(15);var m=this.Y[G],w=this.K[G];g.Gb(m.element,"ytp-ce-element-show");m.element.removeAttribute("aria-hidden");
m=this.player.getRootNode();g.Gb(m,"ytp-ce-shown");nF(this,w.impressionUrls);(m=g.IC())&&g.B7(m,w.visualElement);this.player.S().C&&this.player.G2("endscreenelementshown",G)}};
g.N.onCueRangeExit=function(G){if(G.getId()==="ytp-ce-in-endscreen")this.V&&(g.wV(this.V,"ytp-ce-element-show"),this.V.setAttribute("aria-hidden","true"));else{G=G.getId().substring(15);var m=this.Y[G];g.wV(m.element,"ytp-ce-element-show");m.element.setAttribute("aria-hidden","true");m=this.player.getRootNode();g.wV(m,"ytp-ce-shown");this.player.S().C&&this.player.G2("endscreenelementhidden",G)}};
g.N.qQj=function(G){var m=this;G.target===window&&(new g.ey(function(){for(var w=g.V(Object.values(m.Y)),W=w.next();!W.done;W=w.next())g.Wj(W.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.N.tY=function(G){for(var m=g.V(Object.values(this.Y)),w=m.next();!w.done;w=m.next())w=w.value,G?w.element.setAttribute("hidden",""):w.element.removeAttribute("hidden")};
g.N.UVy=function(G){this.V&&this.player.getRootNode().removeChild(this.V);G&&(g.Gb(G,"ytp-ce-hide-button-container"),this.V=G,g.ye(this.player,this.V,4))};
var qFn=[346,426,470,506,570,640,853,1280,1920],TKq="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),aB4=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],$tH=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var sbc={Ny6:"current",GCB:"new"};var Qbq={CLOSE:"close",Uly:"openUrl",SUBSCRIBE:"subscribe"},v14={tHC:"click",CLOSE:"close",rOC:"hidden",SwC:"rollOut",gwf:"rollOver",bTM:"shown"};O0z.prototype.Po=function(){var G=qzH(this,function(m){return m.type==="openUrl"&&m.url!=null});
return G?G.url:null};
var vaf={h8E:"anchored",Yn:"branding",CHANNEL:"channel",n8B:"cta",JOM:"highlightText",Dlf:"label",PLAYLIST:"playlist",POPUP:"popup",lnM:"speech",SUBSCRIBE:"subscribe",fnj:"title",VIDEO:"video",YZ6:"website"},Q4c={Yn:"branding",FUj:"card",E82:"drawer",j3d:"highlight",LtM:"marker",fH2:"promotion",TEXT:"text",mi6:"widget"};g.I(Xc,g.J);g.N=Xc.prototype;g.N.addCueRange=function(G,m,w,W,U){G=new g.nk(G,m,{id:w,namespace:"annotations_module"});W&&this.OM.set(G,W);U&&this.kB.set(G,U);this.context.N.Zr([G],1)};
g.N.KC=function(){this.context.Y.subscribe("resize",this.rk,this)};
g.N.n5=function(){return this.element};
g.N.z5=function(G,m,w,W,U,c){if(this.Qj)return!1;c&&(c.stopPropagation(),c.preventDefault());this.navigate(G,w,W,U);return!1};
g.N.show=function(){};
g.N.hide=function(){};
g.N.destroy=function(){g.Nb(this.n5())};
g.N.rk=function(){};
g.N.navigate=function(G,m,w,W){var U=this,c=ut(G);if(c){var Q=Klz(c,G.target),D=function(){G.V&&U.context.N.pauseVideo();var O=U.context.videoData.UL||!1,q=g.X7(c||"");O&&q&&(q.v||q.list)?U.context.N.NH(q.v,m,q.list,!1):g.JI(c||"",Q==="current"?"_top":void 0,m)};
Q==="new"&&(D(),D=null);Oy(this.context.logger,w,D,W);i0m(c)||(w=g.IC(),W=m.itct,w&&W&&g.yX(w,g.iD(W)))}};
g.N.Hk=function(){this.OM.clear();this.kB.clear();g.J.prototype.Hk.call(this)};
g.N.createElement=function(G){G=new g.x(G);g.r(this,G);return G.element};g.I(IIm,Xc);g.N=IIm.prototype;g.N.zC=function(){this.D6&&Uy(this,this.D6)};
g.N.isAvailable=function(){var G;if(G=!!this.cards.length)(G=this.N.getRootNode())?(G=g.mF(G),G=173<G.width&&173<G.height):G=!1;return G};
g.N.rk=function(){var G=this.isAvailable();g.wp(this.n5(),G);g.UN(this.context.N.getRootNode(),g.bm.IV_DRAWER_ENABLED,G);RA(this.N)};
g.N.destroy=function(){this.N.Wq(!1);try{this.N.getRootNode().removeChild(this.D)}catch(G){}g.Gz(this.YB);g.L6(this.EM);this.Z6&&this.Z6.dispose();this.K&&this.K.dispose();Xc.prototype.destroy.call(this)};
g.N.Q2=function(){var G=this;this.context.V.listen(g.vC("iv-drawer-close-button",this.D),"click",this.C6,this);this.context.V.listen(this.Y,"touchend",function(){G.J4.start()});
this.context.V.listen(this.Y,"scroll",this.l1,this);this.context.Y.subscribe("onHideControls",function(){G.Pk=!0});
this.context.Y.subscribe("onShowControls",function(){G.Pk=!1});
this.context.Y.subscribe("onVideoAreaChange",function(){G.Pk=g.yR(G.N.getRootNode(),"ytp-autohide")});
this.YB.push(g.yJ("iv-button-shown",this.YM6,this));this.YB.push(g.yJ("iv-button-hidden",this.Vf4,this));g1e(this)};
g.N.findLastIndex=function(G){if(this.cards.length===0)return 0;var m=g.Iq(this.cards,function(w){return G.uI.startMs>w.uI.startMs||G.uI.startMs===w.uI.startMs&&G.uI.timestamp>=w.uI.timestamp?!0:!1});
return m===-1?0:m+1};
g.N.C6=function(){if(this.X){Oy(this.context.logger,QT(this).ET.close);var G=g.IC();G&&this.C&&g.yX(G,this.C);wC(this)}};
g.N.l1=function(){g.UN(this.D,"iv-drawer-scrolled",this.Y.scrollTop>0)};
g.N.YM6=function(){var G=g.IC(),m=QT(this);m=m?m.Yj:this.Yj;G&&m&&g.An(G,[m])};
g.N.Vf4=function(){var G=g.IC(),m=QT(this);m=m?m.Yj:this.Yj;G&&m&&g.X8(G,[m])};
g.N.qo=function(){var G=QT(this);Oy(this.context.logger,G.ET.OI);var m=g.IC();if(m&&G)if(this.N.J("web_infocards_teaser_show_logging_fix")){var w=[];G.lP&&w.push(G.lP);G.Yj&&w.push(G.Yj);w.length>0&&g.An(m,w)}else g.An(m,[G.lP,G.Yj])};
g.N.Xk2=function(){var G=g.IC(),m=QT(this);G&&m&&g.X8(G,[m.lP])};
g.N.I_=function(G){var m=QT(this),w=g.IC();this.V?G?(G=this.context.logger,Oy(G,m.ET.Dl),G.N.sendVideoStatsEngageEvent(4,void 0),w&&m.lP&&g.yX(w,m.lP)):(G=this.context.logger,Oy(G,m.ET.Dl),G.N.sendVideoStatsEngageEvent(4,void 0),w&&m.Yj&&g.yX(w,m.Yj)):(G=this.context.logger,Oy(G,m.ET.Dl),G.N.sendVideoStatsEngageEvent(4,void 0),w&&this.Yj&&g.yX(w,this.Yj))};g.I(vi,Xc);vi.prototype.KC=function(){Xc.prototype.KC.call(this);Pz4(this)};
vi.prototype.show=function(){Xc.prototype.show.call(this);var G=g.IC(),m=this.annotation.data;G&&m&&(m=m.session_data)&&g.An(G,[g.iD(m.itct)])};
vi.prototype.hide=function(){Xc.prototype.hide.call(this);var G=g.IC(),m=this.annotation.data;G&&m&&(m=m.session_data)&&g.X8(G,[g.iD(m.itct)])};g.I(D9,vi);
D9.prototype.show=function(){if(!this.isActive){vi.prototype.show.call(this);if(!this.L){g.Gb(this.n5(),"iv-branding");var G=this.annotation.data;this.Y=this.createElement({B:"img",fM:["branding-img","iv-click-target"],W:{"aria-label":"Filigrane de cha\u00eene",src:G.image_url,width:G.image_width,height:G.image_height}});g.wp(this.Y,!1);var m=this.createElement({B:"button",fM:["branding-img-container","ytp-button"]});m.appendChild(this.Y);this.n5().appendChild(m);var w=this.annotation.Po();w&&yw(this,
m,w,this.annotation.id,G.session_data);this.context.N.J("disable_branding_context")||Czg(this,G);this.L=!0}g.wp(this.n5(),!0);this.isActive=!0;if(this.Y){try{o19(this,this.Y)}catch(W){}g.Gb(this.context.N.getRootNode(),"ytp-branding-shown");this.context.N.getRootNode().style.setProperty("--branding-image-width",this.Y.getAttribute("width")+"px")}}};
D9.prototype.hide=function(){this.isActive&&(vi.prototype.hide.call(this),g.wp(this.n5(),!1),this.isActive=!1,g.wV(this.context.N.getRootNode(),"ytp-branding-shown"))};
D9.prototype.destroy=function(){this.V&&(this.V.dispose(),this.V=null);g.wV(this.context.N.getRootNode(),"ytp-branding-shown");vi.prototype.destroy.call(this)};g.I(J6c,vi);g.N=J6c.prototype;g.N.show=function(){this.isActive||(vi.prototype.show.call(this),this.U||(FlR(this),this.U=!0),g.wp(this.n5(),!0),g.P5(function(){g.wV(this.n5(),"iv-promo-inactive")},100,this),this.n5().removeAttribute("aria-hidden"),this.isActive=!0,uum(this),e4q(this),n1g(this,this.K))};
g.N.hide=function(){this.isActive&&(g.Gb(this.n5(),"iv-promo-inactive"),this.isActive=!1,this.n5().setAttribute("aria-hidden","true"))};
g.N.z5=function(G,m,w,W,U,c){return this.isCollapsed?!1:vi.prototype.z5.call(this,G,m,w,W,U,c)};
g.N.OH=function(G){this.C=!0;r6q(this,500,G)};
g.N.gI=function(){this.C=!1;xiH(this)};
g.N.CH=function(G){G.stopPropagation();this.hide()};
g.N.yr=function(G){G.stopPropagation();uum(this);this.isCollapsed=!0;g.Gb(this.n5(),"iv-promo-collapsed-no-delay");this.j.start()};
g.N.destroy=function(){this.j.dispose();vi.prototype.destroy.call(this)};g.I(Yzn,g.bK);g.N=Yzn.prototype;g.N.MI=function(G,m){if(!OM9(this.player.S().playerStyle))return null;switch(G){case "loadCustomAnnotationsXml":return(G=g.BN(m))&&Gnq(this,G),!0;case "removeCustomAnnotationById":return m&&this.V&&(Llf(this.V,m),RA(this.player)),!0}return null};
g.N.getOptions=function(){return OM9(this.player.S().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.N.Dn=function(){var G=this.player.S(),m=this.player.getVideoData(),w=G.annotationsLoadPolicy||m.annotationsLoadPolicy;return m.UL||this.player.isMutedByEmbedsMutedAutoplay()?!1:w===1&&!m.CL||G.Pk.get(m.videoId)||g.sZ(m)||g.cB(m)?!0:!1};
g.N.E9=function(){if(this.X){var G=this.player.A4().getVideoContentRect(!0);g.Gr(this.X.element,G.width,G.height);g.BC(this.X.element,G.left,G.top)}if(this.V){var m=this.player.TC();G=this.V;m=m.width;g.UN(G.D,"iv-drawer-small",m<=426);g.UN(G.D,"iv-drawer-big",m>=1280)}};
g.N.ZK=function(G){A69(this,G.state);g.H(G.state,2)&&(this.fX()&&this.Wb()&&this.player.getPresentingPlayerType()!==2&&this.Si(!1),this.Wq(!1))};
g.N.load=function(){function G(Q){var D=m.loadNumber;m.j=null;m.loaded&&m.loadNumber===D&&m.player.getVideoData().videoId===W&&(Q=g.vA(Q)&&Q.responseXML?Q.responseXML:null)&&(Gnq(m,Q),g.Gb(m.player.getRootNode(),"iv-module-loaded"))}
var m=this;g.bK.prototype.load.call(this);A69(this,this.player.getPlayerStateObject());this.loadNumber++;var w=this.player.getVideoData(),W=w.videoId;g.YN()&&(G=mtR(this,G));var U={format:"XML",onFinish:G,onError:function(){m.j=null},
urlParams:{}};w.isPharma&&(U.urlParams.pharma="1");U.method="POST";U.withCredentials=!0;var c=this.player.S().Pk.get(W);c&&wzc(U,c);c=c&&(c.cU||c.Rd);if(!w.Kz||c)w.EM?Xxd(this,w.EM,U):(this.L=function(){if(!m.C)m.onVideoDataChange(U);var Q=m.player.getVideoData();(Q==null?0:g.UZ(Q))&&!m.YB&&cjR(m,Q)},this.player.addEventListener("videodatachange",this.L));
g.ye(this.player,this.X.element,4);this.E9();(c=g.sZ(w))&&s4d(this,c);(c=g.cB(w))&&c.featuredChannel&&Dtq(this,c.featuredChannel,c.annotationId||"branding",w.videoId||null,w.eventId||null);this.Ya=g.vC("ytp-cards-button",this.player.getRootNode());g.UZ(w)&&cjR(this,w)};
g.N.onVideoDataChange=function(G){var m=this.player.getVideoData();m.EM&&Xxd(this,m.EM,G)};
g.N.unload=function(){this.player.eZ("annotations_module");for(var G=g.V(Object.keys(this.K)),m=G.next();!m.done;m=G.next())this.K[m.value].destroy();this.U=null;this.V&&(this.V.destroy(),this.V=null,RA(this.player));this.C=!1;this.j&&(this.j.abort(),this.j=null);this.YB=!1;this.K={};this.Y.hide();g.bK.prototype.unload.call(this);this.X.detach();this.L&&(this.player.removeEventListener("videodatachange",this.L),this.L=null)};
g.N.XM=function(G){G===this.player.getVideoData().videoId&&(this.loaded?Wug(this):this.load())};
g.N.fX=function(){var G;return((G=this.V)==null?void 0:G.isAvailable())||this.YB};
g.N.Wb=function(){return!!this.V&&this.V.X};
g.N.Si=function(G,m,w){m=m===void 0?!1:m;this.fX();this.V&&(G?w?mf(this.V,w,m):mf(this.V,"YOUTUBE_DRAWER_AUTO_OPEN",m):wC(this.V))};
g.N.Wq=function(G,m){this.player.publish(G?"cardsteasershow":"cardsteaserhide",m)};
g.N.Hk=function(){this.player.S().Pk.unsubscribe("vast_info_card_add",this.XM,this);g.wV(this.player.getRootNode(),g.bm.IV_DRAWER_OPEN);for(var G=this.D6,m=g.Pv,w=0,W=G.length;w<W;w++)m.Pd(G[w]);this.D6.length=0;g.bK.prototype.Hk.call(this)};
g.N.createElement=function(G){G=new g.x(G);g.r(this,G);return G.element};g.Lf("annotations_module",Yzn);g.Lf("creatorendscreen",eNd);})(_yt_player);
