(function(g){var window=this;'use strict';var iMR=function(G,m,w){g.h(function(W){G.V=g.N4(m,w);g.VZ(W)})},TP=function(G){G.isActive()||G.start()},Ku9=function(G,m){return m?G.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},NKR=function(G){return g.Mu(G)||G.J("web_enable_caption_language_preference_stickiness")},IBn=function(G,m){var w=new g.rF;
w.languageCode=G.languageCode;w.languageName=G.languageName;w.name=G.name;w.displayName=G.displayName;w.kind=G.kind;w.isDefault=!1;w.V=G.V;w.isTranslateable=G.isTranslateable;w.vssId=G.vssId;w.url=G.url;w.translationLanguage=m;G.xtags&&(w.xtags=G.xtags);G.captionId&&(w.captionId=G.captionId);return w},z0n=function(G,m){var w,W,U;
return g.h(function(c){if(c.Y==1)return w=G+"|"+m,g.S(c,g.HL(),2);if(c.Y!=3){W=c.V;if(!W)throw g.kc("gct");return g.S(c,g.c9(W),3)}U=c.V;return c.return(U.get("captions",w))})},V6c=function(G,m,w){z0n(G,m).then(function(W){W&&w(W.trackData,new g.rF(W.metadata))})},bMc=function(G){if(!M6b.test(G))throw Error("'"+G+"' is not a valid hex color");
G.length==4&&(G=G.replace(Lue,"#$1$1$2$2$3$3"));G=G.toLowerCase();G=parseInt(G.slice(1),16);return[G>>16,G>>8&255,G&255]},t6q=function(){var G=void 0;
G=G===void 0?{}:G;var m="suggest_correction"in g.Hhq?g.Hhq.suggest_correction:"Edit caption";m=m||"";var w={},W;for(W in G){w={Ps:w.Ps};w.Ps=W;var U=function(c){return function(){return String(G[c.Ps])}}(w);
m=m.replace(new RegExp("\\$\\{"+w.Ps+"\\}","gi"),U);m=m.replace(new RegExp("\\$"+w.Ps,"gi"),U)}return m},gaf=function(){return g.de("yt-player-caption-display-settings")},$0=function(){this.segments=[]},dte=function(G,m){var w=g.FH(G.segments,m);
w>=0||w<0&&(-w-1)%2===1||(w=-w-1,w>0&&m-G.segments[w-1]===1&&w<G.segments.length&&G.segments[w]-m===1?(g.V9(G.segments,w),g.V9(G.segments,w-1)):w>0&&m-G.segments[w-1]===1?G.segments[w-1]=m:w<G.segments.length&&G.segments[w]-m===1?G.segments[w]=m:(g.Eq(G.segments,w,0,m),g.Eq(G.segments,w+1,0,m)))},fBb=function(G,m,w,W,U,c){g.J.call(this);
this.policy=G;this.player=m;this.YB=w;this.C=W;this.j=U;this.U=c;this.D=new $0;this.K=-1;this.X=this.Y=this.V=null;this.D6=0;this.L=new g.ey(this.zR,1E3,this);this.events=new g.Mh(this);g.r(this,this.L);g.r(this,this.events);this.events.T(m,"SEEK_COMPLETE",this.Nr);this.Nr();this.zR()},R0n=function(G){return G.V&&G.V.K?G.V.K+G.player.mx()<G.player.getCurrentTime():!1},pzH=function(G,m){if(G.policy.f2&&G.player.cF()){var w=g.$X(m,G.policy,{});
w.set("pot",G.player.cF());w=w.Po()}else w=g.$X(m,G.policy,{}).Po();var W={format:"RAW",withCredentials:!0};if(G.policy.pM){W.method="POST";var U=m.D;U&&Object.keys(U).length>0?W.postBody=g.u7(U,g.jw):W.postBody=(0,g.Cb)([120,0])}G.j&&(W.responseType="arraybuffer");var c=++G.D6,Q=(0,g.V6)();G.X=g.M4(w,W,3,100,-1,function(D){D.errorCode==="net.timeout"&&G.player.XC("capnt",{rn:c++})}).then(function(D){if(G.policy.Ds&&c%100===1){var O=(0,g.V6)();
G.player.XC("caprsp",{rn:c,ms:O-Q,kb:(D.xhr.responseText.length/1024).toFixed()})}a:{D=D.xhr;G.i6();if(G.Y){var q=!(G.j?D.response:D.responseText)||D.status>=400;if(O=g.UN6(D)){D=g.$X(G.Y,G.policy,{});G.Y.TW(D,O);pzH(G,G.Y);break a}if(q)G.player.XC("capfail",{status:D.status});else{var T;g.ms("fcb_r",(0,g.V6)(),((T=G.player.getVideoData())==null?void 0:T.YB)||"");T=G.Y.wd[0].Ry;G.C!=null&&G.K!==T&&(O=G.Y.wd[0],G.j?G.C(D.response,(O.startTime+G.player.mx())*1E3):G.C(D.responseText,(O.startTime+G.player.mx())*
1E3),G.K=T)}}G.Y=null;G.X=null}}).d7(function(D){G.Y=null;
G.X=null;var O;G.player.XC("capfail",{rn:c,status:(O=D.xhr)==null?void 0:O.status})});
G.Y=m;dte(G.D,G.Y.wd[0].Ry)},ap=function(G,m){g.g6.call(this,m);
this.V=G;this.N=m;this.D=null;this.K=!1;this.logger=new g.MX("caps");this.L=g.mlV(this.N,this.V)},SFe=function(G,m){var w=[],W;
for(W in G.V.V)if(G.V.V.hasOwnProperty(W)){var U=G.V.V[W];if(g.ff(U,m||null)){var c=U.info.id,Q=c,D="."+c,O="",q="";if(U=U.info.captionTrack)c=U.languageCode,Q=U.displayName,D=U.vssId,O=U.kind,q=U.id;else{U=c;var T=g.KQf.get(U);T==null&&(T=j4g[U]||j4g[U.replace(/-/g,"_")],g.KQf.set(U,T));U=T;Q=U||Q}w.push(new g.rF({id:W,languageCode:c,languageName:Q,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:D,kind:O,captionId:q}))}}return w},P_z=function(G,m){return m!=null&&m in G.V.V?G.V.V[m]:null},
oad=function(G,m,w){var W=[],U;
for(U in G.V.V)if(G.V.V.hasOwnProperty(U)){var c=G.V.V[U];if(g.ff(c,w||null)){var Q=c.info.captionTrack;Q&&Q.languageCode===m&&W.push(c)}}return W.length?W[0]:null},Z9=function(G,m,w,W,U,c,Q,D,O,q){var T=q.isInline()&&!0,a={};
Object.assign(a,m);Object.assign(a,G.params);Object.assign(a,w);var Z={};Object.assign(Z,m.DI);G.params.DI&&Object.assign(Z,G.params.DI);Object.assign(Z,w.DI);T&&(a.windowOpacity=.6,Z.backgroundOpacity=0);a.DI=Z;var k=a.t0===1,K=[{B:"span",Z:"captions-text",W:{style:"word-wrap: normal; display: block;"}}],M,t,R;(D=D.vk("caption_edit_on_hover")&&((M=q.getVideoData().getPlayerResponse())==null?void 0:(t=M.captions)==null?void 0:(R=t.playerCaptionsTracklistRenderer)==null?void 0:R.openTranscriptCommand))&&
K.unshift({B:"button",Z:"caption-edit",W:{tabindex:"0","aria-label":t6q()},G:[{B:"svg",W:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},G:[{B:"path",W:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.x.call(this,{B:"div",Z:"caption-window",W:{id:"caption-window-"+G.id,dir:k?"rtl":"ltr",tabindex:"0",lang:a.lang},G:K});var f=
this;this.L=[];this.rd=!1;this.Y=G;this.Pk=this.pM=null;this.fV=c;this.hA=Q;this.C=null;this.maxWidth=c*.96;this.maxHeight=Q*.96;this.V=a;this.gz=w;this.D6=m;this.D=this.nM("captions-text");this.Bl=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Z6=h0g(W,U,c,Q);this.Wl=O;D&&(this.K=this.nM("caption-edit"),this.T(this.K,"click",function(){f.Wl()}));
this.type=0;this.OM=this.Z6*lBc(Z);this.hY=T;G=new g.rj(this.element,!0);g.r(this,G);G.subscribe("dragstart",this.mR,this);G.subscribe("dragmove",this.Ti,this);G.subscribe("dragend",this.o_,this);this.yj=this.kB=this.Qj=this.u6=0;G="";this.V.windowOpacity&&(G=bMc(this.V.windowColor),G="rgba("+G[0]+","+G[1]+","+G[2]+","+this.V.windowOpacity+")");m={"background-color":G,display:this.V.isVisible===!1?"none":"","text-align":C_e[this.V.textAlign]};this.Bl&&(m["border-radius"]=G?this.OM/8+"px":"");(this.X=
this.Y.params.t0===2||this.Y.params.t0===3)&&Ead(this,this.element);g.eT(this.element,m);if(T){var P;(P=this.element.parentElement)==null||P.style.setProperty("--caption-window-color",G)}switch(this.V.LT){case 0:case 1:case 2:g.Gb(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Gb(this.element,"ytp-caption-window-bottom")}},Ead=function(G,m){var w="vertical-rl";
G.V.lN===1&&(w="vertical-lr");g.vj&&(w=w==="vertical-lr"?"tb-lr":"tb-rl");g.eT(m,"-o-writing-mode",w);g.eT(m,"-webkit-writing-mode",w);g.eT(m,"writing-mode",w);g.eT(m,"text-orientation","upright");g.Gb(m,"ytp-vertical-caption");G.Y.params.t0===3&&(g.eT(m,"text-orientation",""),g.eT(m,"transform","rotate(180deg)"))},lBc=function(G){var m=1+.25*(G.fontSizeIncrement||0);
if(G.offset===0||G.offset===2)m*=.8;return m},Jjf=function(G,m){var w={},W=m.background?m.background:G.V.DI.background;
if(m.backgroundOpacity!=null||m.background){var U=m.backgroundOpacity!=null?m.backgroundOpacity:G.V.DI.backgroundOpacity;W=bMc(W);w.background="rgba("+W[0]+","+W[1]+","+W[2]+","+U+")";G.Bl&&(w["box-decoration-break"]="clone",w["border-radius"]=G.OM/8+"px")}if(m.fontSizeIncrement!=null||m.offset!=null)w["font-size"]=G.Z6*lBc(m)+"px";W=1;U=m.color||G.V.DI.color;if(m.color||m.textOpacity!=null)U=bMc(U),W=m.textOpacity==null?G.V.DI.textOpacity:m.textOpacity,U="rgba("+U[0]+","+U[1]+","+U[2]+","+W+")",
w.color=U,w.fill=U;var c=m.charEdgeStyle;c===0&&(c=void 0);if(c){U="rgba(34, 34, 34, "+W+")";var Q="rgba(204, 204, 204, "+W+")";m.U2&&(Q=U=m.U2);var D=G.Z6/16/2,O=Math.max(D,1),q=Math.max(2*D,1),T=Math.max(3*D,1),a=Math.max(5*D,1);W=[];switch(c){case 4:for(;T<=a;T+=D)W.push(q+"px "+q+"px "+T+"px "+U);break;case 1:q=window.devicePixelRatio>=2?.5:1;for(c=O;c<=T;c+=q)W.push(c+"px "+c+"px "+U);break;case 2:W.push(O+"px "+O+"px "+Q);W.push("-"+O+"px -"+O+"px "+U);break;case 3:for(T=0;T<5;T++)W.push("0 0 "+
q+"px "+U)}w["text-shadow"]=W.join(", ")}U="";switch(m.fontFamily){case 1:U='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:U='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:U='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:U='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:U='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:U=g.CK()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:U='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}U&&(w["font-family"]=U);U=m.offset;U==null&&(U=G.V.DI.offset);switch(U){case 0:w["vertical-align"]="sub";break;case 2:w["vertical-align"]="super"}m.fontFamily===7&&(w["font-variant"]="small-caps");m.bold&&(w["font-weight"]="bold");m.italic&&(w["font-style"]="italic");m.underline&&(w["text-decoration"]=
"underline");m.Ns&&(w.visibility="hidden");m.u9===1&&G.X&&(w["text-combine-upright"]="all",w["text-orientation"]="mixed",U=g.gF||g.aj,G.Y.params.t0===3?w.transform=U?"rotate(90deg)":"rotate(180deg)":U&&(w.transform="rotate(-90deg)"));if(m.textEmphasis===1||m.textEmphasis===2||m.textEmphasis===3||m.textEmphasis===4||m.textEmphasis===5)if(g.gF)w["font-weight"]="bold";else switch(w["text-emphasis-style"]="filled circle",w["text-emphasis-color"]="currentcolor",w["webkit-text-emphasis"]="filled circle",
m.textEmphasis){case 4:case 3:w["text-emphasis-position"]="under left";w["webkit-text-emphasis-position"]="under left";break;case 5:case 2:w["text-emphasis-position"]="over right",w["webkit-text-emphasis-position"]="over right"}return w},k0=function(G){G=G.split("px");
return G.length>0?(G=Number(G[0]))?G:0:0},rj9=function(G){G.C=g.aI("SPAN");
g.eT(G.C,{display:"block"});g.Gb(G.C,"caption-visual-line");G.D.appendChild(G.C)},FuH=function(G,m){var w=g.aI("SPAN");
g.eT(w,{display:"inline-block","white-space":"pre-wrap"});g.eT(w,Jjf(G,m));w.classList.add("ytp-caption-segment");G.C.appendChild(w);w.previousElementSibling&&(g.eT(w.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.eT(w,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return w},e0q=function(G,m,w){G.rd=G.rd||!!w;
var W={};Object.assign(W,G.V.DI);Object.assign(W,w||m.V);Object.assign(W,G.gz.DI);(w=!G.C)&&rj9(G);for(var U=G.pM&&G.Pk&&g.Zy(W,G.Pk)?G.pM:FuH(G,W),c=typeof m.text==="string",Q=c?m.text.split("\n"):[m.text],D=0;D<Q.length;D++){var O=D>0||!m.append,q=Q[D];O&&!w?(rj9(G),U=FuH(G,W)):O&&w&&(w=!1);q&&(U.appendChild(c?g.ZL(q):q),c||q.tagName!=="RUBY"||q.childElementCount!==4||g.gF||!g.xS(q.children[2],"text-emphasis")||(O=G.X?"padding-right":"padding-top",g.xS(q.children[2],"text-emphasis-position")&&(O=
G.X?"padding-left":"padding-bottom"),g.Ox?g.eT(U,O,"1em"):g.eT(U,O,"0.5em")))}G.Pk=W;G.pM=U;G.L.push(m)},h0g=function(G,m,w,W){var U=m/360*16;
m>=G&&(G=640,W>w*1.3&&(G=480),U=w/G*16);return U},xtH=function(){this.X=this.time=this.mode=this.Y=0;
this.D=new na9(this);this.j=new na9(this);this.V=[];this.clear()},HMd=function(G,m,w){if(G===255&&m===255||!G&&!m)return{Xo:G,
Ha:m,result:0};G=ulq[G];m=ulq[m];if(G&128){var W;if(W=!(m&128))W=m,W=w.yM()&&w.Ha===W;if(W)return{Xo:G,Ha:m,result:1}}else if(m&128&&1<=G&&G<=31)return{Xo:G,Ha:m,result:2};return{Xo:G,Ha:m,result:3}},BKq=function(G,m,w,W){m===255&&w===255||!m&&!w?(++G.X===45&&G.reset(),G.D.Y.clear(),G.j.Y.clear()):(G.X=0,YFb(G.D,m,w,W))},AjH=function(G,m){G.V.sort(function(U,c){var Q=U.time-c.time;
return Q===0?U.order-c.order:Q});
for(var w=g.V(G.V),W=w.next();!W.done;W=w.next())W=W.value,G.time=W.time,W.type===0?BKq(G,W.Tb,W.m6,m):W.type===1&&G.Y&496&&YFb(G.j,W.Tb,W.m6,m);G.V.length=0},iX=function(){this.type=0},Kz=function(){this.state=this.Ha=this.Xo=0},XzH=function(){this.timestamp=this.V=0},NI=function(G){this.j=G;
this.X=[];this.V=this.Y=this.row=0;this.style=new iX;for(G=this.D=0;G<=15;G++){this.X[G]=[];for(var m=0;m<=32;m++)this.X[G][m]=new XzH}},Ip=function(G,m){if(G.style.type===3){for(var w=0,W=0,U=G.j.time+0,c="",Q="",D=U,O=1;O<=15;++O){for(var q=!1,T=W?W:1;T<=32;++T){var a=G.X[O][T];
if(a.V!==0){w===0&&(w=O,W=T);q=String.fromCharCode(a.V);var Z=a.timestamp;Z<U&&(U=Z);a.timestamp=D;Q&&(c+=Q,Q="");c+=q;q=!0}if((a.V===0||T===32)&&q){Q="\n";break}else if(W&&!q)break}if(w&&!q)break}c&&m.D(w,W,U,D,c)}else for(W=w=0,c=U=G.j.time+0,Q=1;Q<=15;++Q)for(D="",O=1;O<=32;++O)if(T=G.X[Q][O],a=T.V,a!==0&&(w===0&&(w=Q,W=O),q=String.fromCharCode(a),Z=T.timestamp,Z<=U&&(U=Z),D+=q,T.reset()),O===32||a===0)D&&m.D(w,W,U,c,D),U=c,D="",W=w=0},Wy9=function(G,m){switch(G){case 0:return yj9[(m&127)-32];
case 1:return GJn[m&15];case 2:return mkH[m&31];case 3:return wcq[m&31]}return 0},zP=function(G){return G.X[G.row][G.Y]},VT=function(G,m,w){m>=2&&G.Y>1&&(--G.Y,zP(G).V=0);
var W=zP(G);W.timestamp=G.j.time+0;W.V=Wy9(m,w);G.Y<32&&G.Y++},Ukc=function(G,m,w,W){for(var U=0;U<W;U++)for(var c=0;c<=32;c++){var Q=G.X[m+U][c],D=G.X[w+U][c];
Q.V=D.V;Q.timestamp=D.timestamp}},MI=function(G,m,w){for(var W=0;W<w;W++)for(var U=0;U<=32;U++)G.X[m+W][U].reset()},sOH=function(G){G.row=G.V>0?G.V:1;
G.Y=1;MI(G,0,15)},cPm=function(G){this.X=G;
this.j=0;this.style=new iX;this.K=new NI(this.X);this.L=new NI(this.X);this.text=new NI(this.X);this.Y=this.K;this.D=this.L;this.V=this.Y},QOR=function(G,m,w){var W=G.Y,U=!1;
switch(G.style.get()){case 4:case 1:case 2:G.style.get()===4&&W.V>0||(Ip(W,w),sOH(G.Y),sOH(G.D),W.row=15,W.V=m,U=!0)}G.style.set(3);G.V=W;G.V.style=G.style;G.X.mode=1<<W.D;U?W.Y=1:W.V!==m&&(W.V>m?(Ip(W,w),MI(W,W.row-W.V,m)):W.row<m&&(m=W.V),W.V=m)},vOf=function(G){G.style.set(1);
G.V=G.D;G.V.V=0;G.V.style=G.style;G.X.mode=1<<G.V.D},Dkg=function(G){G.style.set(4);
G.V=G.text;G.V.style=G.style;G.X.mode=1<<G.V.D},na9=function(G){this.V=G;
this.j=0;this.X=new cPm(this.V);this.K=new cPm(this.V);this.Y=new Kz;this.D=this.X},YFb=function(G,m,w,W){G.Y.update();
m=HMd(m,w,G.Y);switch(m.result){case 0:return;case 1:case 2:return}var U=m.Xo;w=m.Ha;if(32<=U||!U)G.V.mode&G.V.Y&&(m=U,m&128&&(m=127),w&128&&(w=127),G=G.D.V,m&96&&VT(G,0,m),w&96&&VT(G,0,w),m!==0&&w!==0&&G.style.type===3&&Ip(G,W));else if(U&16)a:if(!G.Y.matches(U,w)&&(m=G.Y,m.Xo=U,m.Ha=w,m.state=2,m=U&8?G.K:G.X,G.D=m,G.V.mode=1<<(G.j<<2)+(m.j<<1)+(m.style.type===4?1:0),(G.V.mode|1<<(G.j<<2)+(m.j<<1)+(m.style.type!==4?1:0))&G.V.Y))if(w&64){W=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(U&7)<<1|w>>5&1];
G=w&16?((w&14)>>1)*4:0;w=m.V;switch(m.style.get()){case 4:W=w.row;break;case 3:if(W!==w.row){if(W<w.V&&(W=w.V,W===w.row))break;var c=1+w.row-w.V,Q=1+W-w.V;Ukc(w,Q,c,w.V);m=c;U=w.V;Q<c?(c=Q+U-c,c>0&&(m+=c,U-=c)):(c=c+U-Q,c>0&&(U-=c));MI(w,m,U)}}w.row=W;w.Y=G+1}else switch(U&7){case 1:switch(w&112){case 32:VT(m.V,0,32);break a;case 48:w===57?(W=m.V,zP(W).V=0,W.Y<32&&W.Y++):VT(m.V,1,w&15)}break;case 2:w&32&&VT(m.V,2,w&31);break;case 3:w&32&&VT(m.V,3,w&31);break;case 4:case 5:if(32<=w&&w<=47)switch(w){case 32:vOf(m);
break;case 33:W=m.V;W.Y>1&&(--W.Y,zP(W).V=0);break;case 36:W=m.V;m=zP(W);for(G=0;G<=15;G++)for(w=0;w<=32;w++)if(W.X[G][w]===m){for(;w<=32;w++)W.X[G][w].reset();break}break;case 37:QOR(m,2,W);break;case 38:QOR(m,3,W);break;case 39:QOR(m,4,W);break;case 40:VT(m.V,0,32);break;case 41:m.style.set(2);m.V=m.Y;m.V.V=0;m.V.style=m.style;m.X.mode=1<<m.V.D;break;case 42:W=m.text;W.V=15;W.style.set(4);sOH(W);Dkg(m);break;case 43:Dkg(m);break;case 44:G=m.Y;switch(m.style.get()){case 1:case 2:case 3:Ip(G,W)}MI(G,
0,15);break;case 45:b:{G=m.V;switch(m.style.get()){default:case 2:case 1:break b;case 4:if(G.row<15){++G.row;G.Y=1;break b}break;case 3:}G.V<2&&(G.V=2,G.row<G.V&&(G.row=G.V));m=G.row-G.V+1;Ip(G,W);Ukc(G,m,m+1,G.V-1);MI(G,G.row,1)}break;case 46:MI(m.D,0,15);break;case 47:Ip(m.Y,W),m.D.updateTime(m.X.time+0),W=m.D,m.D=m.Y,m.Y=W,vOf(m)}break;case 7:switch(w){case 33:case 34:case 35:W=m.V,(W.Y+=w&3)>32&&(W.Y=32)}}},OWd=function(){},Lz=function(G,m,w,W,U,c,Q){c=c===void 0?!1:c;
Q=Q===void 0?null:Q;g.nk.call(this,G,G+m,{priority:w,namespace:"captions"});this.windowId=W;this.text=U;this.append=c;this.V=Q},THe=function(G,m,w,W,U,c,Q){var D=c[0],O=Q[D.getAttribute("p")];
if(O.RJ===1){var q=c[1],T=c[2];c=c[3];D.getAttribute("t");q.getAttribute("t");T.getAttribute("t");c.getAttribute("t");D.getAttribute("p");q.getAttribute("p");c.getAttribute("p");Q=Q[T.getAttribute("p")];D=qT4(D.textContent,q.textContent,T.textContent,c.textContent,Q);return new Lz(G,m,U,w,D,W,O)}switch(O.RJ){case 9:case 10:O.textEmphasis=1;break;case 11:O.textEmphasis=2;break;case 12:O.textEmphasis=3;break;case 13:O.textEmphasis=4;break;case 14:O.textEmphasis=5}return new Lz(G,m,U,w,D.textContent||
"",W,O)},qT4=function(G,m,w,W,U){var c=g.CK(),Q=c?g.aI("DIV"):g.aI("RUBY"),D=g.aI("SPAN");
D.textContent=G;Q.appendChild(D);G=c?g.aI("DIV"):g.aI("RP");G.textContent=m;Q.appendChild(G);m=c?g.aI("DIV"):g.aI("RT");m.textContent=w;Q.appendChild(m);w=U.RJ;if(w===10||w===11||w===12||w===13||w===14)if(g.eT(m,"text-emphasis-style","filled circle"),g.eT(m,"text-emphasis-color","currentcolor"),g.eT(m,"webkit-text-emphasis","filled circle"),U.RJ===11||U.RJ===13)g.eT(m,"webkit-text-emphasis-position","under left"),g.eT(m,"text-emphasis-position","under left");w=!0;if(U.RJ===4||U.RJ===7||U.RJ===12||
U.RJ===14)g.eT(Q,"ruby-position","over"),g.eT(Q,"-webkit-ruby-position","before");else if(U.RJ===5||U.RJ===6||U.RJ===11||U.RJ===13)g.eT(Q,"ruby-position","under"),g.eT(Q,"-webkit-ruby-position","after"),w=!1;U=c?g.aI("DIV"):g.aI("RP");U.textContent=W;Q.appendChild(U);c&&(W=w,g.eT(Q,{display:"inline-block",position:"relative"}),c=Q.firstElementChild.nextElementSibling,g.eT(c,"display","none"),c=c.nextElementSibling,g.eT(c,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.eT(Q.lastElementChild,"display","none"),W?(g.eT(Q,"padding-top","0.6em"),g.eT(c,"top","0")):(g.eT(Q,"padding-bottom","0.6em"),g.eT(c,"bottom","0")));return Q},bX=function(){g.J.apply(this,arguments)},tB=function(G,m,w,W,U){g.nk.call(this,G,G+m,{priority:w,
namespace:"captions"});this.id=W;this.params=U;this.V=[]},$km=function(G){var m="_"+gC++;
return new tB(0,0x8000000000000,0,m,G)},dC=function(G){bX.call(this);
this.D=G;this.pens={};this.C={};this.U={};this.j="_"+gC++;this.L={};this.Y=this.V=null;this.K=!0},fz=function(G,m){G=G.getAttribute(m);
if(G!=null)return Number(G)},Rp=function(G,m){G=G.getAttribute(m);
if(G!=null)return G==="1"},pz=function(G,m){G=fz(G,m);
return G!==void 0?G:null},Sr=function(G,m){G=G.getAttribute(m);
if(G!=null)return jr.test(G),G},atd=function(G,m){var w={},W=m.getAttribute("ws");
Object.assign(w,W?G.U[W]:G.D);G=pz(m,"mh");G!=null&&(w.t_=G);G=pz(m,"ju");G!=null&&(w.textAlign=G);G=pz(m,"pd");G!=null&&(w.t0=G);G=pz(m,"sd");G!=null&&(w.lN=G);G=Sr(m,"wfc");G!=null&&(w.windowColor=G);m=fz(m,"wfo");m!==void 0&&(w.windowOpacity=m/255);return w},ZW4=function(G,m){var w={},W=m.getAttribute("wp");
W&&Object.assign(w,G.C[W]);G=pz(m,"ap");G!=null&&(w.LT=G);G=fz(m,"cc");G!=null&&(w.Nh=G);G=fz(m,"ah");G!=null&&(w.FD=G);G=fz(m,"rc");G!=null&&(w.Zo=G);m=fz(m,"av");m!=null&&(w.ix=m);return w},kJn=function(G,m,w,W){var U={};
Object.assign(U,ZW4(G,m));Object.assign(U,atd(G,m));W?g.Zy(U,G.D)?(W=G.j,U=G.D):W="_"+gC++:W=m.getAttribute("id")||"_"+gC++;G=fz(m,"t")+w;m=fz(m,"d")||0x8000000000000;if(U.t0===2||U.t0===3)w=U.Zo,U.Zo=U.Nh,U.Nh=w;return new tB(G,m,0,W,U)},Pi=function(G){bX.call(this);
this.K=G;this.V=new Map;this.D=new Map;this.j=new Map;this.Y=new Map},op=function(G){G=g.JQ(Math.round(G),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-G.length)+G},iW4=function(G,m,w,W,U){W===0&&(W=0x8000000000000);
var c={};m.wpWinPosId&&Object.assign(c,G.D.get(m.wpWinPosId));m.wsWinStyleId&&Object.assign(c,G.j.get(m.wsWinStyleId));G=m.rcRowCount;G!==void 0&&(c.Zo=G);m=m.ccColCount;m!==void 0&&(c.Nh=m);if(c.t0===2||c.t0===3)m=c.Zo,c.Zo=c.Nh,c.Nh=m;return new tB(w,W,0,U,c)},hB=function(G,m,w){g.g6.call(this,G);
this.videoData=m;this.audioTrack=w;this.j=m.jW},lX=function(G,m,w,W,U,c,Q,D,O,q){Z9.call(this,G,m,w,W,U,c,Q,D,O,q);
this.type=1},Cz=function(G,m,w){this.trackData=G;
this.K=w;this.version=this.j=this.X=this.byteOffset=0;this.Y=[];this.V=new DataView(this.trackData)},Ey=function(G){var m=G.byteOffset;
G.byteOffset+=1;return G.V.getUint8(m)},JB=function(G){var m=G.byteOffset;
G.byteOffset+=4;return G.V.getUint32(m)},rC=function(G,m){bX.call(this);
this.Y=G;this.D=m;this.track=this.D.languageName==="CC3"?4:0;this.V=new xtH;this.V.Y=1<<this.track},NHq=function(G){if(typeof G==="string")return!1;
G=new Cz(G,8,0);return Kyc(G)},Kyc=function(G){if(!(G.byteOffset<G.V.byteLength)||JB(G)!==1380139777)return!1;
G.version=Ey(G);if(G.version>1)return!1;Ey(G);Ey(G);Ey(G);return!0},FN=function(G,m,w,W,U,c,Q,D,O,q){Z9.call(this,G,m,w,W,U,c,Q,D,O,q);
var T=this;this.type=2;this.M9=[];this.YB=this.U=this.EM=0;this.J4=NaN;this.x5=0;this.TP=null;this.aM=new g.ey(this.ue,433,this);this.K&&(q.createClientVe(this.K,this,167342),this.T(this.K,"click",function(){q.logClick(T.K)}),G=new g.rj(this.element,!0),g.r(this,G),G.subscribe("hoverstart",function(){q.logVisibility(T.K,!0)},this));
g.Gb(this.element,"ytp-caption-window-rollup");g.r(this,this.aM);g.eT(this.element,"overflow","hidden")},Itn=function(G,m){if(!m)return"";
G.X&&G.Y.params.lN!==1&&(m*=-1);return"translate"+(G.X?"X":"Y")+"("+m+"px)"},zdb=function(G){G.M9=Array.from(G.element.getElementsByClassName("caption-visual-line"));
for(var m=G.Y.params.Zo,w=0,W=0,U=G.M9.length-1;w<m&&U>-1;){var c=G.M9[U];W+=G.X?c.offsetWidth:c.offsetHeight;w++;U--}G.U=W;m=Math;w=m.max;isNaN(G.J4)&&((W=G.V.Nh)?(U=g.aI("SPAN"),g.zj(U,"\u2013".repeat(W)),g.eT(U,Jjf(G,G.V.DI)),G.D.appendChild(U),G.J4=U.offsetWidth,G.D.removeChild(U)):G.J4=0);W=G.D;G.YB=w.call(m,G.J4,G.x5,(G.X?W.offsetHeight:W.offsetWidth)+1)},Vmd=function(G,m){zdb(G);
var w=G.M9.reduce(function(c,Q){return(G.X?Q.offsetWidth:Q.offsetHeight)+c},0);
w=G.U-w;if(w!==G.EM){var W=w>0&&G.EM===0,U=w<G.EM;m||isNaN(w)||W||!U||(g.Gb(G.element,"ytp-rollup-mode"),G.T(G.element,"transitionend",G.ue));g.eT(G.D,"transform",Itn(G,w));G.EM=w}zdb(G)},Mmq=function(G,m,w,W){var U=this;
this.N=G;this.X=m;this.logger=w;this.L5=W;this.xz=[];this.Ax=[];this.V=null;this.VU={P_4:function(){return U.V},
XR:function(){return U.xz}};
G=g.mN(this.N.S().experiments,"html5_override_micro_discontinuities_threshold_ms");this.Y=G>0?G:10},tmH=function(G,m){G.V=function(w,W){if(w.info.D){var U=w;
if(G.Ax.length>0){for(U=G.Ax.shift();G.Ax.length>0;)U=g.gJ(U,G.Ax.shift());U=g.gJ(U,w)}if(U){w=U;try{var c=g.dJ(w)*1E3}catch(q){c=w.info.startTime*1E3}try{var Q=g.H99(w)*1E3}catch(q){Q=w.info.duration*1E3}if(c<0||Q<0)c<0&&(c=w.info.startTime*1E3),Q<0&&(Q=w.info.duration*1E3);w.info.startTime=c/1E3;w.info.j=c/1E3;w.info.duration=Q/1E3;w.info.C=Q/1E3;c=G.gT(U);Q=c.Ry;c={formatId:c.formatId,startTimeMs:c.startTimeMs,durationMs:c.durationMs,L8:Q,MK:Q};Q=Lyz(G.xz,c.startTimeMs);var D=(w=Q>=0?G.xz[Q]:null)?
w.startTimeMs+w.durationMs:0,O=c.startTimeMs+c.durationMs;!w||c.startTimeMs-D>G.Y?G.xz.splice(Q+1,0,c):(w.durationMs=Math.max(D,O)-w.startTimeMs,w.MK=Math.max(w.MK,c.MK));W(G.xz);W=g.ts(U);bWg(G.X,W.buffer.slice(W.byteOffset,W.byteLength+W.byteOffset),m,U.info.j)}else G.logger.V(350058965,"Empty slice")}else G.Ax.push(w)};
G.N.addEventListener("sabrCaptionsDataLoaded",G.V)},Lyz=function(G,m){G=g.FH(G,{startTimeMs:m},function(w,W){return w.startTimeMs-W.startTimeMs});
return G>=0?G:-G-2},er=function(G,m){g.g6.call(this,m);
this.V=G;this.N=m;this.logger=new g.MX("caps");this.D=this.K=null;this.L=new Mmq(this.N,this,this.logger,this.V.L5)},bWg=function(G,m,w,W){G.logger.debug(function(){return"SABR captions data received for "+W});
G.K?G.D==null?G.logger.V(350058965,"Null loaded track meta data at captions data received"):w.qb(m,G.D,W*1E3):G.logger.V(350058965,"Null Representation at captions data received")},gOq=function(G,m){var w=[],W;
for(W in G.V.V)if(G.V.V.hasOwnProperty(W)){var U=G.V.V[W];if(g.ff(U,m||null)){var c=U.info.id,Q=c,D="."+c,O="",q="";if(U=U.info.captionTrack)c=U.languageCode,Q=U.displayName,D=U.vssId,O=U.kind,q=U.id;w.push(new g.rF({id:W,languageCode:c,languageName:Q,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:D,kind:O,captionId:q}))}}return w},dkd=function(G,m,w){var W=[],U;
for(U in G.V.V)if(G.V.V.hasOwnProperty(U)){var c=G.V.V[U];if(g.ff(c,w||null)){var Q=c.info.captionTrack;Q&&Q.languageCode===m&&W.push(c)}}return W.length?W[0]:null},ftg=function(G,m){if(!g.uI6(G)||G.V!=null&&g.mlV(m,G.V)&&G.V.V.rawcc!=null)return!1;
m=!!G.V&&G.V.isManifestless&&Object.values(G.V.V).some(function(w){return g.ff(w,"386")});
G=!!G.V&&!G.V.isManifestless&&g.vGV(G.V);return m||G},Rdm=function(){bX.call(this)},jOz=function(G){var m=pcc.length;
if(G.byteLength<m)return!1;G=new Uint8Array(G,0,m);for(var w=0;w<m;w++)if(pcc[w]!==G[w])return!1;return!0},STc=function(G,m,w,W,U,c,Q,D,O){switch(Q.tagName){case "b":D.bold=!0;
break;case "i":D.italic=!0;break;case "u":D.underline=!0}for(var q=0;q<Q.childNodes.length;q++){var T=Q.childNodes[q];if(T.nodeType===3)T=new Lz(m,w,W,U.id,T.nodeValue,c||q>0,g.$u(D)?void 0:D),O.push(T),U.V.push(T);else{var a={};Object.assign(a,D);STc(G,m,w,W,U,!0,T,a,O)}}},P8q=function(G){var m=G.split(":");
G=0;m=g.V(m);for(var w=m.next();!w.done;w=m.next())G=G*60+Number(w.value);return G*1E3},oOR=function(G,m,w,W){W=Object.assign({t_:0},W);
return new tB(G,m,w,"_"+gC++,W)},nz=function(G,m){g.J.call(this);
this.N=G;this.h4=m;this.V=null;this.Y=this.N.tF();this.logger=new g.MX("caps")},ltm=function(G,m,w){if(typeof m==="string"||NHq(m))return[{trackData:m,
VY:w}];if(typeof m==="string"&&m.substring(0,6)==="WEBVTT"||typeof m!=="string"&&jOz(m))return[{trackData:m,VY:w}];var W=new DataView(m);if(W.byteLength<=8||W.getUint32(4)!==1718909296)return[];var U=g.Bf6(W);if(G.Y&&U){var c=g.r8H(U),Q=g.Fzd(U);U=U.hx;c&&U&&G.Y.d2(U,c,Q)}G=g.ba(W,1835295092);if(!G||!G.length||!G[0].size)return[];c=[];for(Q=0;Q<G.length;Q++)U=G[Q],U=new Uint8Array(m,U.dataOffset,U.size-(U.dataOffset-U.offset)),U=g.aZ(U),c.push({trackData:U,VY:w+Q*1E3});hde(W,c,w);return c=c.filter(function(D){return!!D.trackData})},
hde=function(G,m,w){var W=g.kD(G,0,1836476516),U=9E4;
W&&(U=g.ia(W)||9E4);W=0;for(var c=g.ba(G,1836019558),Q=0;Q<c.length;Q++){var D=c[Q];Q<m.length&&(D=g.kD(G,D.dataOffset,1953653094))&&(D=g.kD(G,D.dataOffset,1952867444))&&(D=g.Mw(D)/U*1E3,Q===0&&(W=D),m[Q].VY=D-W+w||w*Q*1E3)}},C8m=function(G,m,w){G.V||(G.V=new Rdm);
G=G.V.X(m,w);Math.random()<.01&&g.f4(Error("Deprecated subtitles format in web player: WebVTT"));return G},EOH=function(G){var m={};
if(G=g.ne(G))m.lang=G,g.tOg.test(G)&&(m.t0=1);return m},FyH=function(G){g.bK.call(this,G);
var m=this;this.N=G;this.pM=[];this.M9={};this.OM={};this.C=!1;this.D="NONE";this.V=this.U=this.YB=this.Z6=this.u6=null;this.aM={A0:function(){m.A0()},
qb:function(c,Q,D,O){m.qb(c,Q,D,O)}};
this.Y=null;this.h4=this.N.S();this.videoData=this.N.getVideoData();this.Qj=this.N.A4();this.X={DI:{}};this.K={DI:{}};g.KB(this.videoData)?this.D="OFFLINE":ftg(this.videoData,this.N)?this.D="SABR_LIVE":g.wN6(this.videoData,this.N)?this.D="LIVE":this.videoData.captionTracks.length?this.D="INNERTUBE":this.videoData.jZ&&(this.D="TTS");this.kB=this.h4.controlsType==="3";this.yj=new nz(this.N,this.h4);this.rd=new g.Mh(this);this.L=new g.x({B:"div",Z:"ytp-caption-window-container",W:{id:"ytp-caption-window-container"}});
this.D6={top:0,right:0,bottom:0,left:0,width:1,height:1};var w=null,W=g.pG("yt-html5-player-modules::subtitlesModuleData");W&&(w=new g.V1(W));this.storage=w;var U;this.hY=!((U=G.u3())==null||!U.Z0());this.j=JPH(this);this.J4=!this.j&&this.kB&&this.hY&&(this.D==="LIVE"||this.D==="SABR_LIVE");g.r(this,this.yj);this.j?this.EM=this.Pk=null:(this.Pk=new g.JY(this.Jq,void 0,this),g.r(this,this.Pk),this.EM=new g.ey(this.Ry4,2E3,this),g.r(this,this.EM));g.r(this,this.rd);g.ye(this.player,this.L.element,4);
g.r(this,this.L);this.j||this.rd.T(G,"resize",this.LA);(this.x5=g.Qi(this.h4)&&!g.TZ()&&!this.N.isFullscreen()&&!this.j&&!this.J4)&&this.rd.T(G,"resize",this.esj);this.rd.T(G,"onPlaybackAudioChange",this.OMj);this.rd.T(G,g.uA("captions"),function(c){m.onCueRangeEnter(c)});
this.rd.T(G,g.H_("captions"),function(c){m.onCueRangeExit(c)});
rPH(this,gaf()||{});this.player.Dr("onCaptionsModuleAvailable")},xkd=function(G){if(G.h4.Hu===1||G.videoData.Fb===1||g.Yn(G.videoData,"yt:cc")==="alwayson")return!0;
if(G.videoData.captionTracks.length)var m=G.getAudioTrack().Y;if(G.h4.Hu===2){if(g.Mu(G.h4))var w=ed4(G);else if(G.storage)try{w=G.storage.get("module-enabled")}catch(U){G.storage.remove("module-enabled")}else w=null;if(w!=null)return!!w}w=Ku9(G.player.getAudioTrack(),g.Mu(G.h4));var W=g.Yn(G.videoData,"yt:cc");if(nOH(G)===void 0){if(w==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return W?W==="on":!0;if(w==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return W==="on"}else return W==="on";return m==="ON"||
g.Yn(G.videoData,"yt:cc")==="on"},x0=function(G,m){if(G.Y&&(m===void 0||!m)||!G.videoData.captionTracks.length)return!1;
G=G.getAudioTrack();return!!G.V||G.Y==="FORCED_ON"},nOH=function(G){var m=void 0,w=g.o$(g.P1(),65);
if(g.Mu(G.h4)&&w!=null){if(ed4(G)!=null)return!1;m=!w}return m},Hi=function(G,m){if(!G.V)return null;
if(G.U&&G.U.D)return G.U.D;m=uBz(G,m);m=g.sQ(G.V.Y,m);var w=null;if(NKR(G.h4)){var W=G.N.isInline()?void 0:g.de("yt-player-caption-sticky-language");for(var U=[W,G.videoData.captionsLanguagePreference,G.h4.captionsLanguagePreference,g.Yn(G.videoData,"yt:cc_default_lang")],c=!1,Q=0;Q<U.length;Q++){var D=U[Q];if(D){c=!0;for(var O=0;O<m.length;O++)if(g.ne(m[O])===D)return m[O];for(O=0;O<m.length;O++)if(g.ne(m[O]).split("-")[0]===D.split("-")[0])return m[O]}}if(c&&G.V&&(U=G.V.j,U.length))for(U=g.V(U),
c=U.next();!c.done;c=U.next())if(c=c.value,c.languageCode===W){w=c;break}}else for(W=[G.videoData.captionsLanguagePreference,G.h4.captionsLanguagePreference,g.Yn(G.videoData,"yt:cc_default_lang")],U=0;U<W.length;U++)for(c=0;c<m.length;c++)if(g.ne(m[c])===W[U])return m[c];W=null;G.U&&G.U.X&&(W=G.U.X);W||(W=m.find(function(q){return q.isDefault})||null);
W||(W=m[0]||uX(G));W&&w&&g.ne(W).split("-")[0]!==w.languageCode.split("-")[0]&&(W=IBn(W,w));return W},uX=function(G){return G.U&&G.U.V},Y0=function(G){var m=uX(G);
return!!m&&G.Y===m},HWd=function(G,m){var w=G.N.u3().n5().textTracks;
G=G.Y.toString();for(var W=0;W<w.length;W++){var U=w[W];U.id===G&&(m?U.mode!=="showing"&&(U.mode="showing"):U.mode==="showing"&&(U.mode="disabled"))}},XN=function(G,m,w){G.loaded&&G.unload();
w!=null&&(G.C=w,G.C&&(g.Mu(G.h4)?Bi(G,!!m):AB(G,!!m)));m!==null||x0(G,!0)||G.h0(m,!!m,G.C?"m":"s");G.Y=m;x0(G)&&(G.Y=uX(G));var W;YTb(G,(W=G.Y)!=null?W:void 0);G.load()},APf=function(G,m){if(m instanceof tB){var w=G.M9[m.id];
w&&w.Y!==m&&(w.dispose(),delete G.M9[m.id],w=null);w||(w=BHH(G,m))&&(G.M9[m.id]=w)}else w=m.windowId,G.OM[w]||(G.OM[w]=[]),G.OM[w].push(m)},BHH=function(G,m){var w=XcH(G);
if(!w)return null;var W=G.Y?g.ne(G.Y):null;W&&g.tOg.test(W)&&(m.params.t0=1);var U=G.Qj.getPlayerSize();W=U.height*G.D6.height;U=U.width*G.D6.width;G.h4.playerStyle!=="google-live"||G.X.isDefault||Object.assign(m.params,G.X);switch(m.params.t_!=null?m.params.t_:m.V.length>1?1:0){case 1:return new lX(m,G.X,G.K,w.width,w.height,U,W,G.h4.experiments,G.C9.bind(G),G.N);case 2:return new FN(m,G.X,G.K,w.width,w.height,U,W,G.h4.experiments,G.C9.bind(G),G.N);default:return new Z9(m,G.X,G.K,w.width,w.height,
U,W,G.h4.experiments,G.C9.bind(G),G.N)}},rPH=function(G,m,w){w=w===void 0?!1:w;
var W=yT.DI;G.X={};Object.assign(G.X,yT);G.X.DI={};Object.assign(G.X.DI,W);G.K={DI:{}};var U=m.backgroundOverride?G.K:G.X,c=m.background||W.background;jr.test(c);U.DI.background=c;U=m.colorOverride?G.K:G.X;c=m.color||W.color;jr.test(c);U.DI.color=c;U=m.windowColorOverride?G.K:G.X;c=m.windowColor||yT.windowColor;jr.test(c);U.windowColor=c;U=m.backgroundOpacityOverride?G.K:G.X;c=m.backgroundOpacity;c==null&&(c=W.backgroundOpacity);U.DI.backgroundOpacity=c;U=m.fontSizeIncrementOverride?G.K:G.X;c=m.fontSizeIncrement;
c==null&&(c=W.fontSizeIncrement);U.DI.fontSizeIncrement=c;c=m.fontStyleOverride?G.K:G.X;U=m.fontStyle;U==null&&(U=W.bold&&W.italic?3:W.bold?1:W.italic?2:0);c=c.DI;switch(U){case 1:c.bold=!0;delete c.italic;break;case 2:delete c.bold;c.italic=!0;break;case 3:c.bold=!0;c.italic=!0;break;default:delete c.bold,delete c.italic}U=m.textOpacityOverride?G.K:G.X;c=m.textOpacity;c==null&&(c=W.textOpacity);U.DI.textOpacity=c;U=m.windowOpacityOverride?G.K:G.X;c=m.windowOpacity;c==null&&(c=yT.windowOpacity);U.windowOpacity=
c;U=m.charEdgeStyleOverride?G.K:G.X;c=m.charEdgeStyle;c==null&&(c=W.charEdgeStyle);U.DI.charEdgeStyle=c;U=m.fontFamilyOverride?G.K:G.X;c=m.fontFamily;c==null&&(c=W.fontFamily);U.DI.fontFamily=c;G.loaded&&G.LA();w&&g.ge("yt-player-caption-display-settings",m,2592E3)},yP9=function(G,m){if(!G.V)return{};
if(m){g.$u(m)||G.Vz(m.vss_id,"m");if(G.j||!g.sq(m))return;if(g.$u(m)){XN(G,null,!0);return}for(var w,W=g.sQ(G.V.Y,!0),U=0;U<W.length;U++){var c=W[U];c.languageCode!==m.languageCode||w&&(c.languageName!==m.languageName||(c.captionId||"")!==(m.captionId||"")||g.FW(c)!==m.displayName)||(w=m.translationLanguage?IBn(c,m.translationLanguage):c)}G.K9(m.position);!w||w===G.Y&&G.loaded||(m=g.Mx(),W=g.ne(w),m.length&&W===m[m.length-1]||(m.push(W),g.ge("yt-player-caption-language-preferences",m)),NKR(G.h4)&&
!G.N.isInline()&&g.ge("yt-player-caption-sticky-language",W,2592E3),XN(G,w,!0))}else return G.loaded&&G.Y&&!Y0(G)?g.eL(G.Y):{};return""},m0H=function(G,m,w){m&&!G.YB?(m=$km({t0:0,
lang:"fr"}),G.YB=[m,new Lz(m.start,m.end-m.start,0,m.id,w!=null?w:"Aper\u00e7u des sous-titres")],G.player.Zr(G.YB)):!m&&G.YB&&(G14(G,G.YB),G.YB=null)},G14=function(G,m){G.player.VK(m);
m=g.V(m);for(var w=m.next();!w.done;w=m.next())g.Mn(G.pM,w.value);TP(G.Pk)},YTb=function(G,m){G.h4.J("html5_modify_caption_vss_logging")&&(G.videoData.dQ=m)},XcH=function(G){var m=G.Qj.getVideoContentRect(!0).height,w=G.Qj.getVideoContentRect(!0).width;
if(!m||!w)return null;m*=G.D6.height;w*=G.D6.width;return{width:w,height:m}},AB=function(G,m){if(G.storage)try{G.storage.set("module-enabled",m)}catch(w){}},Bi=function(G,m){G.N.isInline()||g.ge("yt-player-sticky-caption",m,2592E3)},ed4=function(G){if(!G.N.isInline())return g.de("yt-player-sticky-caption")},JPH=function(G){var m,w=!((m=G.N.u3())==null||!m.qf());
return G.kB&&w&&G.D!=="LIVE"&&G.D!=="SABR_LIVE"},uBz=function(G,m){g.vB(G.videoData)&&(m=!0);
m||(m=G.D==="TTS"?!1:G.D==="INNERTUBE"?!1:!0);return m||G.h4.J("web_deprecate_always_includes_asr_setting")&&g.Mu(G.h4)?!0:!!g.o$(g.P1(),66)};
g.g6.prototype.Ez=g.Uo(71,function(){return!1});
g.g6.prototype.XU=g.Uo(70,function(){});
g.d6.prototype.XU=g.Uo(69,function(G,m,w){var W=this;this.i6();m=this.gq(G,m);var U=this.oy.S().J("html5_report_captions_ctmp_qoe"),c=(0,g.V6)();this.p7();iMR(this,m,{format:"RAW",onSuccess:function(Q){W.V=null;if(U){var D=(Q.responseText.length/1024).toFixed(),O=(0,g.V6)();W.videoData.XC("capresp",{ms:O-c,kb:D})}w.qb(Q.responseText,G)},
onError:U?function(Q){var D;Q=(D=Q==null?void 0:Q.status)!=null?D:0;W.videoData.XC("capfail",{status:Q})}:void 0,
withCredentials:!0})});
g.Rl.prototype.XU=g.Uo(68,function(G,m,w){var W=this;this.i6();m=this.gq(G,m);this.p7();this.V=g.N4(m,{format:"RAW",onSuccess:function(U){W.V=null;w.qb(U.responseText,G)},
withCredentials:!0})});
g.Bw.prototype.r4=g.Uo(67,function(){for(var G=g.Q7(document,"track",void 0,this.V),m=0;m<G.length;m++)g.Nb(G[m])});
g.Jl.prototype.r4=g.Uo(66,function(){this.mediaElement.r4()});
g.Bw.prototype.Z0=g.Uo(65,function(){return!(!this.V.textTracks||!this.V.textTracks.addEventListener)});
g.Jl.prototype.Z0=g.Uo(64,function(){return this.mediaElement.Z0()});
g.Bw.prototype.qf=g.Uo(63,function(){return!!this.V.textTracks});
g.Jl.prototype.qf=g.Uo(62,function(){return this.mediaElement.qf()});
g.Bw.prototype.Ca=g.Uo(61,function(G){for(var m=0;m<G.length;m++)this.V.appendChild(G[m])});
g.Jl.prototype.Ca=g.Uo(60,function(G){this.mediaElement.Ca(G)});
g.q$.prototype.d2=g.Uo(59,function(G,m,w){this.EL.d2(G,m,w)});
g.G5.prototype.d2=g.Uo(58,function(G,m,w){this.Y.set(G,{RI:m,Yo:w})});
g.mO.prototype.d2=g.Uo(57,function(G,m,w){this.D6.d2(G,m,w)});
g.q$.prototype.T$=g.Uo(56,function(G){return this.EL.T$(G)});
g.mO.prototype.T$=g.Uo(55,function(G){var m=2;this.j.has(G)?m=0:g.vCe(this,G)&&(m=1);return m});
g.nB.prototype.BE=g.Uo(43,function(G){var m=this.app.PR({playerType:void 0});return m?m.BE(G):!1});
g.sI.prototype.BE=g.Uo(42,function(G){return this.Vj.IJ.BE(G)});
g.oS.prototype.BE=g.Uo(41,function(G){return this.tM().some(function(m){return m.namespace===G})});
g.xA.prototype.BE=g.Uo(40,function(){return!1});
g.nB.prototype.Vz=g.Uo(38,function(G,m){this.app.FC().Vz(G,m)});
g.sI.prototype.Vz=g.Uo(37,function(G,m){this.Vj.Vz(G,m)});
g.WX.prototype.Vz=g.Uo(36,function(G,m){G=[G,m];g.wB(this,g.sd(this.provider),"cfi",G)});
g.PX.prototype.Vz=g.Uo(35,function(G,m){this.qoe&&this.qoe.Vz(G,m)});
g.cw.prototype.Vz=g.Uo(34,function(G,m){this.qU.Vz(G,m)});
g.xA.prototype.Vz=g.Uo(33,function(){});
g.nB.prototype.h0=g.Uo(32,function(G,m,w){this.app.FC().h0(G,m,w)});
g.sI.prototype.h0=g.Uo(31,function(G,m,w){this.Vj.h0(G,m,w)});
g.WX.prototype.h0=g.Uo(30,function(G,m,w){if(this.Pk!==G||this.Wl!==m)m=m==="rawcc"?"":m,w=[G,m,this.Pk,w],g.wB(this,g.sd(this.provider),"cfs",w),this.Pk=G,this.Wl=m});
g.PX.prototype.h0=g.Uo(29,function(G,m,w){this.qoe&&this.qoe.h0(G,m,w)});
g.cw.prototype.h0=g.Uo(28,function(G,m,w){this.qU.h0(G,m,w)});
g.xA.prototype.h0=g.Uo(27,function(){});
g.Od.prototype.c5=g.Uo(12,function(){return this.C});
g.is.prototype.c5=g.Uo(11,function(){return this.FC().tF()});
g.nB.prototype.tF=g.Uo(10,function(){return this.app.c5()});
g.sI.prototype.tF=g.Uo(9,function(){return this.Vj.tF()});
g.cw.prototype.tF=g.Uo(8,function(){var G;return((G=this.loader)==null?void 0:G.c5())||null});
g.xA.prototype.tF=g.Uo(7,function(){return null});
g.WF.prototype.z9=g.Uo(1,function(G){return(G=this.WF(G))?G.V:0});
g.jz.prototype.z9=g.Uo(0,function(){return 0});
var Lue=/#(.)(.)(.)/,M6b=/^#(?:[0-9a-f]{3}){1,2}$/i,j4g={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};$0.prototype.contains=function(G){G=g.FH(this.segments,G);return G>=0||G<0&&(-G-1)%2===1};
$0.prototype.length=function(){return this.segments.length/2};
g.I(fBb,g.J);g.N=fBb.prototype;g.N.Hk=function(){g.J.prototype.Hk.call(this);this.X&&this.X.cancel()};
g.N.Nr=function(){this.seekTo(this.player.getCurrentTime())};
g.N.seekTo=function(G){G-=this.player.mx();var m=this.V;this.V=g.kf(this.YB.Wa(G).wd);m!==this.V&&this.U&&this.U()};
g.N.reset=function(){this.D=new $0;this.K=-1;this.X&&(this.X.cancel(),this.X=null)};
g.N.zR=function(){this.i6();var G;if(G=this.V!=null)G=this.V,G=G.V.bB(G);if(G&&!this.X&&!(this.V&&this.V.startTime-this.player.getCurrentTime()>30)){G=this.V;G=G.V.hn(G);var m=G.wd[0],w;if((w=this.player.getVideoData())==null?0:w.enableServerStitchedDai)if(w=this.player.tF()){var W=m.V.info.id,U=m.Ry,c=G.wd[0].j;if(this.policy.pM){if(w=w.Fn(c,U,W,3))G.D=w}else if(W=w.OE(c,U,W,3))if(w=w.T$(U),w===0)W&&(G.V=new g.YQ(W));else if(w===2){this.L.start();R0n(this)&&this.seekTo(this.player.getCurrentTime());
return}}m.V.index.Vn(m.Ry)?(this.D.contains(G.wd[0].Ry)||pzH(this,G),this.V=g.kf(G.wd)):R0n(this)&&this.seekTo(this.player.getCurrentTime())}this.L.start()};
g.I(ap,g.g6);g.N=ap.prototype;g.N.XU=function(G,m,w){var W=this;this.p7();m=P_z(this,G.getId());m||(m=G.languageCode,m=this.V.isManifestless?oad(this,m,"386"):oad(this,m));if(m){var U=(m.index.z9(m.index.vF())-m.index.getStartTime(m.index.vF()))*1E3,c=new g.JJ$(this.N.S());this.D=new fBb(c,this.N,m,function(Q,D){w.qb(Q,G,D,U)},this.L||g.YW(m.info),function(){W.D&&W.D.reset();
W.K=!0})}};
g.N.Ez=function(){var G=this.K;this.K=!1;return G};
g.N.Ng=function(G){var m=this.N.S().J("html5_fallback_if_rawcc_missing");var w=this.V.V.rawcc!=null;if(!this.L||!w&&m)m=this.V.isManifestless?SFe(this,"386"):SFe(this);else{if(!w){this.logger.V(386248249,"rawcc used but unavailable");return}m=[new g.rF({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.rF({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}m=g.V(m);
for(w=m.next();!w.done;w=m.next())g.t5(this.Y,w.value);G.A0()};
g.N.p7=function(){this.D&&(this.D.dispose(),this.D=null)};
g.N.gq=function(){return""};
var jr=/^#(?:[0-9a-f]{3}){1,2}$/i;var C_e=["left","right","center","justify"];g.I(Z9,g.x);g.N=Z9.prototype;g.N.mR=function(G,m){this.kB=G;this.yj=m;var w=g.y7(this.element,this.element.parentElement);this.u6=G-w.x;this.Qj=m-w.y};
g.N.Ti=function(G,m){if(G!==this.kB||m!==this.yj){g.yR(this.element,"ytp-dragging")||g.Gb(this.element,"ytp-dragging");var w=g.mF(this.element);G=G-this.u6-.02*this.fV;var W=m-this.Qj-.02*this.hA,U=(G+w.width/2)/this.maxWidth*3;U=Math.floor(g.JQ(U,0,2));var c=(W+w.height/2)/this.maxHeight*3;c=Math.floor(g.JQ(c,0,2));m=U+c*3;G=(G+U/2*w.width)/this.maxWidth;G=g.JQ(G,0,1)*100;w=(W+c/2*w.height)/this.maxHeight;w=g.JQ(w,0,1)*100;this.Y.params.LT=m;this.Y.params.ix=w;this.Y.params.FD=G;this.Y.params.isDefault=
!1;this.V.LT=m;this.V.ix=w;this.V.FD=G;this.V.isDefault=!1;this.D6.LT=m;this.D6.ix=w;this.D6.FD=G;this.D6.isDefault=!1;this.wP()}};
g.N.o_=function(){g.wV(this.element,"ytp-dragging")};
g.N.wP=function(){this.wJ(this.L)};
g.N.wJ=function(G){var m=this.hY?0:Math.min(this.cP(),this.maxWidth),w=this.Qw(),W=this.hY;if(W){var U=getComputedStyle(this.D.parentNode);U=k0(U.borderLeftWidth)+k0(U.borderRightWidth)+k0(U.paddingLeft)+k0(U.paddingRight)}else U=0;var c=U;U="";this.Y.params.t0===3&&(U="rotate(180deg)");var Q=W?"calc(96% - "+c+"px)":"96%";g.eT(this.element,{top:0,left:0,right:"",bottom:"",width:m?m+"px":"",height:w?w+"px":"","max-width":Q,"max-height":Q,margin:"",transform:""});this.z_(G);U={transform:U,top:"",left:"",
width:m?m+"px":"",height:w?w+"px":"","max-width":"","max-height":""};var D=this.V.FD*.96+2;Q=this.V.LT;switch(Q){case 0:case 3:case 6:(W=this.V.DI.fontSizeIncrement)&&W>0&&this.V.t0!==2&&this.V.t0!==3&&(D=Math.max(D/(1+W*2),2));U.left=D+"%";break;case 1:case 4:case 7:U.left=D+"%";D=this.D.offsetWidth;m||D?(m=m||D+1,U.width=m+"px",U["margin-left"]=W?m/-2-c/2+"px":m/-2+"px"):U.transform+=" translateX(-50%)";break;case 2:case 5:case 8:U.right=100-D+"%"}W=this.V.ix*.96+2;switch(Q){case 0:case 1:case 2:U.top=
W+"%";break;case 3:case 4:case 5:U.top=W+"%";(w=w||this.element.clientHeight)?(U.height=w+"px",U["margin-top"]=w/-2+"px"):U.transform+=" translateY(-50%)";break;case 6:case 7:case 8:U.bottom=100-W+"%"}g.eT(this.element,U);if(this.K){w=this.D.offsetHeight;W=1;for(m=0;m<G.length;m++)U=G[m],typeof U.text==="string"&&(W+=U.text.split("\n").length-1,U.append||m===0||W++);w/=W;this.K.style.height=w+"px";this.K.style.width=w+"px";this.element.style.paddingLeft=w+5+"px";this.element.style.paddingRight=w+
5+"px";G=Number(this.element.style.marginLeft.replace("px",""))-w-5;w=Number(this.element.style.marginRight.replace("px",""))-w-5;this.element.style.marginLeft=G+"px";this.element.style.marginRight=w+"px"}};
g.N.z_=function(G){var m;for(m=0;m<G.length&&G[m]===this.L[m];m++);if(this.rd||this.L.length>m)m=0,this.rd=!1,this.L=[],this.C=this.Pk=this.pM=null,g.iQ(this.D);for(;m<G.length;m++)e0q(this,G[m])};
g.N.cP=function(){return 0};
g.N.Qw=function(){return 0};
g.N.toString=function(){return g.x.prototype.toString.call(this)};xtH.prototype.clear=function(){this.X=this.time=this.mode=0;this.V=[];this.reset()};
xtH.prototype.reset=function(){this.mode=0;this.D.reset(0);this.j.reset(1)};
var ulq=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];iX.prototype.set=function(G){this.type=G};
iX.prototype.get=function(){return this.type};
Kz.prototype.clear=function(){this.state=0};
Kz.prototype.update=function(){this.state=this.state===2?1:0};
Kz.prototype.yM=function(){return this.state!==0};
Kz.prototype.matches=function(G,m){return this.yM()&&G===this.Xo&&m===this.Ha};
XzH.prototype.reset=function(){this.timestamp=this.V=0};
NI.prototype.updateTime=function(G){for(var m=1;m<=15;++m)for(var w=1;w<=32;++w)this.X[m][w].timestamp=G};
NI.prototype.debugString=function(){for(var G="\n",m=1;m<=15;++m){for(var w=1;w<=32;++w){var W=this.X[m][w];G=W.V===0?G+"_":G+String.fromCharCode(W.V)}G+="\n"}return G};
NI.prototype.reset=function(G){for(var m=0;m<=15;m++)for(var w=0;w<=32;w++)this.X[m][w].reset();this.D=G;this.V=0;this.Y=this.row=1};
var yj9=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],GJn=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],mkH=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],wcq=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];cPm.prototype.reset=function(G,m){this.j=m;this.style.set(2);this.Y=this.K;this.D=this.L;this.V=this.Y;var w=(G<<2)+(m<<1);this.K.reset(w);this.L.reset(w);this.text.reset((G<<2)+(m<<1)+1)};
na9.prototype.reset=function(G){this.j=G;this.Y.clear();this.D=this.X;this.X.reset(G,0);this.K.reset(G,1)};OWd.prototype.D=function(){};g.I(Lz,g.nk);Lz.prototype.toString=function(){return g.nk.prototype.toString.call(this)};g.I(bX,g.J);bX.prototype.reset=function(){};g.I(tB,g.nk);tB.prototype.toString=function(){return g.nk.prototype.toString.call(this)};
var gC=0;g.I(dC,bX);dC.prototype.reset=function(){this.L={};this.Y=this.V=null;this.K=!0};
dC.prototype.X=function(G,m){G=G.firstChild;G.getAttribute("format");m=m||0;Number.isFinite(m);G=Array.from(G.childNodes);G=g.V(G);for(var w=G.next();!w.done;w=G.next())if(w=w.value,w.nodeType===1)switch(w.tagName){case "head":var W=w;break;case "body":var U=w}if(W)for(W=Array.from(W.childNodes),W=g.V(W),G=W.next();!G.done;G=W.next())if(G=G.value,G.nodeType===1)switch(G.tagName){case "pen":w=G.getAttribute("id");var c=this.pens,Q={},D=G.getAttribute("p");D&&Object.assign(Q,this.pens[D]);D=Rp(G,"b");
D!=null&&(Q.bold=D);D=Rp(G,"i");D!=null&&(Q.italic=D);D=Rp(G,"u");D!=null&&(Q.underline=D);D=pz(G,"et");D!=null&&(Q.charEdgeStyle=D);D=pz(G,"of");D!=null&&(Q.offset=D);D=Sr(G,"bc");D!=null&&(Q.background=D);D=Sr(G,"ec");D!=null&&(Q.U2=D);D=Sr(G,"fc");D!=null&&(Q.color=D);D=pz(G,"fs");D!=null&&D!==0&&(Q.fontFamily=D);D=fz(G,"sz");D!==void 0&&(Q.fontSizeIncrement=D/100-1);D=fz(G,"bo");D!==void 0&&(Q.backgroundOpacity=D/255);D=fz(G,"fo");D!==void 0&&(Q.textOpacity=D/255);D=pz(G,"rb");D!=null&&D!==10&&
D!==0&&(Q.RJ=D>10?D-1:D);G=pz(G,"hg");G!=null&&(Q.u9=G);c[w]=Q;break;case "ws":w=G.getAttribute("id");this.U[w]=atd(this,G);break;case "wp":w=G.getAttribute("id"),this.C[w]=ZW4(this,G)}if(U){W=[];U=Array.from(U.childNodes);U=g.V(U);for(G=U.next();!G.done;G=U.next())if(G=G.value,G.nodeType===1)switch(G.tagName){case "w":this.V=kJn(this,G,m,!1);(G=this.L[this.V.id])&&G.end>this.V.start&&(G.end=this.V.start);this.L[this.V.id]=this.V;W.push(this.V);break;case "p":var O=G;D=m;w=[];c=O.getAttribute("w")||
this.j;Q=!!Rp(O,"a");D=(fz(O,"t")||0)+D;var q=fz(O,"d")||5E3;Q||(!this.K&&this.Y&&this.Y.windowId===c&&this.Y.end>D&&(this.Y.end=D),this.Y&&this.Y.text==="\n"&&(this.Y.text=""));var T=Q?6:5,a=O.getAttribute("p");a=a?this.pens[a]:null;var Z=Array.from(O.childNodes);Z.length&&(this.K=O.getAttribute("d")!=null);for(O=0;O<Z.length;O++){var k=Z[O],K=void 0;O>0&&(Q=!0);var M=void 0;k.nodeType===1&&(M=k);if(M&&M.tagName==="s"){if((k=(k=M.getAttribute("p"))?this.pens[k]:null)&&k.RJ&&(k.RJ===1?(k=Z.slice(O,
O+4),k.length===4&&(K=THe(D,q,c,Q,T,k,this.pens),O+=3)):K=THe(D,q,c,Q,T,[M],this.pens)),!K){var t=M;K=D;M=q;k=c;var R=Q,f=T,P=t.textContent?t.textContent:"",E=t.getAttribute("p");E=E?this.pens[E]:null;t=fz(t,"t")||0;K=new Lz(K+t,M-t,f,k,P,R,E)}}else K=new Lz(D,q,T,c,k.textContent||"",Q,a);w.push(K);this.Y=K}if(w.length>0)for(w[0].windowId===this.j&&(this.V=kJn(this,G,m,!0),W.push(this.V)),G=g.V(w),w=G.next();!w.done;w=G.next())w=w.value,w.windowId=this.V.id,this.V.V.push(w),W.push(w)}m=W}else m=[];
return m};var wPe=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.I(Pi,bX);Pi.prototype.reset=function(){this.Y.clear()};
Pi.prototype.X=function(G,m){var w=JSON.parse(G);if(!w)return[];if(w.pens){G=0;for(var W=g.V(w.pens),U=W.next();!U.done;U=W.next()){U=U.value;var c={},Q=U.pParentId;Q&&Object.assign(c,this.V.get(Q));U.bAttr&&(c.bold=!0);U.iAttr&&(c.italic=!0);U.uAttr&&(c.underline=!0);Q=U.ofOffset;Q!=null&&(c.offset=Q);U.szPenSize!==void 0&&(c.fontSizeIncrement=U.szPenSize/100-1);Q=U.etEdgeType;Q!=null&&(c.charEdgeStyle=Q);U.ecEdgeColor!==void 0&&(c.U2=op(U.ecEdgeColor));Q=U.fsFontStyle;Q!=null&&Q!==0&&(c.fontFamily=
Q);U.fcForeColor!==void 0&&(c.color=op(U.fcForeColor));U.foForeAlpha!==void 0&&(c.textOpacity=U.foForeAlpha/255);U.bcBackColor!==void 0&&(c.background=op(U.bcBackColor));U.boBackAlpha!==void 0&&(c.backgroundOpacity=U.boBackAlpha/255);(Q=U.rbRuby)&&Q!==10&&(c.RJ=Q>10?Q-1:Q,c.textEmphasis=wPe.get(c.RJ));U.hgHorizGroup&&(c.u9=U.hgHorizGroup);this.V.set(G++,c)}}if(w.wsWinStyles)for(G=0,W=g.V(w.wsWinStyles),U=W.next();!U.done;U=W.next())U=U.value,c={},(Q=U.wsParentId)?Object.assign(c,this.j.get(Q)):Object.assign(c,
this.K),U.mhModeHint!==void 0&&(c.t_=U.mhModeHint),U.juJustifCode!==void 0&&(c.textAlign=U.juJustifCode),U.pdPrintDir!==void 0&&(c.t0=U.pdPrintDir),U.sdScrollDir!==void 0&&(c.lN=U.sdScrollDir),U.wfcWinFillColor!==void 0&&(c.windowColor=op(U.wfcWinFillColor)),U.wfoWinFillAlpha!==void 0&&(c.windowOpacity=U.wfoWinFillAlpha/255),this.j.set(G++,c);if(w.wpWinPositions)for(G=0,W=g.V(w.wpWinPositions),U=W.next();!U.done;U=W.next())U=U.value,c={},(Q=U.wpParentId)&&Object.assign(c,this.D.get(Q)),U.ahHorPos!==
void 0&&(c.FD=U.ahHorPos),U.apPoint!==void 0&&(c.LT=U.apPoint),U.avVerPos!==void 0&&(c.ix=U.avVerPos),U.ccCols!==void 0&&(c.Nh=U.ccCols),U.rcRows!==void 0&&(c.Zo=U.rcRows),this.D.set(G++,c);if(w.events){G=[];w=g.V(w.events);for(W=w.next();!W.done;W=w.next()){var D=W.value;U=(D.tStartMs||0)+m;c=D.dDurationMs||0;if(D.id)Q=String(D.id),W=iW4(this,D,U,c,Q),G.push(W),this.Y.set(Q,W);else{D.wWinId?Q=D.wWinId.toString():(Q="_"+gC++,W=iW4(this,D,U,c,Q),G.push(W),this.Y.set(Q,W));W=G;var O=D;c===0&&(c=5E3);
D=this.Y.get(Q);var q=!!O.aAppend,T=q?6:5,a=O.segs,Z=null;O.pPenId&&(Z=this.V.get(O.pPenId));for(O=0;O<a.length;O++){var k=a[O],K=k.utf8;if(K){var M=k.tOffsetMs||0,t=null;k.pPenId&&(t=this.V.get(k.pPenId));if((D.params.t_!=null?D.params.t_:D.V.length>1?1:0)===2&&q&&K==="\n")continue;k=null;var R=[],f;if(f=t&&t.RJ===1){f=a;var P=O;if(P+3>=f.length||!f[P+1].pPenId||!f[P+2].pPenId||!f[P+3].pPenId)f=!1;else{var E=f[P+1].pPenId;(E=this.V.get(E))&&E.RJ&&E.RJ===2?(E=f[P+2].pPenId,E=this.V.get(E),!E||!E.RJ||
E.RJ<3?f=!1:(E=f[P+3].pPenId,f=(E=this.V.get(E))&&E.RJ&&E.RJ===2?!0:!1)):f=!1}}if(f)M=a[O+1].utf8,k=a[O+3].utf8,f=a[O+2].utf8,P=this.V.get(a[O+2].pPenId),K=qT4(K,M,f,k,P),k=new Lz(U,c,T,Q,K,q,t),O+=3;else{if(K.indexOf("<")>-1){var e=void 0;R=t;f=Z;P=U;E=c;var A=M,Y=T,vW=q,Oo=[],QZ=g.BN("<html>"+K+"</html>");if(!QZ.getElementsByTagName("parsererror").length&&((e=QZ.firstChild)==null?0:e.childNodes.length))for(e=g.V(QZ.firstChild.childNodes),QZ=e.next();!QZ.done;QZ=e.next()){QZ=QZ.value;var D$=void 0,
me=void 0,dd=(me=(D$=QZ.textContent)==null?void 0:D$.replace(/\n/g,""))!=null?me:"";if(QZ.nodeType!==3||dd&&dd.match(/^ *$/)==null){D$={};Object.assign(D$,R||f);me=void 0;switch((me=QZ)==null?void 0:me.tagName){case "b":D$.bold=!0;break;case "i":D$.italic=!0;break;case "u":D$.underline=!0}Oo.push(new Lz(P+A,E-A,Y,D.id,dd,vW,D$))}}R=Oo}R.length||(R=[new Lz(U+M,c-M,T,D.id,K,q,t||Z)])}if(R.length)for(q=g.V(R),t=q.next();!t.done;t=q.next())t=t.value,W.push(t),D.V.push(t);else k&&(W.push(k),D.V.push(k))}q=
!0}}}m=G}else m=[];return m};g.I(hB,g.g6);hB.prototype.XU=function(G,m,w){V6c(this.videoData.videoId,G.vssId,w.qb)};
hB.prototype.Ng=function(G){if(this.audioTrack)for(var m=g.V(this.audioTrack.captionTracks),w=m.next();!w.done;w=m.next())g.t5(this.Y,w.value);G.A0()};g.I(lX,Z9);lX.prototype.z_=function(G){var m=this.Y.V;Z9.prototype.z_.call(this,G);for(G=G.length;G<m.length;G++){var w=m[G];if(c&&w.V===U)var W=c;else{W={};Object.assign(W,w.V);Object.assign(W,WIH);var U=w.V;var c=W}e0q(this,w,W)}};
var WIH={Ns:!0};g.I(Cz,OWd);Cz.prototype.D=function(G,m,w,W,U){if(w<W){var c="_"+gC++;w=w/1E3-this.K;W=W/1E3-this.K;G=new tB(w,W-w,5,c,{textAlign:0,LT:0,FD:m*2.5,ix:G*5.33});U=new Lz(w,W-w,5,c,U);this.Y.push(G);this.Y.push(U)}};
g.I(rC,bX);rC.prototype.X=function(G){G=new Cz(G,G.byteLength,this.Y);if(Kyc(G)){for(;G.byteOffset<G.V.byteLength;)for(G.version===0?G.X=JB(G)*(1E3/45):G.version===1&&(G.X=JB(G)*4294967296+JB(G)),G.j=Ey(G);G.j>0;G.j--){var m=Ey(G),w=Ey(G),W=Ey(G);m&4&&(m&3)===this.track&&(this.track===0||this.track===1)&&(m=this.V,m.V.push({time:G.X,type:this.track,Tb:w,m6:W,order:m.V.length}))}AjH(this.V,G);return G.Y}return[]};
rC.prototype.reset=function(){this.V.clear()};g.I(FN,Z9);g.N=FN.prototype;g.N.wP=function(){g.xE(this.aM)};
g.N.ue=function(){this.element.removeEventListener("transitionend",this.ue,!1);g.wV(this.element,"ytp-rollup-mode");this.wJ(this.TP,!0)};
g.N.Qw=function(){return this.X?this.YB:this.U};
g.N.cP=function(){return this.X?this.U:this.YB};
g.N.wJ=function(G,m){this.TP=G;if(this.Y.params.Zo){for(var w=0,W=0;W<this.L.length&&w<G.length;W++)this.L[W]===G[w]&&w++;w>0&&w<G.length&&(G=this.L.concat(G.slice(w)));this.x5=this.YB;this.U=this.YB=0;Z9.prototype.wJ.call(this,G);Vmd(this,m)}Z9.prototype.wJ.call(this,G)};Mmq.prototype.unload=function(){this.V!=null&&(this.N.removeEventListener("sabrCaptionsDataLoaded",this.V),this.V=null);this.xz=[];this.N.publish("sabrCaptionsBufferedRangesUpdated",this.xz)};
Mmq.prototype.gT=function(G){return{formatId:g.X3(G.info.V.info,this.L5),Ry:G.info.Ry+(this.L5?0:1),startTimeMs:G.info.j*1E3,durationMs:G.info.C*1E3}};g.I(er,g.g6);er.prototype.XU=function(G,m,w){this.p7();m=G.getId();m=m!=null&&m in this.V.V?this.V.V[m]:null;m||(m=G.languageCode,m=this.V.isManifestless?dkd(this,m,"386"):dkd(this,m));m&&(this.D=G,this.K=m,tmH(this.L,w),this.N.publish("sabrCaptionsTrackChanged",g.X3(m.info,this.V.L5)))};
er.prototype.Ng=function(G){var m=this.V.isManifestless?gOq(this,"386"):gOq(this);m=g.V(m);for(var w=m.next();!w.done;w=m.next())g.t5(this.Y,w.value);G.A0()};
er.prototype.p7=function(){this.D&&(this.D=this.K=null,this.L.unload(),this.N.publish("sabrCaptionsTrackChanged",null))};
er.prototype.gq=function(){return""};var pcc="WEBVTT".split("").map(function(G){return G.charCodeAt(0)});
g.I(Rdm,bX);
Rdm.prototype.X=function(G,m){G instanceof ArrayBuffer&&(G=g.aZ(new Uint8Array(G)));var w=[];G=G.split(U0g);for(var W=1;W<G.length;W++){var U=G[W],c=m;if(U!==""&&!s1c.test(U)){var Q=cXq.exec(U);if(Q&&Q.length>=4){var D=P8q(Q[1]),O=P8q(Q[2])-D;D+=c;var q=(Q=Q[3])?Q.split(" "):[];Q={};var T=null;var a="";var Z=null,k="";q=g.V(q);for(var K=q.next();!K.done;K=q.next())if(K=K.value.split(":"),K.length===2){var M=K[1];switch(K[0]){case "line":K=M.split(",");K[0].endsWith("%")&&(T=K[0],Q.ix=Number.parseInt(T,
10),K.length===2&&(a=K[1].trim()));break;case "position":K=M.split(",");Z=K[0];Q.FD=Number.parseInt(Z,10);K.length===2&&(k=K[1].trim());break;case "align":switch(M){case "start":Q.textAlign=0;break;case "middle":Q.textAlign=2;break;case "end":Q.textAlign=1}}}T||a||(a="end");if(!Z)switch(Q.textAlign){case 0:Q.FD=0;break;case 1:Q.FD=100;break;case 2:Q.FD=50}if(Q.textAlign!=null){T=0;switch(a){case "center":T+=3;break;case "end":T+=6;break;default:T+=0}switch(k){case "line-left":T+=0;break;case "center":T+=
1;break;case "line-right":T+=2;break;default:switch(Q.textAlign){case 0:T+=0;break;case 2:T+=1;break;case 1:T+=2}}a=T<0||T>8?7:T;Q.LT=a}U=U.substring(cXq.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");k=Q;Q=U;U={};if(Q.indexOf("<")<0&&Q.indexOf("&")<0)c=oOR(D,O,5,k),O=new Lz(D,O,5,c.id,Q,!1,g.$u(U)?void 0:U),w.push(c),w.push(O),c.V.push(O);else for(a=Q.split(Q1q),a.length===1?(Q=5,k=oOR(D,O,Q,k)):(T=Q=6,k=Object.assign({Nh:32},k),k=new tB(D,O,T,"_"+gC++,k)),w.push(k),T=D,Z=0;Z<a.length;Z++)q=a[Z],
Z%2===0?(K=g.BN("<html>"+q+"</html>"),K.getElementsByTagName("parsererror").length?(M=K.createElement("span"),M.appendChild(K.createTextNode(q))):M=K.firstChild,STc(this,T,O-(T-D),Q,k,Z>0,M,U,w)):T=P8q(q)+c}cXq.lastIndex=0}}return w};
var s1c=/^NOTE/,U0g=/(?:\r\n|\r|\n){2,}/,cXq=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Q1q=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.I(nz,g.J);nz.prototype.clear=function(){this.V&&this.V.dispose();this.V=null};
nz.prototype.reset=function(){this.V&&this.V.reset()};
nz.prototype.Hk=function(){g.J.prototype.Hk.call(this);this.clear()};var yT={windowColor:"#080808",windowOpacity:0,textAlign:2,LT:7,FD:50,ix:100,isDefault:!0,DI:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.I(FyH,g.bK);g.N=FyH.prototype;g.N.Hk=function(){if(this.j||this.J4){var G=this.N.u3();G&&!G.i6()&&G.r4()}else m0H(this,!1);g.bK.prototype.Hk.call(this)};
g.N.FE=function(){return this.h4.J("html5_honor_caption_availabilities_in_audio_track")&&this.D!=="LIVE"&&this.D!=="SABR_LIVE"};
g.N.Dn=function(){if(this.kB)return this.j||this.J4;var G=this.getAudioTrack();if(this.FE()){if(!G.captionTracks.length)return!1;if(!this.V)return!0}G=Ku9(G,g.Mu(this.h4));return G==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:G==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?x0(this):nOH(this)||x0(this)?!0:xkd(this)};
g.N.load=function(){g.bK.prototype.load.call(this);this.U=this.getAudioTrack();if(this.V)this.Y&&(this.yj.clear(),this.j?HWd(this,!0):this.player.getPresentingPlayerType()!==3&&this.V.XU(this.Y,"json3",this.aM),this.j||this.J4||Y0(this)||this.player.Dr("captionschanged",g.eL(this.Y)));else{var G;this.D==="OFFLINE"?G=new hB(this.player,this.videoData,this.getAudioTrack()):this.D==="SABR_LIVE"?G=new er(this.videoData.V,this.player):this.D==="LIVE"?G=new ap(this.videoData.V,this.player):this.D==="INNERTUBE"?
G=new g.d6(this.player,this.videoData,this.getAudioTrack()):G=new g.Rl(this.player,this.videoData.jZ,this.videoData.videoId,g.Aid(this.videoData),this.videoData.KT,this.videoData.eventId);this.V=G;g.r(this,this.V);this.V.Ng(this.aM)}};
g.N.unload=function(){this.j&&this.Y?HWd(this,!1):(this.EM&&g.u3(this.EM),this.player.eZ("captions"),this.pM=[],this.V&&this.V.p7(),this.yj.clear(),this.YB&&this.player.Zr(this.YB),this.LA());g.bK.prototype.unload.call(this);this.player.v7();this.player.Dr("captionschanged",{})};
g.N.create=function(){this.Dn()&&this.load();var G;a:{var m,w,W;if(this.h4.J("web_player_nitrate_promo_tooltip")&&((m=this.videoData.getPlayerResponse())==null?0:(w=m.captions)==null?0:(W=w.playerCaptionsTracklistRenderer)==null?0:W.enableTouchCaptionsNitrate)){var U,c;if(m=(G=this.videoData.getPlayerResponse())==null?void 0:(U=G.captions)==null?void 0:(c=U.playerCaptionsTracklistRenderer)==null?void 0:c.captionTracks)for(G=g.V(m),U=G.next();!U.done;U=G.next())if(U=U.value,U.kind==="asr"&&U.languageCode===
"en"){G=!0;break a}}G=!1}G&&this.N.publish("showpromotooltip",this.L.element)};
g.N.A0=function(){var G=Ku9(this.player.getAudioTrack(),g.Mu(this.h4));var m=G==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?Hi(this,this.C):G==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&x0(this)?uX(this):nOH(this)||this.C||xkd(this)?Hi(this,this.C):x0(this)?uX(this):null;if(this.j||this.J4){var w=g.sQ(this.V.Y,!0);G=[];for(var W=0;W<w.length;W++){var U=w[W],c=g.aI("TRACK");c.setAttribute("kind","subtitles");c.setAttribute("label",g.FW(U));c.setAttribute("srclang",g.ne(U));c.setAttribute("id",U.toString());
this.J4||c.setAttribute("src",this.V.gq(U,"vtt"));U===m&&c.setAttribute("default","1");G.push(c)}m=this.N.u3();m.Ca(G);G=m.n5();this.hY&&this.rd.T(G.textTracks,"change",this.RhE)}else!this.Y&&m&&XN(this,m),this.player.Dr("onCaptionsTrackListChanged"),this.player.Cv("onApiChange")};
g.N.RhE=function(){for(var G=this.N.u3().n5().textTracks,m=null,w=0;w<G.length;w++)if(G[w].mode==="showing")a:{m=g.sQ(this.V.Y,!0);for(var W=0;W<m.length;W++)if(m[W].toString()===G[w].id){m=m[W];break a}m=null}(this.loaded?this.Y:null)!==m&&XN(this,m,!0)};
g.N.UK6=function(){!this.Y&&this.j||this.unload()};
g.N.qb=function(G,m,w,W){if(G){var U;YTb(this,(U=this.Y)!=null?U:void 0);this.V.Ez()&&(this.pM=[],this.N.eZ("captions"),TP(this.Pk),this.yj.reset());a:{U=this.yj;W=W||0;w=ltm(U,G,w||0);G=[];try{for(var c=g.V(w),Q=c.next();!Q.done;Q=c.next()){var D=Q.value,O=D.trackData,q=D.VY,T=U.h4.J("safari_live_drm_captions_fix");if(typeof O!=="string"){w=G;var a=w.concat;if(T&&jOz(O))var Z=C8m(U,O,q);else{var k=U,K=m,M=O,t=q,R=W;if(!NHq(M))throw Error("Invalid binary caption track data");k.V||(k.V=new rC(R,K));
Z=k.V.X(M,t)}var f=a.call(w,Z)}else{if(O.substring(0,6)==="WEBVTT")var P=G.concat(C8m(U,O,q));else{w=G;var E=w.concat;b:{K=k=void 0;M=U;t=m;if(O[0]==="{")try{M.V||(M.V=new Pi(EOH(t)));var e=K=M.V.X(O,q);break b}catch(me){g.dR(me);e=[];break b}var A=g.BN(O);if(!A||!A.firstChild){var Y=Error("Invalid caption track data");Y.params=O;throw Y;}if(A.firstChild.tagName==="timedtext"){if(Number(A.firstChild.getAttribute("format"))===3){M.V||(M.V=new dC(EOH(t),M.h4));e=k=M.V.X(A,q);break b}var vW=Error("Unsupported subtitles format in web player (Format2)");
vW.params=O;throw vW;}if(A.firstChild.tagName==="transcript"){var Oo=Error("Unsupported subtitles format in web player (Format1)");Oo.params=O;throw Oo;}var QZ=Error("Invalid caption track data");QZ.params=O;throw QZ;}P=E.call(w,e)}f=P}G=f}var D$=G;break a}catch(me){U.logger.V(187101178,"Captions parsing failed: "+me.message+". ");U.clear();D$=[];break a}D$=void 0}m=D$;m.length>0&&(D$=this.Y,this.h0(D$,!!D$,Y0(this)?"g":this.C?"m":"s"));this.player.Zr(m,void 0,this.D==="LIVE"||this.D==="SABR_LIVE");
!this.C||this.J4||Y0(this)||g.Z_(this.h4)||g.D0(this.h4)||g.SX(this.h4)||this.h4.rd==="shortspage"||this.player.isInline()||(g.u3(this.EM),m=$km({LT:0,FD:5,ix:5,Zo:2,textAlign:0,t0:0,lang:"fr"}),this.Z6=[m],D$=["Cliquez sur "," pour acc\u00e9der aux param\u00e8tres."],this.u6||(c=new g.sG(g.bC()),g.r(this,c),this.u6=c.element),c=m.end-m.start,(Q=g.FW(this.Y))&&this.Z6.push(new Lz(m.start,c,0,m.id,Q)),this.Z6.push(new Lz(m.start,c,0,m.id,D$[0]),new Lz(m.start,c,0,m.id,this.u6,!0),new Lz(m.start,c,
0,m.id,D$[1],!0)),this.player.Zr(this.Z6),g.nT(this.EM));!this.C||this.J4||Y0(this)||(g.Mu(this.h4)?Bi(this,!0):AB(this,!0),this.U&&(this.U.D=this.Y),this.player.v7());this.C=!1}};
g.N.onCueRangeEnter=function(G){this.pM.push(G);TP(this.Pk)};
g.N.onCueRangeExit=function(G){g.Mn(this.pM,G);this.V instanceof ap&&this.V.L&&this.player.VK([G]);TP(this.Pk)};
g.N.getCaptionWindowContainerId=function(){return this.L.element.id};
g.N.Ry4=function(){G14(this,this.Z6);this.Z6=null};
g.N.Jq=function(){var G=this;if(!this.x5||!this.j){this.Pk.stop();g.o6o(this.OM);this.pM.sort(g.xm);var m=this.pM;if(this.YB){var w=g.g$(m,function(c){return this.YB.indexOf(c)===-1},this);
w.length&&(m=w)}m=g.V(m);for(w=m.next();!w.done;w=m.next())APf(this,w.value);m=g.V(Object.entries(this.M9));var W=m.next();for(w={};!W.done;w={Kb:void 0,Sb:void 0},W=m.next()){var U=g.V(W.value);W=U.next().value;U=U.next().value;w.Kb=W;w.Sb=U;this.OM[w.Kb]?(w.Sb.element.parentNode||(w.Sb instanceof FN||w.Sb instanceof lX||g.wQ(this.M9,function(c){return function(Q,D){D!==c.Kb&&Q.Y.params.LT===c.Sb.Y.params.LT&&Q.Y.params.FD===c.Sb.Y.params.FD&&Q.Y.params.ix===c.Sb.Y.params.ix&&(Q.dispose(),delete G.M9[D]);
return D===c.Kb}}(w),this),this.L.element.appendChild(w.Sb.element)),w.Sb.wJ(this.OM[w.Kb])):(w.Sb.dispose(),delete this.M9[w.Kb])}}};
g.N.eyj=function(){rPH(this,{},!0);this.player.Dr("captionssettingschanged")};
g.N.Jb=function(){var G=yT.DI;G={background:G.background,backgroundOpacity:G.backgroundOpacity,charEdgeStyle:G.charEdgeStyle,color:G.color,fontFamily:G.fontFamily,fontSizeIncrement:G.fontSizeIncrement,fontStyle:G.bold&&G.italic?3:G.bold?1:G.italic?2:0,textOpacity:G.textOpacity,windowColor:yT.windowColor,windowOpacity:yT.windowOpacity};var m=gaf()||{};m.background!=null&&(G.background=m.background);m.backgroundOverride!=null&&(G.backgroundOverride=m.backgroundOverride);m.backgroundOpacity!=null&&(G.backgroundOpacity=
m.backgroundOpacity);m.backgroundOpacityOverride!=null&&(G.backgroundOpacityOverride=m.backgroundOpacityOverride);m.charEdgeStyle!=null&&(G.charEdgeStyle=m.charEdgeStyle);m.charEdgeStyleOverride!=null&&(G.charEdgeStyleOverride=m.charEdgeStyleOverride);m.color!=null&&(G.color=m.color);m.colorOverride!=null&&(G.colorOverride=m.colorOverride);m.fontFamily!=null&&(G.fontFamily=m.fontFamily);m.fontFamilyOverride!=null&&(G.fontFamilyOverride=m.fontFamilyOverride);m.fontSizeIncrement!=null&&(G.fontSizeIncrement=
m.fontSizeIncrement);m.fontSizeIncrementOverride!=null&&(G.fontSizeIncrementOverride=m.fontSizeIncrementOverride);m.fontStyle!=null&&(G.fontStyle=m.fontStyle);m.fontStyleOverride!=null&&(G.fontStyleOverride=m.fontStyleOverride);m.textOpacity!=null&&(G.textOpacity=m.textOpacity);m.textOpacityOverride!=null&&(G.textOpacityOverride=m.textOpacityOverride);m.windowColor!=null&&(G.windowColor=m.windowColor);m.windowColorOverride!=null&&(G.windowColorOverride=m.windowColorOverride);m.windowOpacity!=null&&
(G.windowOpacity=m.windowOpacity);m.windowOpacityOverride!=null&&(G.windowOpacityOverride=m.windowOpacityOverride);return G};
g.N.Ej=function(G,m){var w={};Object.assign(w,gaf());Object.assign(w,G);rPH(this,w,m);this.player.Dr("captionssettingschanged")};
g.N.LA=function(){!this.j&&this.loaded&&(g.y9(this.M9,function(G,m){G.dispose();delete this.M9[m]},this),this.Jq())};
g.N.MI=function(G,m){switch(G){case "fontSize":if(isNaN(m))break;G=g.JQ(m,-2,4);this.Ej({fontSizeIncrement:G});return G;case "reload":m&&!this.j&&XN(this,this.Y,!0);break;case "stickyLoading":m!==void 0&&this.h4.C&&(g.Mu(this.h4)?Bi(this,!!m):AB(this,!!m));break;case "track":return yP9(this,m);case "tracklist":return this.V?g.iI(g.sQ(this.V.Y,!(!m||!m.includeAsr)),function(w){return g.eL(w)}):[];
case "translationLanguages":return this.V?this.V.j.map(function(w){return Object.assign({},w)}):[];
case "sampleSubtitles":this.j||m===void 0||m0H(this,!!m);break;case "sampleSubtitlesCustomized":this.j||m0H(this,!!m,m);break;case "recommendedTranslationLanguages":return g.Mx();case "defaultTranslationSourceTrackIndices":return this.V?this.V.C:[]}};
g.N.getOptions=function(){var G="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.h4.C&&G.push("stickyLoading");return G};
g.N.S5=function(){var G=this.Y;if(this.N.BE("captions")){if(this.h4.J("html5_modify_caption_vss_logging")){var m;return(G=(m=this.videoData.dQ)!=null?m:null)?{cc:g.i3W(G)}:{}}if(G)return m=G.vssId,G.translationLanguage&&m&&(m="t"+m+"."+g.ne(G)),{cc:m}}return{}};
g.N.y1C=function(){this.isSubtitlesOn()?(g.Mu(this.h4)?Bi(this,!1):AB(this,!1),YTb(this),XN(this,null,!0)):this.UI()};
g.N.UI=function(){var G=Y0(this)||!this.Y?Hi(this,!0):this.Y;G&&this.Vz(G.vssId,"m");this.isSubtitlesOn()||XN(this,Y0(this)||!this.Y?Hi(this,!0):this.Y,!0)};
g.N.isSubtitlesOn=function(){return!!this.loaded&&!!this.Y&&!Y0(this)};
g.N.OMj=function(){var G=Y0(this);x0(this,G)?XN(this,this.getAudioTrack().V,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.FE()&&(this.C=!1,this.Y=null,this.V&&(this.V.dispose(),this.V=null)),this.Dn()&&(G?XN(this,Hi(this,!1),!1):this.load()))};
g.N.K9=function(G){G&&(this.D6={top:G.top,right:G.right,bottom:G.bottom,left:G.left,width:1-G.left-G.right,height:1-G.top-G.bottom},this.L.element.style.top=this.D6.top*100+"%",this.L.element.style.left=this.D6.left*100+"%",this.L.element.style.width=this.D6.width*100+"%",this.L.element.style.height=this.D6.height*100+"%",this.L.element.style.position="absolute",G=XcH(this))&&(this.L.element.style.width=G.width+"px",this.L.element.style.height=G.height+"px")};
g.N.onVideoDataChange=function(G,m){G==="newdata"&&(this.videoData=m,this.loaded&&this.unload(),this.C=!1,this.Y=null,this.V&&(this.V.dispose(),this.V=null,this.player.Dr("captionschanged",{})),this.Dn()&&this.load())};
g.N.getAudioTrack=function(){return this.player.getAudioTrack()};
g.N.esj=function(){var G=this.N.u3();G&&!G.i6()&&G.r4();this.N.isFullscreen()?(this.j=this.kB=!0,this.loaded&&this.A0()):(this.kB=this.h4.controlsType==="3",this.j=JPH(this));XN(this,this.Y)};
g.N.C9=function(){var G,m,w,W=(G=this.videoData.getPlayerResponse())==null?void 0:(m=G.captions)==null?void 0:(w=m.playerCaptionsTracklistRenderer)==null?void 0:w.openTranscriptCommand;W&&this.player.G2("innertubeCommand",W)};
g.N.h0=function(G,m,w){var W=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,U="";G&&(U=G.vssId,U=U.replace(W,""));var c="";G&&G.getId()&&(c=G.getId()||"");G&&G.getXtags()&&(G=G.getXtags(),G=G.replace(W,""),c=c.concat(";"+G));this.N.h0(m?U:"",m?c:"",w)};
g.N.Vz=function(G,m){G=(G||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");G.length>0&&this.N.Vz(G,m)};g.Lf("captions",FyH);})(_yt_player);
