(function(g){var window=this;'use strict';var j1z=function(G){G.publish("autonavvisibility")},SRd=function(G,m){G.G2("onAutonavCoundownStarted",m)},P$q=function(G){var m,w,W;
return G==null?void 0:(m=G.playerOverlays)==null?void 0:(w=m.playerOverlayRenderer)==null?void 0:(W=w.autoplay)==null?void 0:W.playerOverlayAutoplayRenderer},QB=function(G){var m=G.S(),w=m.D;
g.x.call(this,{B:"a",Z:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:w?m.U:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},G:[{B:"div",fM:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},G:[{B:"div",W:{"aria-label":"{{timestamp}}"},fM:["ytp-autonav-timestamp"],l6:"{{duration}}"},{B:"div",fM:["ytp-autonav-live-stamp"],l6:"En direct"},
{B:"div",fM:["ytp-autonav-upcoming-stamp"],l6:"\u00c0 venir"},{B:"div",Z:"ytp-autonav-list-overlay",G:[{B:"div",Z:"ytp-autonav-mix-text",l6:"Mix"},{B:"div",Z:"ytp-autonav-mix-icon"}]}]},{B:"div",fM:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],l6:"{{title}}"},{B:"div",fM:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],l6:"{{author}}"},{B:"div",fM:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],l6:"{{views_and_publish_time}}"}]});this.N=
G;this.suggestion=null;this.V=w;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},vD=function(G,m){m=m===void 0?!1:m;
g.x.call(this,{B:"div",Z:"ytp-autonav-endscreen-countdown-overlay"});var w=this;this.L=m;this.cancelCommand=this.K=void 0;this.X=0;this.container=new g.x({B:"div",Z:"ytp-autonav-endscreen-countdown-container"});g.r(this,this.container);this.container.KM(this.element);m=G.S();var W=m.D;this.N=G;this.suggestion=null;this.onVideoDataChange("newdata",this.N.getVideoData());this.T(G,"videodatachange",this.onVideoDataChange);this.V=new g.x({B:"div",Z:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},G:[{B:"div",Z:"ytp-autonav-endscreen-upnext-header"},{B:"div",Z:"ytp-autonav-endscreen-upnext-alternative-header",l6:"{{autoplayAlternativeHeader}}"},{B:"a",Z:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:W?m.U:""},G:[{B:"div",Z:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},G:[{B:"div",W:{"aria-label":"{{timestamp}}"},fM:["ytp-autonav-timestamp"],
l6:"{{duration}}"},{B:"div",fM:["ytp-autonav-live-stamp"],l6:"En direct"},{B:"div",fM:["ytp-autonav-upcoming-stamp"],l6:"\u00c0 venir"}]},{B:"div",Z:"ytp-autonav-endscreen-video-info",G:[{B:"div",Z:"ytp-autonav-endscreen-premium-badge"},{B:"div",Z:"ytp-autonav-endscreen-upnext-title",l6:"{{title}}"},{B:"div",Z:"ytp-autonav-endscreen-upnext-author",l6:"{{author}}"},{B:"div",Z:"ytp-autonav-view-and-date",l6:"{{views_and_publish_time}}"},{B:"div",Z:"ytp-autonav-author-and-view",l6:"{{author_and_views}}"}]}]}]});
g.r(this,this.V);this.V.KM(this.container.element);W||this.T(this.V.nM("ytp-autonav-endscreen-link-container"),"click",this.HH);this.N.createClientVe(this.container.element,this,115127);this.N.createClientVe(this.V.nM("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.x({B:"div",Z:"ytp-autonav-overlay"});g.r(this,this.overlay);this.overlay.KM(this.container.element);this.Y=new g.x({B:"div",Z:"ytp-autonav-endscreen-button-container"});g.r(this,this.Y);this.Y.KM(this.container.element);
this.cancelButton=new g.x({B:"button",fM:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",m.J("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{"aria-label":"Annuler la lecture automatique"},l6:"Annuler"});g.r(this,this.cancelButton);this.cancelButton.KM(this.Y.element);this.cancelButton.listen("click",this.Fy,this);this.N.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.x({B:"a",fM:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button",m.J("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{href:"{{url}}",role:"button","aria-label":"Lire la vid\u00e9o suivante"},l6:"Regarder"});g.r(this,this.playButton);this.playButton.KM(this.Y.element);this.playButton.listen("click",this.HH,this);this.N.createServerVe(this.playButton.element,this.playButton,!0);(m=this.N.getVideoData())&&ohm(this,m);this.D=new g.ey(function(){h1R(w)},500);
g.r(this,this.D);this.d9();this.T(G,"autonavvisibility",this.d9);this.N.J("web_autonav_color_transition")&&(this.T(G,"autonavchange",this.yA),this.T(G,"onAutonavCoundownStarted",this.k2M))},D4=function(G){var m=G.N.TC(!0,G.N.isFullscreen());
g.UN(G.container.element,"ytp-autonav-endscreen-small-mode",G.OY(m));g.UN(G.container.element,"ytp-autonav-endscreen-is-premium",!!G.suggestion&&!!G.suggestion.dK2);g.UN(G.N.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!G.N.JP());g.UN(G.N.getRootNode(),"countdown-running",G.zW());g.UN(G.container.element,"ytp-player-content",G.N.JP());g.eT(G.overlay.element,{width:m.width+"px"});if(!G.zW()){G.N.JP()?lMb(G,Math.round(C$q(G)/1E3)):lMb(G);m=!!G.suggestion&&!!G.suggestion.a8;var w=G.N.JP()||
!m;g.UN(G.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!w&&m);g.UN(G.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",w&&!m);G.Y.tY(G.N.JP());g.UN(G.element,"ytp-enable-w2w-color-transitions",EhH(G))}},h1R=function(G){var m=C$q(G),w=Math,W=w.min;
var U=G.X?Date.now()-G.X:0;w=W.call(w,U,m);lMb(G,Math.ceil((m-w)/1E3));m-w<=500&&G.zW()?G.select(!0):G.zW()&&G.D.start()},C$q=function(G){if(G.N.isFullscreen()){var m;
G=(m=G.N.getVideoData())==null?void 0:m.Ta;return G===-1||G===void 0?8E3:G}return G.N.o8()>=0?G.N.o8():g.mN(G.N.S().experiments,"autoplay_time")||1E4},ohm=function(G,m){m=m.getWatchNextResponse();
var w,W;m=(w=P$q(m))==null?void 0:(W=w.nextButton)==null?void 0:W.buttonRenderer;G.K=m==null?void 0:m.navigationEndpoint;w=m==null?void 0:m.trackingParams;G.playButton&&w&&G.N.setTrackingParams(G.playButton.element,w)},EhH=function(G){var m;
return!((m=G.N.getVideoData())==null||!m.watchToWatchTransitionRenderer)},lMb=function(G,m){m=m===void 0?-1:m;
G=G.V.nM("ytp-autonav-endscreen-upnext-header");g.iQ(G);if(m>=0){m=String(m);var w="Prochaine vid\u00e9o dans $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],W="Prochaine vid\u00e9o dans $SECONDS".indexOf(w);if(W>=0){G.appendChild(g.ZL("Prochaine vid\u00e9o dans $SECONDS".slice(0,W)));var U=g.aI("span");g.XU(U,"ytp-autonav-endscreen-upnext-header-countdown-number");g.zj(U,m);G.appendChild(U);G.appendChild(g.ZL("Prochaine vid\u00e9o dans $SECONDS".slice(W+w.length)));return}}g.zj(G,"\u00c0 suivre")},
OM=function(G,m){g.x.call(this,{B:"div",
fM:["html5-endscreen","ytp-player-content",m||"base-endscreen"]});this.created=!1;this.player=G},qY=function(G){g.x.call(this,{B:"div",
fM:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},G:[{B:"div",Z:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{B:"span",Z:"ytp-upnext-top",G:[{B:"span",Z:"ytp-upnext-header",l6:"\u00c0 suivre"},{B:"span",Z:"ytp-upnext-title",l6:"{{title}}"},{B:"span",Z:"ytp-upnext-author",l6:"{{author}}"}]},{B:"a",Z:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Lire la vid\u00e9o suivante"},G:[{B:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},G:[{B:"circle",Z:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{B:"circle",Z:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{B:"path",Z:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{B:"span",Z:"ytp-upnext-bottom",G:[{B:"span",Z:"ytp-upnext-cancel"},{B:"span",Z:"ytp-upnext-paused",
l6:"La lecture automatique est d\u00e9sactiv\u00e9e"}]}]});this.api=G;this.cancelButton=null;this.K=this.nM("ytp-svg-autoplay-ring");this.X=this.notification=this.V=this.suggestion=null;this.D=new g.ey(this.eE,5E3,this);this.Y=0;var m=this.nM("ytp-upnext-cancel");this.cancelButton=new g.x({B:"button",fM:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Annuler la lecture automatique"},l6:"Annuler"});g.r(this,this.cancelButton);this.cancelButton.listen("click",this.WB,this);this.cancelButton.KM(m);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.r(this,this.D);this.api.createClientVe(this.element,this,18788);m=this.nM("ytp-upnext-autoplay-icon");this.T(m,"click",this.Sh);this.api.createClientVe(m,this,115130);this.BH();this.T(G,"autonavvisibility",this.BH);this.T(G,"mdxnowautoplaying",this.qe9);this.T(G,"mdxautoplaycanceled",this.Z5y);g.UN(this.element,"ytp-upnext-mobile",this.api.S().Y)},JX4=function(G,m){if(m)return m;
if(G.api.isFullscreen()){var w;G=(w=G.api.getVideoData())==null?void 0:w.Ta;return G===-1||G===void 0?8E3:G}return G.api.o8()>=0?G.api.o8():g.mN(G.api.S().experiments,"autoplay_time")||1E4},rXq=function(G,m){m=JX4(G,m);
var w=Math,W=w.min;var U=(0,g.V6)()-G.Y;w=W.call(w,U,m);m=m===0?1:Math.min(w/m,1);G.K.setAttribute("stroke-dashoffset",""+-211*(m+1));m>=1&&G.zW()&&G.api.getPresentingPlayerType()!==3?G.select(!0):G.zW()&&G.V.start()},Tx=function(G){OM.call(this,G,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.x({B:"div",Z:"ytp-suggestion-panel",G:[{B:"div",fM:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],l6:"Plus de vid\u00e9os"}]});this.C=new g.x({B:"div",Z:"ytp-suggestions-container"});this.videos=[];this.X=null;this.K=this.L=!1;this.Y=new vD(this.player);g.r(this,this.Y);this.Y.KM(this.element);G.getVideoData().CV?this.V=this.Y:(this.V=new qY(G),g.ye(this.player,this.V.element,4),g.r(this,this.V));this.overlay=new g.x({B:"div",
Z:"ytp-autonav-overlay-cancelled-state"});g.r(this,this.overlay);this.overlay.KM(this.element);this.D=new g.Mh(this);g.r(this,this.D);g.r(this,this.table);this.table.KM(this.element);this.table.show();g.r(this,this.C);this.C.KM(this.table.element);this.hide()},$d=function(G){var m=G.JP();
m!==G.K&&(G.K=m,j1z(G.player),G.K?(G.Y!==G.V&&G.Y.hide(),G.table.hide()):(G.Y!==G.V&&G.Y.show(),G.table.show()))},FIe=function(G){OM.call(this,G,"videowall-endscreen");
var m=this;this.N=G;this.stills=[];this.X=this.videoData=null;this.D=this.L=!1;this.C=null;g.Gb(this.element,"modern-videowall-endscreen");this.Y=new g.Mh(this);g.r(this,this.Y);this.K=new g.ey(function(){g.Gb(m.element,"ytp-show-tiles")},0);
g.r(this,this.K);this.table=new g.sG({B:"div",Z:"ytp-modern-endscreen-content"});g.r(this,this.table);this.table.KM(this.element);G.getVideoData().CV?this.V=new vD(G,!0):this.V=new qY(G);g.r(this,this.V);g.ye(this.player,this.V.element,4);G.createClientVe(this.element,this,158789);this.hide()},ax=function(G){return g.G7(G.player)&&G.VV()&&!G.X},Z4=function(G){var m=G.JP();
m!==G.L&&(G.L=m,j1z(G.player))},e1q=function(G){OM.call(this,G,"subscribecard-endscreen");
this.V=new g.x({B:"div",Z:"ytp-subscribe-card",G:[{B:"img",Z:"ytp-author-image",W:{src:"{{profilePicture}}"}},{B:"div",Z:"ytp-subscribe-card-right",G:[{B:"div",Z:"ytp-author-name",l6:"{{author}}"},{B:"div",Z:"html5-subscribe-button-container"}]}]});g.r(this,this.V);this.V.KM(this.element);var m=G.getVideoData();this.subscribeButton=new g.UW("S'abonner",null,"Se d\u00e9sabonner",null,!0,!1,m.lk,m.subscribed,"trailer-endscreen",null,G,!1);g.r(this,this.subscribeButton);this.subscribeButton.KM(this.V.nM("html5-subscribe-button-container"));
this.T(G,"videodatachange",this.T2);this.T2();this.hide()},kd=function(G){var m=G.S(),w=g.Nh||g.Gw?{style:"will-change: opacity"}:void 0,W=m.D,U=["ytp-videowall-still"];
m.Y&&U.push("ytp-videowall-show-text");g.x.call(this,{B:"a",fM:U,W:{href:"{{url}}",target:W?m.U:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},G:[{B:"div",Z:"ytp-videowall-still-image",W:{style:"{{background}}"}},{B:"span",Z:"ytp-videowall-still-info",W:{"aria-hidden":"true"},G:[{B:"span",Z:"ytp-videowall-still-info-bg",G:[{B:"span",Z:"ytp-videowall-still-info-content",W:w,G:[{B:"span",Z:"ytp-videowall-still-info-title",l6:"{{title}}"},
{B:"span",Z:"ytp-videowall-still-info-author",l6:"{{author_and_views}}"},{B:"span",Z:"ytp-videowall-still-info-live",l6:"En direct"},{B:"span",Z:"ytp-videowall-still-info-duration",l6:"{{duration}}"}]}]}]},{B:"span",fM:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},G:[{B:"span",Z:"ytp-videowall-still-listlabel-icon"},"Playlist",{B:"span",Z:"ytp-videowall-still-listlabel-length",G:[" (",{B:"span",l6:"{{playlist_length}}"},")"]}]},{B:"span",fM:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},G:[{B:"span",Z:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{B:"span",Z:"ytp-videowall-still-listlabel-length",l6:" (50+)"}]}]});this.suggestion=null;this.Y=W;this.api=G;this.V=new g.Mh(this);g.r(this,this.V);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.V.T(G,"videodatachange",this.onVideoDataChange);G.createServerVe(this.element,this);this.onVideoDataChange()},ir=function(G){OM.call(this,G,"videowall-endscreen");
var m=this;this.N=G;this.X=0;this.stills=[];this.D=this.videoData=null;this.K=this.C=!1;this.U=null;this.Y=new g.Mh(this);g.r(this,this.Y);this.L=new g.ey(function(){g.Gb(m.element,"ytp-show-tiles")},0);
g.r(this,this.L);var w=new g.x({B:"button",fM:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Pr\u00e9c\u00e9dente"},G:[g.aL()]});g.r(this,w);w.KM(this.element);w.listen("click",this.ws,this);this.table=new g.sG({B:"div",Z:"ytp-endscreen-content"});g.r(this,this.table);this.table.KM(this.element);w=new g.x({B:"button",fM:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Suivante"},G:[g.ZQ()]});g.r(this,w);w.KM(this.element);w.listen("click",this.vB,this);G.getVideoData().CV?this.V=new vD(G,
!0):this.V=new qY(G);g.r(this,this.V);g.ye(this.player,this.V.element,4);G.createClientVe(this.element,this,158789);this.hide()},Kl=function(G){return g.G7(G.player)&&G.VV()&&!G.D},NY=function(G){var m=G.JP();
m!==G.C&&(G.C=m,j1z(G.player))},nhb=function(G,m){g.x.call(this,{B:"button",
fM:["ytp-watch-on-youtube-button","ytp-button"],l6:"{{content}}"});this.N=G;this.buttonType=this.buttonType=m;this.sI();this.buttonType===2&&g.Gb(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.sI);this.tY(!0)},Ix=function(G){OM.call(this,G,"watch-again-on-youtube-endscreen");
this.watchButton=new nhb(G,1);g.r(this,this.watchButton);this.watchButton.KM(this.element);g.fem(G)&&(this.V=new g.X4(G),g.r(this,this.V),this.Y=new g.x({B:"div",fM:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],W:{tabIndex:"-1"},G:[this.V]}),g.r(this,this.Y),this.V.KM(this.Y.element),this.Y.KM(this.element));G.createClientVe(this.element,this,156914);this.hide()},YRq=function(G){g.bK.call(this,G);
var m=this;this.endScreen=null;this.V=this.Y=this.X=!1;this.listeners=new g.Mh(this);g.r(this,this.listeners);var w=G.S();G.isEmbedsShortsMode()?this.endScreen=new Ix(G):x0q(G)?(this.X=!0,uEq(this),this.V?this.endScreen=new Tx(G):w.J("delhi_modern_endscreen")?this.endScreen=new FIe(G):this.endScreen=new ir(G)):w.Bj?this.endScreen=new e1q(G):this.endScreen=new OM(G);g.r(this,this.endScreen);g.ye(G,this.endScreen.element,4);Hpz(this);this.listeners.T(G,"videodatachange",this.onVideoDataChange,this);
this.listeners.T(G,g.uA("endscreen"),function(W){m.onCueRangeEnter(W)});
this.listeners.T(G,g.H_("endscreen"),function(W){m.onCueRangeExit(W)})},uEq=function(G){var m=G.player.getVideoData();
if(!m||G.V===m.Ml&&G.Y===m.CV)return!1;G.V=m.Ml;G.Y=m.CV;return!0},x0q=function(G){G=G.S();
return G.CV&&!G.Bj&&!G.disableOrganicUi},Hpz=function(G){G.player.eZ("endscreen");
var m=G.player.getVideoData();m=new g.nk(Math.max((m.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var w=new g.nk(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});G.player.Zr([m,w])};
g.nB.prototype.o8=g.Uo(6,function(){return this.app.o8()});
g.is.prototype.o8=g.Uo(5,function(){return this.getVideoData().Sp});
g.Jt.prototype.kH=g.Uo(4,function(G){this.Fu().kH(G)});
g.A5.prototype.kH=g.Uo(3,function(G){this.Da!==G&&(this.Da=G,this.du())});
g.I(QB,g.x);QB.prototype.select=function(){this.N.NH(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.oB||void 0)&&this.N.logClick(this.element)};
QB.prototype.onClick=function(G){g.tf(G,this.N,this.V,this.suggestion.sessionData||void 0)&&this.select()};
QB.prototype.onKeyPress=function(G){switch(G.keyCode){case 13:case 32:G.defaultPrevented||(this.select(),G.preventDefault())}};g.I(vD,g.x);g.N=vD.prototype;g.N.Sd=function(G){this.suggestion!==G&&(this.suggestion=G,g.qG(this.V,G),this.playButton.updateValue("url",this.suggestion.OT()),D4(this))};
g.N.zW=function(){return this.X>0};
g.N.cN=function(){this.zW()||(this.X=Date.now(),h1R(this),SRd(this.N,C$q(this)),g.UN(this.N.getRootNode(),"countdown-running",this.zW()))};
g.N.yQ=function(){this.Pb();h1R(this);var G=this.V.nM("ytp-autonav-endscreen-upnext-header");G&&g.zj(G,"\u00c0 suivre")};
g.N.Pb=function(){this.zW()&&(this.D.stop(),this.X=0)};
g.N.select=function(G){this.N.nextVideo(!1,G===void 0?!1:G);this.Pb()};
g.N.HH=function(G){g.tf(G,this.N)&&(G.currentTarget===this.playButton.element?this.N.logClick(this.playButton.element):G.currentTarget===this.V.nM("ytp-autonav-endscreen-link-container")&&(G=this.V.nM("ytp-autonav-endscreen-link-container"),this.N.logVisibility(G,!0),this.N.logClick(G)),this.K?(this.N.G2("innertubeCommand",this.K),this.Pb()):this.select())};
g.N.Fy=function(){this.N.logClick(this.cancelButton.element);g.uU(this.N,!0);this.cancelCommand&&this.N.G2("innertubeCommand",this.cancelCommand)};
g.N.onVideoDataChange=function(G,m){ohm(this,m);G=m.getWatchNextResponse();var w,W;G=(w=P$q(G))==null?void 0:(W=w.cancelButton)==null?void 0:W.buttonRenderer;this.cancelCommand=G==null?void 0:G.command};
g.N.k2M=function(G){if(EhH(this)){var m=this.N.getVideoData().watchToWatchTransitionRenderer,w=m==null?void 0:m.fromColorPaletteDark;m=m==null?void 0:m.toColorPaletteDark;if(w&&m){var W=this.element;W.style.setProperty("--w2w-start-background-color",g.PZ(w.surgeColor));W.style.setProperty("--w2w-start-primary-text-color",g.PZ(w.primaryTitleColor));W.style.setProperty("--w2w-start-secondary-text-color",g.PZ(w.secondaryTitleColor));W.style.setProperty("--w2w-end-background-color",g.PZ(m.surgeColor));
W.style.setProperty("--w2w-end-primary-text-color",g.PZ(m.primaryTitleColor));W.style.setProperty("--w2w-end-secondary-text-color",g.PZ(m.secondaryTitleColor));W.style.setProperty("--w2w-animation-duration",G+"ms")}g.UN(this.element,"ytp-w2w-animate",!0)}};
g.N.yA=function(G){this.N.J("web_autonav_color_transition")&&G!==2&&g.UN(this.element,"ytp-w2w-animate",!1)};
g.N.d9=function(){var G=this.N.JP();this.L&&this.Y5!==G&&this.tY(G);D4(this);this.N.logVisibility(this.container.element,G);this.N.logVisibility(this.cancelButton.element,G);this.N.logVisibility(this.V.nM("ytp-autonav-endscreen-link-container"),G);this.N.logVisibility(this.playButton.element,G)};
g.N.OY=function(G){return G.width<400||G.height<459};g.I(OM,g.x);g.N=OM.prototype;g.N.create=function(){this.created=!0};
g.N.destroy=function(){this.created=!1};
g.N.VV=function(){return!1};
g.N.JP=function(){return!1};
g.N.e_=function(){return!1};g.I(qY,g.x);g.N=qY.prototype;g.N.eE=function(){this.notification&&(this.D.stop(),this.JA(this.X),this.X=null,this.notification.close(),this.notification=null)};
g.N.Sd=function(G){this.suggestion=G;g.qG(this,G,"hqdefault.jpg")};
g.N.BH=function(){this.tY(this.api.JP());this.api.logVisibility(this.element,this.api.JP());this.api.logVisibility(this.nM("ytp-upnext-autoplay-icon"),this.api.JP());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.JP())};
g.N.yY6=function(){window.focus();this.eE()};
g.N.cN=function(G){var m=this;this.zW()||(g.mq("a11y-announce","\u00c0 suivre "+this.suggestion.title),this.Y=(0,g.V6)(),this.V=new g.ey(function(){rXq(m,G)},25),rXq(this,G),SRd(this.api,JX4(this,G)));
g.wV(this.element,"ytp-upnext-autoplay-paused")};
g.N.hide=function(){g.x.prototype.hide.call(this)};
g.N.zW=function(){return!!this.V};
g.N.yQ=function(){this.Pb();this.Y=(0,g.V6)();rXq(this);g.Gb(this.element,"ytp-upnext-autoplay-paused")};
g.N.Pb=function(){this.zW()&&(this.V.dispose(),this.V=null)};
g.N.select=function(G){G=G===void 0?!1:G;if(this.api.S().J("autonav_notifications")&&G&&window.Notification&&typeof document.hasFocus==="function"){var m=Notification.permission;m==="default"?Notification.requestPermission():m!=="granted"||document.hasFocus()||(this.eE(),this.notification=new Notification("\u00c0 suivre",{body:this.suggestion.title,icon:this.suggestion.iG()}),this.X=this.T(this.notification,"click",this.yY6),this.D.start())}this.Pb();this.api.nextVideo(!1,G)};
g.N.Sh=function(G){!g.II(this.cancelButton.element,G.target)&&g.tf(G,this.api)&&(this.api.JP()&&this.api.logClick(this.nM("ytp-upnext-autoplay-icon")),this.select())};
g.N.WB=function(){this.api.JP()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.uU(this.api,!0)};
g.N.qe9=function(G){this.api.getPresentingPlayerType();this.show();this.cN(G)};
g.N.Z5y=function(){this.api.getPresentingPlayerType();this.Pb();this.hide()};
g.N.Hk=function(){this.Pb();this.eE();g.x.prototype.Hk.call(this)};g.I(Tx,OM);g.N=Tx.prototype;g.N.create=function(){OM.prototype.create.call(this);this.D.T(this.player,"appresize",this.Wm);this.D.T(this.player,"onVideoAreaChange",this.Wm);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.MP);this.D.T(this.player,"onAutonavCancelled",this.gs);this.onVideoDataChange()};
g.N.show=function(){OM.prototype.show.call(this);(this.L||this.X&&this.X!==this.videoData.clientPlaybackNonce)&&g.uU(this.player,!1);g.G7(this.player)&&this.VV()&&!this.X?($d(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.V.select(!0):this.V.cN():this.videoData.autonavState===3&&this.V.yQ()):(g.uU(this.player,!0),$d(this));this.Wm()};
g.N.hide=function(){OM.prototype.hide.call(this);this.V.yQ();$d(this)};
g.N.Wm=function(){var G=this.player.TC(!0,this.player.isFullscreen());$d(this);D4(this.Y);g.UN(this.element,"ytp-autonav-cancelled-small-mode",this.OY(G));g.UN(this.element,"ytp-autonav-cancelled-tiny-mode",this.Kf(G));g.UN(this.element,"ytp-autonav-cancelled-mini-mode",G.width<=400||G.height<=360);this.overlay&&g.eT(this.overlay.element,{width:G.width+"px"});if(!this.K)for(G=0;G<this.videos.length;G++)g.UN(this.videos[G].element,"ytp-suggestion-card-with-margin",G%2===1)};
g.N.onVideoDataChange=function(){var G=this.player.getVideoData();if(this.videoData!==G&&G){this.videoData=G;if((G=this.videoData.suggestions)&&G.length||this.player.J("web_player_autonav_empty_suggestions_fix")){var m=g.bw(this.videoData);m&&(this.V.Sd(m),this.V!==this.Y&&this.Y.Sd(m))}if(G&&G.length)for(m=0;m<B$R.length;++m){var w=B$R[m];if(G&&G[w]){this.videos[m]=new QB(this.player);var W=this.videos[m];w=G[w];W.suggestion!==w&&(W.suggestion=w,g.qG(W,w));g.r(this,this.videos[m]);this.videos[m].KM(this.C.element)}}this.Wm()}};
g.N.MP=function(G){G===1?(this.L=!1,this.X=this.videoData.clientPlaybackNonce,this.V.Pb(),this.Y5&&this.Wm()):(this.L=!0,this.JP()&&(G===2?this.V.cN():G===3&&this.V.yQ()))};
g.N.gs=function(G){G?this.MP(1):(this.X=null,this.L=!1)};
g.N.VV=function(){return this.videoData.autonavState!==1};
g.N.OY=function(G){return(G.width<910||G.height<459)&&!this.Kf(G)&&!(G.width<=400||G.height<=360)};
g.N.Kf=function(G){return G.width<800&&!(G.width<=400||G.height<=360)};
g.N.JP=function(){return this.Y5&&g.G7(this.player)&&this.VV()&&!this.X};
var B$R=[1,3,2,4];g.I(FIe,OM);g.N=FIe.prototype;g.N.create=function(){OM.prototype.create.call(this);var G=this.player.getVideoData();G&&(this.videoData=G);this.fO();this.Y.T(this.player,"appresize",this.fO);this.Y.T(this.player,"onVideoAreaChange",this.fO);this.Y.T(this.player,"videodatachange",this.onVideoDataChange);this.Y.T(this.player,"autonavchange",this.FX);this.Y.T(this.player,"onAutonavCancelled",this.OC);G=this.videoData.autonavState;G!==this.C&&this.FX(G);this.Y.T(this.element,"transitionend",this.uj)};
g.N.destroy=function(){g.L6(this.Y);g.WP(this.stills);this.stills=[];OM.prototype.destroy.call(this);g.wV(this.element,"ytp-show-tiles");this.K.stop();this.C=this.videoData.autonavState};
g.N.VV=function(){return this.videoData.autonavState!==1};
g.N.show=function(){var G=this.Y5;OM.prototype.show.call(this);g.wV(this.element,"ytp-show-tiles");this.player.S().Y?g.xE(this.K):this.K.start();(this.D||this.X&&this.X!==this.videoData.clientPlaybackNonce)&&g.uU(this.player,!1);ax(this)?(Z4(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.V.select(!0):this.V.cN():this.videoData.autonavState===3&&this.V.yQ()):(g.uU(this.player,!0),Z4(this));G!==this.Y5&&this.player.logVisibility(this.element,!0)};
g.N.hide=function(){var G=this.Y5;OM.prototype.hide.call(this);this.V.yQ();Z4(this);G!==this.Y5&&this.player.logVisibility(this.element,!1)};
g.N.uj=function(G){G.target===this.element&&this.fO()};
g.N.fO=function(){var G,m,w,W;var U=((G=this.videoData)==null?0:(m=G.suggestions)==null?0:m.length)?(w=this.videoData)==null?void 0:w.suggestions:[(W=this.videoData)==null?void 0:g.bw(W)];if(U.length){m=this.N.TC(!0,this.N.isFullscreen());G=Math.floor((m.width-64+16)/(g.JQ(m.width*.27,250,450)+16));m=Math.min(3,Math.floor((m.height-64)/((m.width-64-(G-1)*16)/G*.5625+70)));g.Wj(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.Gb(this.element,"ytp-modern-endscreen-limit-rows-"+m);g.UN(this.element,"ytp-modern-endscreen-single-item",G===1);g.UN(this.element,"ytp-modern-endscreen-row-0",m===0);G=this.table.element;G.ariaLive="polite";this.V.Sd(g.bw(this.videoData));this.V instanceof vD&&D4(this.V);g.UN(this.element,"ytp-endscreen-takeover",ax(this));Z4(this);m=0;G.ariaBusy="true";w=U.length;for(W=0;W<w;W++){var c=W%w,Q=this.stills[W];Q||(Q=new g.Tc(this.player),this.stills[W]=Q,G.appendChild(Q.element));g.Rhk(Q,U[c]);m++}this.stills.length=
m}};
g.N.onVideoDataChange=function(){var G=this.player.getVideoData(1);this.videoData!==G&&(G!=null&&g.bw(G)?(this.videoData=G,this.fO()):this.player.XC("missg",{vid:(G==null?void 0:G.videoId)||"",cpn:(G==null?void 0:G.clientPlaybackNonce)||""}))};
g.N.e_=function(){return this.V.zW()};
g.N.FX=function(G){G===1?(this.D=!1,this.X=this.videoData.clientPlaybackNonce,this.V.Pb(),this.Y5&&this.fO()):(this.D=!0,this.Y5&&ax(this)&&(G===2?this.V.cN():G===3&&this.V.yQ()))};
g.N.OC=function(G){if(G){for(G=0;G<this.stills.length;G++)this.N.logVisibility(this.stills[G].element,!0);this.FX(1)}else this.X=null,this.D=!1;this.fO()};
g.N.JP=function(){return this.Y5&&ax(this)};g.I(e1q,OM);e1q.prototype.T2=function(){var G=this.player.getVideoData();this.V.update({profilePicture:G.profilePicture,author:G.author});this.subscribeButton.channelId=G.lk;var m=this.subscribeButton;G.subscribed?m.V():m.Y()};g.I(kd,g.x);kd.prototype.select=function(){this.api.NH(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.oB||void 0)&&this.api.logClick(this.element)};
kd.prototype.onClick=function(G){if(g.wF(this.api.S())&&this.api.J("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var m=this.suggestion.OT(),w={};g.BB(this.api,w);m=g.i8(m,w);g.g4(m,this.api,G)}else g.tf(G,this.api,this.Y,this.suggestion.sessionData||void 0)&&this.select()};
kd.prototype.onKeyPress=function(G){switch(G.keyCode){case 13:case 32:G.defaultPrevented||(this.select(),G.preventDefault())}};
kd.prototype.onVideoDataChange=function(){var G=this.api.getVideoData(),m=this.api.S();this.Y=G.UL?!1:m.D};g.I(ir,OM);g.N=ir.prototype;g.N.create=function(){OM.prototype.create.call(this);var G=this.player.getVideoData();G&&(this.videoData=G);this.Jt();this.Y.T(this.player,"appresize",this.Jt);this.Y.T(this.player,"onVideoAreaChange",this.Jt);this.Y.T(this.player,"videodatachange",this.onVideoDataChange);this.Y.T(this.player,"autonavchange",this.Wg);this.Y.T(this.player,"onAutonavCancelled",this.Gi);G=this.videoData.autonavState;G!==this.U&&this.Wg(G);this.Y.T(this.element,"transitionend",this.AJ)};
g.N.destroy=function(){g.L6(this.Y);g.WP(this.stills);this.stills=[];OM.prototype.destroy.call(this);g.wV(this.element,"ytp-show-tiles");this.L.stop();this.U=this.videoData.autonavState};
g.N.VV=function(){return this.videoData.autonavState!==1};
g.N.show=function(){var G=this.Y5;OM.prototype.show.call(this);g.wV(this.element,"ytp-show-tiles");this.player.S().Y?g.xE(this.L):this.L.start();(this.K||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.uU(this.player,!1);Kl(this)?(NY(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.V.select(!0):this.V.cN():this.videoData.autonavState===3&&this.V.yQ()):(g.uU(this.player,!0),NY(this));G!==this.Y5&&this.player.logVisibility(this.element,!0)};
g.N.hide=function(){var G=this.Y5;OM.prototype.hide.call(this);this.V.yQ();NY(this);G!==this.Y5&&this.player.logVisibility(this.element,!1)};
g.N.AJ=function(G){G.target===this.element&&this.Jt()};
g.N.Jt=function(){var G,m,w,W;var U=((G=this.videoData)==null?0:(m=G.suggestions)==null?0:m.length)?(w=this.videoData)==null?void 0:w.suggestions:[(W=this.videoData)==null?void 0:g.bw(W)];if(U.length){g.Gb(this.element,"ytp-endscreen-paginate");var c=this.N.TC(!0,this.N.isFullscreen());if(G=g.oa(this.N))G=G.Ia()?48:32,c.width-=G*2;var Q=c.width/c.height;W=96/54;m=G=2;var D=Math.max(c.width/96,2),O=Math.max(c.height/54,2);w=U.length;var q=w*4;for(q-=4;q>0&&(G<D||m<O);){var T=G/2,a=m/2,Z=G<=D-2&&q>=
a*4,k=m<=O-2&&q>=T*4;if((T+1)/a*W/Q>Q/(T/(a+1)*W)&&k)q-=T*4,m+=2;else if(Z)q-=a*4,G+=2;else if(k)q-=T*4,m+=2;else break}W=!1;q>=12&&w*4-q<=6&&(m>=4||G>=4)&&(W=!0);q=G*96;D=m*54;Q=q/D<Q?c.height/D:c.width/q;Q=Math.min(Q,2);q=Math.floor(Math.min(c.width,q*Q));D=Math.floor(Math.min(c.height,D*Q));c=this.table.element;c.ariaLive="polite";g.Gr(c,q,D);g.eT(c,{marginLeft:q/-2+"px",marginTop:D/-2+"px"});this.V.Sd(g.bw(this.videoData));this.V instanceof vD&&D4(this.V);g.UN(this.element,"ytp-endscreen-takeover",
Kl(this));NY(this);q+=4;D+=4;Q=0;c.ariaBusy="true";for(O=0;O<G;O++)for(T=0;T<m;T++)if(a=Q,k=0,W&&O>=G-2&&T>=m-2?k=1:T%2===0&&O%2===0&&(T<2&&O<2?T===0&&O===0&&(k=2):k=2),a=g.rO(a+this.X,w),k!==0){Z=this.stills[Q];Z||(Z=new kd(this.player),this.stills[Q]=Z,c.appendChild(Z.element));var K=Math.floor(D*T/m),M=Math.floor(q*O/G),t=Math.floor(D*(T+k)/m)-K-4,R=Math.floor(q*(O+k)/G)-M-4;g.BC(Z.element,M,K);g.Gr(Z.element,R,t);g.eT(Z.element,"transitionDelay",(T+O)/20+"s");g.UN(Z.element,"ytp-videowall-still-mini",
k===1);g.UN(Z.element,"ytp-videowall-still-large",k>2);k=Math.max(R,t);g.UN(Z.element,"ytp-videowall-still-round-large",k>=256);g.UN(Z.element,"ytp-videowall-still-round-medium",k>96&&k<256);g.UN(Z.element,"ytp-videowall-still-round-small",k<=96);a=U[a];Z.suggestion!==a&&(Z.suggestion=a,k=Z.api.S(),K=g.yR(Z.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.qG(Z,a,K),g.wF(k)&&!Z.api.J("web_player_log_click_before_generating_ve_conversion_params")&&(k=a.OT(),K={},g.Ra(Z.api,"addEmbedsConversionTrackingParams",
[K]),k=g.i8(k,K),Z.updateValue("url",k)),(a=(a=a.sessionData)&&a.itct)&&Z.api.setTrackingParams(Z.element,a));Q++}c.ariaBusy="false";g.UN(this.element,"ytp-endscreen-paginate",Q<w);for(U=this.stills.length-1;U>=Q;U--)G=this.stills[U],g.Nb(G.element),g.w$(G);this.stills.length=Q}};
g.N.onVideoDataChange=function(){var G=this.player.getVideoData(1);this.videoData!==G&&(G!=null&&g.bw(G)?(this.X=0,this.videoData=G,this.Jt()):this.player.XC("missg",{vid:(G==null?void 0:G.videoId)||"",cpn:(G==null?void 0:G.clientPlaybackNonce)||""}))};
g.N.vB=function(){this.X+=this.stills.length;this.Jt()};
g.N.ws=function(){this.X-=this.stills.length;this.Jt()};
g.N.e_=function(){return this.V.zW()};
g.N.Wg=function(G){G===1?(this.K=!1,this.D=this.videoData.clientPlaybackNonce,this.V.Pb(),this.Y5&&this.Jt()):(this.K=!0,this.Y5&&Kl(this)&&(G===2?this.V.cN():G===3&&this.V.yQ()))};
g.N.Gi=function(G){if(G){for(G=0;G<this.stills.length;G++)this.N.logVisibility(this.stills[G].element,!0);this.Wg(1)}else this.D=null,this.K=!1;this.Jt()};
g.N.JP=function(){return this.Y5&&Kl(this)};g.I(nhb,g.x);g.N=nhb.prototype;g.N.sI=function(){switch(this.buttonType){case 1:var G="Regarder \u00e0 nouveau sur YouTube";var m=156915;break;case 2:G="Continuer \u00e0 regarder sur YouTube";m=156942;break;default:G="Continuer \u00e0 regarder sur YouTube",m=156942}this.update({content:G});this.N.hasVe(this.element)&&this.N.destroyVe(this.element);this.N.createClientVe(this.element,this,m)};
g.N.onClick=function(G){this.N.J("web_player_log_click_before_generating_ve_conversion_params")&&this.N.logClick(this.element);g.g4(this.getVideoUrl(),this.N,G);this.N.J("web_player_log_click_before_generating_ve_conversion_params")||this.N.logClick(this.element)};
g.N.getVideoUrl=function(){var G=!0;switch(this.buttonType){case 1:G=!0;break;case 2:G=!1}G=this.N.getVideoUrl(G,!1,!1,!0);var m=this.N.S();if(g.wF(m)){var w={};g.wF(m)&&g.Ra(this.N,"addEmbedsConversionTrackingParams",[w]);G=g.i8(G,w)}return G};
g.N.logVisibility=function(){this.N.logVisibility(this.element,this.Y5&&this.j)};
g.N.show=function(){g.x.prototype.show.call(this);this.logVisibility()};
g.N.hide=function(){g.x.prototype.hide.call(this);this.logVisibility()};
g.N.Sn=function(G){g.x.prototype.Sn.call(this,G);this.logVisibility()};g.I(Ix,OM);Ix.prototype.hasSuggestions=function(){var G;return(G=this.V)==null?void 0:G.hasSuggestions()};
Ix.prototype.show=function(){if(this.player.getPlayerState()!==3){OM.prototype.show.call(this);var G=this.Y;if(G){var m=this.V.hasSuggestions();g.UN(this.element,"ytp-shorts-branded-ui",m);m?G.show():G.hide()}var w;(w=g.oa(this.player))==null||w.kH(!0);this.player.logVisibility(this.element,!0);this.watchButton.Sn(!0)}};
Ix.prototype.hide=function(){OM.prototype.hide.call(this);var G;(G=g.oa(this.player))==null||G.kH(!1);this.player.logVisibility(this.element,!1);this.watchButton.Sn(!1)};g.I(YRq,g.bK);g.N=YRq.prototype;g.N.Dn=function(){var G=this.player.getVideoData(),m=G.mutedAutoplay&&(G.limitedPlaybackDurationInSeconds>0||G.endSeconds>0||G.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!m)return!0;var w;var W=!!((G==null?0:g.bw(G))||(G==null?0:(w=G.suggestions)==null?0:w.length));W=!x0q(this.player)||W;G=G.XD;w=this.player.ZO();return W&&!G&&!w&&!m};
g.N.JP=function(){return this.endScreen.JP()};
g.N.E8=function(){return this.JP()?this.endScreen.e_():!1};
g.N.Hk=function(){this.player.eZ("endscreen");g.bK.prototype.Hk.call(this)};
g.N.load=function(){var G=this.player.getVideoData();var m=G.transitionEndpointAtEndOfStream;if(m&&m.videoId){var w=this.player.jn().QM.get("heartbeat"),W=g.bw(G);!W||m.videoId!==W.videoId||G.bN?(this.player.NH(m.videoId,void 0,void 0,!0,!0,m),w&&w.Zv("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),G=!0):G=!1}else G=!1;G||(g.bK.prototype.load.call(this),this.endScreen.show())};
g.N.unload=function(){g.bK.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.N.onCueRangeEnter=function(G){this.Dn()&&(this.endScreen.created||this.endScreen.create(),G.getId()==="load"&&this.load())};
g.N.onCueRangeExit=function(G){G.getId()==="load"&&this.loaded&&this.unload()};
g.N.onVideoDataChange=function(){Hpz(this);this.X&&uEq(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.V?this.endScreen=new Tx(this.player):this.endScreen=new ir(this.player),g.r(this,this.endScreen),g.ye(this.player,this.endScreen.element,4))};g.Lf("endscreen",YRq);})(_yt_player);
